#!/bin/bash
# AF, 27.Feb.23
# Baut die SAS/C Amiga Version mittels vamos. Das smake habe ich nicht zum Laufen bekommen (wegen rx und setenv), deshalb die einzelnen Aufrufe, die das smakefile
# auf dem Amgiga macht, direkt ausfuehren.

# auf dem Amiga Compilieren, damit wir wissen, welche C-Files notwendig sind
# for FILE in $(ls *.o); do echo sc NOOPT NODEBUG $FILE  "IGNORE=51" "DEFINE=STATIC_FCN=static" "DEFINE=STATIC_VAR=static" "DEFINE=__BYTE_ORDER__=1" "DEFINE=__ORDER_BIG_ENDIAN__=1"; done
# mit dem Ergebnis dann folgende Zeilen gebastelt:

echo 
echo "Checking if still compileable with SAS/C"
echo "----------------------------------------"
echo

set -e  # Abbruch bei Fehler
set -x  # Zeige Kommandos

rm -f *.o WCSGST WCS >/dev/null


# extra Optionen fuer WCS, mit und ohne GST
vamos -q sc MAKEGST=WCSGST WCS.c "IGNORE=51" "DEFINE=STATIC_FCN=static" "DEFINE=STATIC_VAR=static" "DEFINE=__BYTE_ORDER__=1" "DEFINE=__ORDER_BIG_ENDIAN__=1"
vamos -q sc NOGST WCS.c "IGNORE=51" "DEFINE=STATIC_FCN=static" "DEFINE=STATIC_VAR=static" "DEFINE=__BYTE_ORDER__=1" "DEFINE=__ORDER_BIG_ENDIAN__=1"

# Jetzt der Rest
vamos -q sc NOOPT NODEBUG AGUI.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG BitMaps.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG Cloud.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG CloudGUI.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG ColorBlends.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG Commands.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG DEM.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG DEMGUI.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG DEMObject.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG DLG.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG DataBase.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG DataOps.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG DataOpsGUI.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG DefaultParams.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG DiagnosticGUI.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG DispatchGUI.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG EdDBaseGUI.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG EdEcoGUI.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG EdMoGUI.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG EdPar.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG EdSetExtrasGUI.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG EdSetGUI.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG EditGui.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG EvenMoreGUI.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG Foliage.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG FoliageGUI.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG Fractal.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG GenericParams.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG GenericTLGUI.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG GlobeMap.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG GlobeMapSupport.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG GrammarTable.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG HyperKhorner4M-1.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG Images.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG InteractiveDraw.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG InteractiveUtils.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG InteractiveView.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG LWSupport.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG LineSupport.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG MakeFaces.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG Map.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG MapExtra.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG MapGUI.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG MapLineObject.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG MapSupport.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG MapTopo.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG MapTopoObject.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG MapUtil.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG Memory.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG MoreGUI.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG Params.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG ParamsGUI.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG PlotGUI.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG RequesterGUI.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG RexxSupport.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG ScratchPad.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG ScreenModeGUI.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG Support.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG TLSupportGUI.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG TimeLinesGUI.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG Tree.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG Version.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1 DEFINE=BUILDID=\"AF_BuildID\"
vamos -q sc NOOPT NODEBUG VocabTable.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG Wave.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG WaveGUI.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG nncrunch.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG nngridr.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG BigEndianReadWrite.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1
vamos -q sc NOOPT NODEBUG sasc_functions.c IGNORE=51 DEFINE=STATIC_FCN=static DEFINE=STATIC_VAR=static DEFINE=__BYTE_ORDER__=1 DEFINE=__ORDER_BIG_ENDIAN__=1

# und linken
vamos -q slink LIB:c.o WCS.o WITH WCSObjs.lnk lib:utillib.with LIB LIB:scm881.lib libvgl.a LIB:sc.lib LIB:amiga.lib TO WCS ND

