#!/bin/bash

# AF, HWG, 21.Sep23
# Tests if git pre-commit hook is installed (should perform additional tests before checkin is permitted)
# is called from makefile in post-build-step (Eclipse-> Properties-> C/C++ Build -> Settings -> Build Steps ->Post Build Steps)
# does not return an error code (just meant to be a warning)

if [ -f ../../.git/hooks/pre-commit ]; then  # will be called from Buildconfiguration Subdir, e.g. 3DNature/Amiga/68020
  echo pre-commit hook ok 
else
  echo !!!! pre-commit hook not installed !!!
  echo "Do 'ln -s ../../pre-commit pre-commit' in .git/hooks!"
  for i in {1..3}; do
    printf '\e[?5h'; sleep 0.2 ; printf '\e[?5l'; sleep 0.2  # flashes the screen
  done
fi
