/* Cloud.h
** Header file for Cloud generation and manipulation functions for WCS.
** Written by Gary R. Huber, Jan 1995.
*/

#ifndef CLOUD_H
#define CLOUD_H

#define CLOUDLAYER_ALT		0
#define CLOUDLAYER_COVG		1
#define CLOUDLAYER_DENS		2
#define CLOUDLAYER_ILLUM	3

/* long */
#define CLOUDDATA_RANDSEED	0
#define CLOUDDATA_ROWS		1
#define CLOUDDATA_COLS		2
/* short */
#define CLOUDDATA_NUMKEYS	0
#define CLOUDDATA_NUMWAVES	1
#define CLOUDDATA_NUMLAYERS	2
#define CLOUDDATA_DYNAMIC	3
#define CLOUDDATA_CLOUDTYPE	4
/* double */
#define CLOUDDATA_COVERAGE	0
#define CLOUDDATA_DENSITY	1
#define CLOUDDATA_NWLAT		2
#define CLOUDDATA_SELAT		3
#define CLOUDDATA_NWLON		4
#define CLOUDDATA_SELON		5
#define CLOUDDATA_MINALT	6
#define CLOUDDATA_STDDEV	7
#define CLOUDDATA_H		8
#define CLOUDDATA_LATOFF	9
#define CLOUDDATA_LONOFF	10
#define CLOUDDATA_MAXALT	20	/* not setable from GUI */

#define CLOUDTYPE_CIRRUS	0
#define CLOUDTYPE_STRATUS	1
#define CLOUDTYPE_NIMBUS	2
#define CLOUDTYPE_CUMULUS	3

#define FRAMES_PER_HOUR		108000.0

/* Cloud file stuff */

#define CLOUD_CURRENT_VERSION	1

#define CLOUDDATA_SHT_NUMKEYS	1
#define CLOUDDATA_LNG_ROWS	2
#define CLOUDDATA_LNG_COLS	3
#define CLOUDDATA_SHT_NUMWAVES	4
#define CLOUDDATA_SHT_NUMLAYERS	5
#define CLOUDDATA_SHT_DYNAMIC	6
#define CLOUDDATA_SHT_CLOUDTYPE	7
#define CLOUDDATA_DBL_COVERAGE	8
#define CLOUDDATA_DBL_DENSITY	9
#define CLOUDDATA_DBL_NWLAT	10
#define CLOUDDATA_DBL_SELAT	11
#define CLOUDDATA_DBL_NWLON	12
#define CLOUDDATA_DBL_SELON	13
#define CLOUDDATA_DBL_MAXALT	14
#define CLOUDDATA_DBL_MINALT	15
#define CLOUDDATA_LNG_RANDSEED	16
#define CLOUDDATA_DBL_STDDEV	17
#define CLOUDDATA_DBL_H		18
#define CLOUDDATA_BYT_COLOR	19
#define CLOUDDATA_DBL_LATOFF	20
#define CLOUDDATA_DBL_LONOFF	21
#define CLOUDDATA_SHT_KFITEMS	22
#define CLOUDDATA_SHT_KEYFRAME	23
#define CLOUDDATA_SHT_KFGROUP	24
#define CLOUDDATA_SHT_KFITEM	25
#define CLOUDDATA_FLT_KFTCB	26
#define CLOUDDATA_SHT_KFLINEAR	27
#define CLOUDDATA_FLT_KFVALUES	28


#define CLOUDLAYER_NEW		50
#define CLOUDLAYER_DBL_ALT	51
#define CLOUDLAYER_DBL_COVG	52
#define CLOUDLAYER_DBL_DENS	53
#define CLOUDLAYER_DBL_ILLUM	54

#define WAVE_NEW		100
#define WAVE_SHT_NUMKEYS	101	
#define WAVE_DBL_AMP		102
#define WAVE_DBL_LENGTH		103
#define WAVE_DBL_VELOCITY	104
#define WAVE_DBL_LAT		105
#define WAVE_DBL_LON		106

#endif /* CLOUD_H */
