/*
** GUIDefines.h (renamed from gisgui_defines.h on 14 Jan 1994 CXH)
** Define values for return ID's as used by Amiga MUI system for World 
** Construction Set.
** By Gary R. Huber and Chris "Xenon" Hanson, 1993.
*/

#ifndef _GUIDEFINES_H_
#define _GUIDEFINES_H_

#include "Defines.h"

/* General define values */

#define MO_APPLICATION	0x01000000
#define MO_DATABASE	0x02000000
#define MO_DATAOPS	0x03000000
#define MO_MAPPING	0x04000000
#define MO_EDITING	0x05000000
#define MO_IMAGEOPS	0x06000000
#define MO_RENDER	0x07000000
#define MO_EXTRAS	0x08000000
#define MO_EXIT		0x09000000
#define MO_WAVEED	0x0a000000
#define MO_TIMELINES	0x0b000000

#define MO_DUMMYMENU	0x0f000000

#define WI_WINDOW(y)	(y << 16)

#define WI_WINDOW0	0x00000000
#define WI_WINDOW1	0x00010000
#define WI_WINDOW2	0x00020000
#define WI_WINDOW3	0x00030000
#define WI_WINDOW4	0x00040000
#define WI_WINDOW5	0x00050000
#define WI_WINDOW6	0x00060000
#define WI_WINDOW7	0x00070000
#define WI_WINDOW8	0x00080000
#define WI_WINDOW9	0x00090000
#define WI_WINDOW10	0x000a0000
#define WI_WINDOW11	0x000b0000
#define WI_WINDOW12	0x000c0000
#define WI_WINDOW13	0x000d0000
#define WI_WINDOW14	0x000e0000
#define WI_WINDOW15	0x000f0000
#define WI_WINDOW16	0x00100000
#define WI_WINDOW17	0x00110000
#define WI_WINDOW18	0x00120000
#define WI_WINDOW19	0x00130000
#define WI_WINDOW20	0x00140000
#define WI_WINDOW21	0x00150000
#define WI_WINDOW22	0x00160000

#define GP_OPEN_WINDOW	0x00000000
#define GP_BUTTONS1	0x00000100
#define GP_BUTTONS2	0x00000200
#define GP_BUTTONS3	0x00000300
#define GP_BUTTONS4	0x00000400
#define GP_PROP1	0x00000500
#define GP_PROP2	0x00000600
#define GP_PROP3	0x00000700
#define GP_PROP4	0x00000800
#define GP_ARROW1	0x00000900
#define GP_ARROW2	0x00000a00
#define GP_ARROW3	0x00000b00
#define GP_ARROW4	0x00000c00
#define GP_ARROW5	0x00000d00
#define GP_ARROW6	0x00000e00
#define GP_ARROW7	0x00000f00
#define GP_ARROW8	0x00001000
#define GP_ARROW9	0x00001100
#define GP_ARROW10	0x00001200
#define GP_STRING1	0x00001300
#define GP_STRING2	0x00001400
#define GP_STRING3	0x00001500
#define GP_STRING4	0x00001600
#define GP_TEXT1	0x00001700
#define GP_TEXT2	0x00001800
#define GP_TEXT3	0x00001900
#define GP_TEXT4	0x00001a00
#define GP_CYCLE1	0x00001b00
#define GP_CYCLE2	0x00001c00
#define GP_CYCLE3	0x00001d00
#define GP_CYCLE4	0x00001e00
#define GP_RADIO1	0x00001f00
#define GP_RADIO2	0x00002000
#define GP_RADIO3	0x00002100
#define GP_RADIO4	0x00002200
#define GP_LIST1	0x00002300
#define GP_LIST2	0x00002400
#define GP_LIST3	0x00002500
#define GP_LIST4	0x00002600
#define GP_BUTTONS5	0x00002700
#define GP_ACTIVEWIN	0x00002800
#define GP_ARROW11	0x00002900
#define GP_ARROW12	0x00002a00
#define GP_STRING5	0x00002b00
#define GP_HELP		0x00005000

#define GA_GADNUM(x)	(x)

#define ID_QUIT		MO_EXIT

/*
** Application module
*/
#define ID_MCP_ACTIVATE	(MO_APPLICATION | WI_WINDOW0 | GP_ACTIVEWIN)
#define ID_UM_BUTTON(x)	(MO_APPLICATION | WI_WINDOW1 | GP_BUTTONS1 | GA_GADNUM(x))
#define ID_LOG		(MO_APPLICATION | WI_WINDOW2 | GP_BUTTONS1 | GA_GADNUM(0))
#define ID_LOG_HIDE	(MO_APPLICATION | WI_WINDOW2 | GP_BUTTONS1 | GA_GADNUM(1))
#define ID_LOG_CLEAR	(MO_APPLICATION | WI_WINDOW2 | GP_BUTTONS1 | GA_GADNUM(0))
#define ID_INFO		(MO_APPLICATION | WI_WINDOW2 | GP_BUTTONS2 | GA_GADNUM(0))
#define ID_INFO_ACTIVATE \
			(MO_APPLICATION | WI_WINDOW2 | GP_BUTTONS2 | GA_GADNUM(1))
#define ID_INFO_FLUSH	(MO_APPLICATION | WI_WINDOW2 | GP_BUTTONS2 | GA_GADNUM(2))
#define ID_VERSION	(MO_APPLICATION | WI_WINDOW2 | GP_BUTTONS2 | GA_GADNUM(3))
#define ID_CREDITS	(MO_APPLICATION | WI_WINDOW2 | GP_BUTTONS2 | GA_GADNUM(4))
#define ID_SCREENSAVE	(MO_APPLICATION | WI_WINDOW2 | GP_BUTTONS2 | GA_GADNUM(5))
#define ID_ICONIFY	(MO_APPLICATION | WI_WINDOW2 | GP_BUTTONS2 | GA_GADNUM(6))
#define ID_PREFS	(MO_APPLICATION | WI_WINDOW2 | GP_BUTTONS2 | GA_GADNUM(7))
#define ID_SCREENPREFS	(MO_APPLICATION | WI_WINDOW2 | GP_BUTTONS2 | GA_GADNUM(8))
#define ID_LOADPREFS	(MO_APPLICATION | WI_WINDOW2 | GP_BUTTONS2 | GA_GADNUM(9))
#define ID_SAVEPREFS	(MO_APPLICATION | WI_WINDOW2 | GP_BUTTONS2 | GA_GADNUM(10))

#define ID_LOADPROJ	(MO_APPLICATION | WI_WINDOW2 | GP_BUTTONS2 | GA_GADNUM(11))
#define ID_SAVEPROJ	(MO_APPLICATION | WI_WINDOW2 | GP_BUTTONS2 | GA_GADNUM(12))
#define ID_SAVEPROJNEW	(MO_APPLICATION | WI_WINDOW2 | GP_BUTTONS2 | GA_GADNUM(13))
#define ID_SCRNRESET	(MO_APPLICATION | WI_WINDOW2 | GP_BUTTONS2 | GA_GADNUM(14))
#define ID_MUI_SETTINGS (MO_APPLICATION | WI_WINDOW2 | GP_BUTTONS2 | GA_GADNUM(15))  // ALEXANDER 11.Oct 24 "Menu MUI-Settingsg..."

#ifdef UNDER_CONST
#define ID_UNDERCONST	(MO_APPLICATION | WI_WINDOW20 | GP_BUTTONS1 | GA_GADNUM(1))
#endif /* UNDER_CONST */

/* BusyWindow */
#define ID_BW_CLOSE	(MO_APPLICATION	| WI_WINDOW0 | GP_BUTTONS1 | GA_GADNUM(0))

/* ScreenMode requester */
#define ID_SM_LIST	(MO_APPLICATION	| WI_WINDOW3 | GP_BUTTONS1 | GA_GADNUM(0))
#define ID_SM_OSCAN	(MO_APPLICATION	| WI_WINDOW3 | GP_BUTTONS1 | GA_GADNUM(1))
#define ID_SM_HEIGHT	(MO_APPLICATION	| WI_WINDOW3 | GP_BUTTONS1 | GA_GADNUM(2))
#define ID_SM_WIDTH	(MO_APPLICATION	| WI_WINDOW3 | GP_BUTTONS1 | GA_GADNUM(3))
#define ID_SM_SAVE	(MO_APPLICATION	| WI_WINDOW3 | GP_BUTTONS1 | GA_GADNUM(4))
#define ID_SM_USE	(MO_APPLICATION	| WI_WINDOW3 | GP_BUTTONS1 | GA_GADNUM(5))
#define ID_SM_EXIT	(MO_APPLICATION	| WI_WINDOW3 | GP_BUTTONS1 | GA_GADNUM(6))
#define ID_SM_COLORS (MO_APPLICATION	| WI_WINDOW3 | GP_BUTTONS1 | GA_GADNUM(7))

/* String Input */
#define ID_IS_OK	(MO_APPLICATION	| WI_WINDOW4 | GP_BUTTONS1 | GA_GADNUM(0))
#define ID_IS_CANCEL	(MO_APPLICATION	| WI_WINDOW4 | GP_BUTTONS1 | GA_GADNUM(1))

/* Help Message */
#define ID_HM_CLOSE	(MO_APPLICATION | WI_WINDOW5 | GP_BUTTONS1 | GA_GADNUM(0))

/* Project Editor */
#define ID_PJ_WINDOW	(MO_APPLICATION | WI_WINDOW6)
#define ID_PJ_ACTIVATE	(MO_APPLICATION | WI_WINDOW6 | GP_ACTIVEWIN)
#define ID_PJ_CLOSEQUERY \
			(MO_APPLICATION | WI_WINDOW6 | GP_BUTTONS1 | GA_GADNUM(0))
#define ID_PJ_CLOSE	(MO_APPLICATION | WI_WINDOW6 | GP_BUTTONS1 | GA_GADNUM(1))
#define ID_PJ_APPLY	(MO_APPLICATION | WI_WINDOW6 | GP_BUTTONS1 | GA_GADNUM(2))
#define ID_PJ_GET(x)	(MO_APPLICATION | WI_WINDOW6 | GP_BUTTONS2 | GA_GADNUM(x))
#define ID_PJ_STRING(x)	(MO_APPLICATION | WI_WINDOW6 | GP_STRING1  | GA_GADNUM(x))

/* New Project */
#define ID_PN_WINDOW	(MO_APPLICATION | WI_WINDOW8)
#define ID_PN_ACTIVATE	(MO_APPLICATION | WI_WINDOW8 | GP_ACTIVEWIN)
#define ID_PN_CLOSEQUERY \
			(MO_APPLICATION | WI_WINDOW8 | GP_BUTTONS1 | GA_GADNUM(0))
#define ID_PN_CLOSE	(MO_APPLICATION | WI_WINDOW8 | GP_BUTTONS1 | GA_GADNUM(1))
#define ID_PN_SAVE	(MO_APPLICATION | WI_WINDOW8 | GP_BUTTONS1 | GA_GADNUM(2))
#define ID_PN_GET(x)	(MO_APPLICATION | WI_WINDOW8 | GP_BUTTONS2 | GA_GADNUM(x))

/* Preferences Editor */
#define ID_PR_WINDOW	(MO_APPLICATION | WI_WINDOW7)
#define ID_PR_ACTIVATE	(MO_APPLICATION | WI_WINDOW7 | GP_ACTIVEWIN)
#define ID_PR_CLOSE	(MO_APPLICATION | WI_WINDOW7 | GP_BUTTONS1 | GA_GADNUM(1))
#define ID_PR_LOPRI	(MO_APPLICATION | WI_WINDOW7 | GP_BUTTONS1 | GA_GADNUM(2))
#define ID_PR_NORPRI	(MO_APPLICATION | WI_WINDOW7 | GP_BUTTONS1 | GA_GADNUM(3))
#define ID_PR_HIPRI	(MO_APPLICATION | WI_WINDOW7 | GP_BUTTONS1 | GA_GADNUM(4))
#define ID_PR_SAVEASC	(MO_APPLICATION | WI_WINDOW7 | GP_BUTTONS1 | GA_GADNUM(5))
#define ID_PR_SAVEBIN	(MO_APPLICATION | WI_WINDOW7 | GP_BUTTONS1 | GA_GADNUM(6))
#define ID_PR_RNDRQTR	(MO_APPLICATION | WI_WINDOW7 | GP_BUTTONS1 | GA_GADNUM(7))
#define ID_PR_RNDRHLF	(MO_APPLICATION | WI_WINDOW7 | GP_BUTTONS1 | GA_GADNUM(8))
#define ID_PR_RNDRFUL	(MO_APPLICATION | WI_WINDOW7 | GP_BUTTONS1 | GA_GADNUM(9))
#define ID_PR_REPTERR(x) \
			(MO_APPLICATION | WI_WINDOW7 | GP_BUTTONS2 | GA_GADNUM(x))

/* 
**Editing Module
*/
#define ID_EM_WINDOW	(MO_EDITING | WI_WINDOW1)	/* edit motion */
#define ID_EC_WINDOW	(MO_EDITING | WI_WINDOW2)	/* edit colors */
#define ID_EE_WINDOW	(MO_EDITING | WI_WINDOW3)	/* edit ecosystems */
#define ID_ES_WINDOW	(MO_EDITING | WI_WINDOW4)	/* edit settings */
#define ID_PS_WINDOW	(MO_EDITING | WI_WINDOW12)	/* scale keys */
#define ID_LW_WINDOW	(MO_EDITING | WI_WINDOW13)
#define ID_FM_WINDOW	(MO_EDITING | WI_WINDOW14)
#define ID_AN_WINDOW	(MO_EDITING | WI_WINDOW15)
#define ID_EL_WINDOW	(MO_EDITING | WI_WINDOW16)
#define ID_SC_WINDOW	(MO_EDITING | WI_WINDOW17)
#define ID_TS_WINDOW	(MO_EDITING | WI_WINDOW18)
#define ID_EP_ACTIVATE	(MO_EDITING | WI_WINDOW0 | GP_ACTIVEWIN)
#define ID_EP_QUIT	(MO_EDITING | WI_WINDOW0 | GP_BUTTONS1 | GA_GADNUM(0))
#define ID_EP_SAVE	(MO_EDITING | WI_WINDOW0 | GP_BUTTONS1 | GA_GADNUM(1))
#define ID_EP_LOAD	(MO_EDITING | WI_WINDOW0 | GP_BUTTONS1 | GA_GADNUM(2))
#define ID_EP_FIX	(MO_EDITING | WI_WINDOW0 | GP_BUTTONS1 | GA_GADNUM(3))
#define ID_EP_UNDO	(MO_EDITING | WI_WINDOW0 | GP_BUTTONS1 | GA_GADNUM(4))
#define ID_EP_RESTORE	(MO_EDITING | WI_WINDOW0 | GP_BUTTONS1 | GA_GADNUM(5))
#define ID_EP_DEFAULTS	(MO_EDITING | WI_WINDOW0 | GP_BUTTONS1 | GA_GADNUM(6))
#define ID_EP_EXPORTMO	(MO_EDITING | WI_WINDOW0 | GP_BUTTONS1 | GA_GADNUM(7))
#define ID_EP_LAYOUT	(MO_EDITING | WI_WINDOW0 | GP_CYCLE1   | GA_GADNUM(1))

/* Color Editing */
#define ID_ECTL_WINDOW	(MO_EDITING | WI_WINDOW6)
#define ID_EC_ACTIVATE	(MO_EDITING | WI_WINDOW2 | GP_ACTIVEWIN)
#define ID_EC_CLOSE	(MO_EDITING | WI_WINDOW2 | GP_BUTTONS1 | GA_GADNUM(0))
#define ID_EC_CLOSEQUERY \
			(MO_EDITING | WI_WINDOW2 | GP_BUTTONS1 | GA_GADNUM(50))
#define ID_EC_APPLY	(MO_EDITING | WI_WINDOW2 | GP_BUTTONS1 | GA_GADNUM(1))
#define ID_EC_MAKEKEY	(MO_EDITING | WI_WINDOW2 | GP_BUTTONS1 | GA_GADNUM(2))
#define ID_EC_UPDATEKEYS \
			(MO_EDITING | WI_WINDOW2 | GP_BUTTONS1 | GA_GADNUM(3))
#define ID_EC_NEXTKEY	(MO_EDITING | WI_WINDOW2 | GP_BUTTONS1 | GA_GADNUM(4))
#define ID_EC_PREVKEY	(MO_EDITING | WI_WINDOW2 | GP_BUTTONS1 | GA_GADNUM(5))
#define ID_EC_DELETEKEY	(MO_EDITING | WI_WINDOW2 | GP_BUTTONS1 | GA_GADNUM(6))
#define ID_EC_COPY	(MO_EDITING | WI_WINDOW2 | GP_BUTTONS1 | GA_GADNUM(7))
#define ID_EC_SWAP	(MO_EDITING | WI_WINDOW2 | GP_BUTTONS1 | GA_GADNUM(8))
#define ID_EC_INSERT	(MO_EDITING | WI_WINDOW2 | GP_BUTTONS1 | GA_GADNUM(9))
#define ID_EC_REMOVE	(MO_EDITING | WI_WINDOW2 | GP_BUTTONS1 | GA_GADNUM(10))
#define ID_EC_SAVEALL	(MO_EDITING | WI_WINDOW2 | GP_BUTTONS1 | GA_GADNUM(11))
#define ID_EC_SAVECURRENT \
			(MO_EDITING | WI_WINDOW2 | GP_BUTTONS1 | GA_GADNUM(12))
#define ID_EC_LOADALL	(MO_EDITING | WI_WINDOW2 | GP_BUTTONS1 | GA_GADNUM(13))
#define ID_EC_LOADCURRENT \
			(MO_EDITING | WI_WINDOW2 | GP_BUTTONS1 | GA_GADNUM(14))
#define ID_EC_FIX	(MO_EDITING | WI_WINDOW2 | GP_BUTTONS1 | GA_GADNUM(15))
#define ID_EC_UNDO	(MO_EDITING | WI_WINDOW2 | GP_BUTTONS1 | GA_GADNUM(16))
#define ID_EC_RESTORE	(MO_EDITING | WI_WINDOW2 | GP_BUTTONS1 | GA_GADNUM(17))
#define ID_EC_KEYSCALE	(MO_EDITING | WI_WINDOW2 | GP_BUTTONS1 | GA_GADNUM(18))
#define ID_EC_DELETEALL	(MO_EDITING | WI_WINDOW2 | GP_BUTTONS1 | GA_GADNUM(19))
#define ID_EC_LIST	(MO_EDITING | WI_WINDOW2 | GP_LIST1    | GA_GADNUM(0))
#define ID_EC_NAMESTR	(MO_EDITING | WI_WINDOW2 | GP_STRING1  | GA_GADNUM(0))
#define ID_EC_FRAMESTR(x) \
			(MO_EDITING | WI_WINDOW2 | GP_STRING2  | GA_GADNUM(x))
#define ID_EC_SARROWLEFT(x) \
			(MO_EDITING | WI_WINDOW2 | GP_ARROW1   | GA_GADNUM(x))
#define ID_EC_SARROWRIGHT(x) \
			(MO_EDITING | WI_WINDOW2 | GP_ARROW2   | GA_GADNUM(x))
#define ID_EC_PARROWLEFT(x) \
			(MO_EDITING | WI_WINDOW2 | GP_ARROW3   | GA_GADNUM(x))
#define ID_EC_PARROWRIGHT(x) \
			(MO_EDITING | WI_WINDOW2 | GP_ARROW4   | GA_GADNUM(x))
#define ID_EC_PROP(x)	(MO_EDITING | WI_WINDOW2 | GP_PROP1    | GA_GADNUM(x))
#define ID_EC_COLBT0(x)	(MO_EDITING | WI_WINDOW2 | GP_BUTTONS2 | GA_GADNUM(x))
#define ID_EC_COLBT1(x)	(MO_EDITING | WI_WINDOW2 | GP_BUTTONS3 | GA_GADNUM(x))
#define ID_EC_COLORSTR(x) \
			(MO_EDITING | WI_WINDOW2 | GP_STRING4  | GA_GADNUM(x))

/* Color Time Lines */
#define ID_ECTL_ACTIVATE \
			(MO_EDITING | WI_WINDOW6 | GP_ACTIVEWIN)
#define ID_ECTL_CLOSE	(MO_EDITING | WI_WINDOW6 | GP_BUTTONS1 | GA_GADNUM(0))
#define ID_ECTL_CLOSEQUERY \
			(MO_EDITING | WI_WINDOW6 | GP_BUTTONS1 | GA_GADNUM(50))
#define ID_ECTL_APPLY	(MO_EDITING | WI_WINDOW6 | GP_BUTTONS1 | GA_GADNUM(1))
#define ID_ECTL_ADDKEY	(MO_EDITING | WI_WINDOW6 | GP_BUTTONS1 | GA_GADNUM(2))
#define ID_ECTL_TIMELINEOBJ \
			(MO_EDITING | WI_WINDOW6 | GP_BUTTONS1 | GA_GADNUM(3))
#define ID_ECTL_PLAY	(MO_EDITING | WI_WINDOW6 | GP_BUTTONS1 | GA_GADNUM(4))
#define ID_ECTL_GRID	(MO_EDITING | WI_WINDOW6 | GP_BUTTONS1 | GA_GADNUM(5))
#define ID_ECTL_LINEAR	(MO_EDITING | WI_WINDOW6 | GP_BUTTONS1 | GA_GADNUM(6))
#define ID_ECTL_STRARROWLEFT \
			(MO_EDITING | WI_WINDOW6 | GP_ARROW1   | GA_GADNUM(0))
#define ID_ECTL_STRARROWRIGHT \
			(MO_EDITING | WI_WINDOW6 | GP_ARROW2   | GA_GADNUM(0))
#define ID_ECTL_TXTARROWLEFT \
			(MO_EDITING | WI_WINDOW6 | GP_ARROW3   | GA_GADNUM(0))
#define ID_ECTL_TXTARROWRIGHT \
			(MO_EDITING | WI_WINDOW6 | GP_ARROW4   | GA_GADNUM(0))
#define ID_ECTL_TXTARROWLGLEFT \
			(MO_EDITING | WI_WINDOW6 | GP_ARROW9   | GA_GADNUM(0))
#define ID_ECTL_TXTARROWLGRIGHT \
			(MO_EDITING | WI_WINDOW6 | GP_ARROW10  | GA_GADNUM(0))
#define ID_ECTL_PANPROP	(MO_EDITING | WI_WINDOW6 | GP_PROP1    | GA_GADNUM(0))
#define ID_ECTL_FRAMEPROP \
			(MO_EDITING | WI_WINDOW6 | GP_PROP2    | GA_GADNUM(0))
#define ID_ECTL_CYCLESTR \
			(MO_EDITING | WI_WINDOW6 | GP_STRING1  | GA_GADNUM(0))
#define ID_ECTL_VALSTR(x) \
			(MO_EDITING | WI_WINDOW6 | GP_STRING2  | GA_GADNUM(x))
#define ID_ECTL_CYCLE	(MO_EDITING | WI_WINDOW6 | GP_CYCLE1   | GA_GADNUM(0))
#define ID_ECTL_PARCYCLE \
			(MO_EDITING | WI_WINDOW6 | GP_CYCLE2   | GA_GADNUM(0))

/* Motion Editing */
#define ID_EMTL_WINDOW	(MO_EDITING | WI_WINDOW7)
#define ID_EMPL_WINDOW	(MO_EDITING | WI_WINDOW11)
#define ID_EM_ACTIVATE	(MO_EDITING | WI_WINDOW1 | GP_ACTIVEWIN)
#define ID_EM_CLOSE	(MO_EDITING | WI_WINDOW1 | GP_BUTTONS1 | GA_GADNUM(0))
#define ID_EM_CLOSEQUERY \
			(MO_EDITING | WI_WINDOW1 | GP_BUTTONS1 | GA_GADNUM(50))
#define ID_EM_APPLY	(MO_EDITING | WI_WINDOW1 | GP_BUTTONS1 | GA_GADNUM(1))
#define ID_EM_MAKEKEY	(MO_EDITING | WI_WINDOW1 | GP_BUTTONS1 | GA_GADNUM(2))
#define ID_EM_UPDATEKEYS \
			(MO_EDITING | WI_WINDOW1 | GP_BUTTONS1 | GA_GADNUM(3))
#define ID_EM_NEXTKEY	(MO_EDITING | WI_WINDOW1 | GP_BUTTONS1 | GA_GADNUM(4))
#define ID_EM_PREVKEY	(MO_EDITING | WI_WINDOW1 | GP_BUTTONS1 | GA_GADNUM(5))
#define ID_EM_DELETEKEY	(MO_EDITING | WI_WINDOW1 | GP_BUTTONS1 | GA_GADNUM(6))
#define ID_EM_WINSIZE	(MO_EDITING | WI_WINDOW1 | GP_BUTTONS1 | GA_GADNUM(7))
#define ID_EM_HIDE	(MO_EDITING | WI_WINDOW1 | GP_BUTTONS1 | GA_GADNUM(8))
#define ID_EM_UNHIDE	(MO_EDITING | WI_WINDOW1 | GP_BUTTONS1 | GA_GADNUM(9))
#define ID_EM_AUTOCENTER \
			(MO_EDITING | WI_WINDOW1 | GP_BUTTONS1 | GA_GADNUM(10))
#define ID_EM_INTERACTIVE \
			(MO_EDITING | WI_WINDOW1 | GP_BUTTONS1 | GA_GADNUM(11))

#define ID_EM_SAVEALL	(MO_EDITING | WI_WINDOW1 | GP_BUTTONS1 | GA_GADNUM(12))
#define ID_EM_SAVECURRENT \
			(MO_EDITING | WI_WINDOW1 | GP_BUTTONS1 | GA_GADNUM(13))
#define ID_EM_LOADALL	(MO_EDITING | WI_WINDOW1 | GP_BUTTONS1 | GA_GADNUM(14))
#define ID_EM_LOADCURRENT \
			(MO_EDITING | WI_WINDOW1 | GP_BUTTONS1 | GA_GADNUM(15))
#define ID_EM_FIX	(MO_EDITING | WI_WINDOW1 | GP_BUTTONS1 | GA_GADNUM(16))
#define ID_EM_UNDO	(MO_EDITING | WI_WINDOW1 | GP_BUTTONS1 | GA_GADNUM(17))
#define ID_EM_RESTORE	(MO_EDITING | WI_WINDOW1 | GP_BUTTONS1 | GA_GADNUM(18))
#define ID_EM_BANKKEYS	(MO_EDITING | WI_WINDOW1 | GP_BUTTONS1 | GA_GADNUM(19))
#define ID_EM_KEYSCALE	(MO_EDITING | WI_WINDOW1 | GP_BUTTONS1 | GA_GADNUM(20))
#define ID_EM_DELETEALL	(MO_EDITING | WI_WINDOW1 | GP_BUTTONS1 | GA_GADNUM(21))
#define ID_EM_SENS(x)	(MO_EDITING | WI_WINDOW1 | GP_BUTTONS2 | GA_GADNUM(x))
#define ID_EM_LIST	(MO_EDITING | WI_WINDOW1 | GP_LIST1    | GA_GADNUM(0))
#define ID_EM_SARROWLEFT(x) \
			(MO_EDITING | WI_WINDOW1 | GP_ARROW1   | GA_GADNUM(x))
#define ID_EM_SARROWRIGHT(x) \
			(MO_EDITING | WI_WINDOW1 | GP_ARROW2   | GA_GADNUM(x))
#define ID_EM_IAARROWLEFT(x) \
			(MO_EDITING | WI_WINDOW1 | GP_ARROW3   | GA_GADNUM(x))
#define ID_EM_IAARROWRIGHT(x) \
			(MO_EDITING | WI_WINDOW1 | GP_ARROW4   | GA_GADNUM(x))
#define ID_EM_VALSTR(x)	(MO_EDITING | WI_WINDOW1 | GP_STRING1  | GA_GADNUM(x))
#define ID_EM_FRAMESTR(x) \
			(MO_EDITING | WI_WINDOW1 | GP_STRING3  | GA_GADNUM(x))
#define ID_EM_SENSSTR	(MO_EDITING | WI_WINDOW1 | GP_STRING2  | GA_GADNUM(0))
#define ID_EM_SENSLARROW \
			(MO_EDITING | WI_WINDOW1 | GP_ARROW5   | GA_GADNUM(0))
#define ID_EM_SENSRARROW \
			(MO_EDITING | WI_WINDOW1 | GP_ARROW6  | GA_GADNUM(0))

/* Interactive Motion */
#define ID_EMIA_WINDOW	(MO_EDITING | WI_WINDOW8)
#define ID_EMIA_ACTIVATE \
			(MO_EDITING | WI_WINDOW8 | GP_ACTIVEWIN)
#define ID_EMIA_CLOSE	(MO_EDITING | WI_WINDOW8 | GP_BUTTONS1 | GA_GADNUM(0))
#define ID_EMIA_CLOSEQUERY \
			(MO_EDITING | WI_WINDOW8 | GP_BUTTONS1 | GA_GADNUM(50))
#define ID_EMIA_APPLY	(MO_EDITING | WI_WINDOW8 | GP_BUTTONS1 | GA_GADNUM(1))
#define ID_EMIA_GRID	(MO_EDITING | WI_WINDOW8 | GP_BUTTONS1 | GA_GADNUM(2))
#define ID_EMIA_ELSHADE	(MO_EDITING | WI_WINDOW8 | GP_BUTTONS1 | GA_GADNUM(3))
#define ID_EMIA_SUNSHADE \
			(MO_EDITING | WI_WINDOW8 | GP_BUTTONS1 | GA_GADNUM(4))
#define ID_EMIA_ECORENDER \
			(MO_EDITING | WI_WINDOW8 | GP_BUTTONS1 | GA_GADNUM(5))
#define ID_EMIA_DIAGRENDER \
			(MO_EDITING | WI_WINDOW8 | GP_BUTTONS1 | GA_GADNUM(6))
#define ID_EMIA_VECTOR	(MO_EDITING | WI_WINDOW8 | GP_BUTTONS1 | GA_GADNUM(7))
#define ID_EMIA_ANIM	(MO_EDITING | WI_WINDOW8 | GP_BUTTONS1 | GA_GADNUM(8))
#define ID_EMIA_COMPASSBDS \
			(MO_EDITING | WI_WINDOW8 | GP_BUTTONS1 | GA_GADNUM(9))
#define ID_EMIA_LANDBDS	(MO_EDITING | WI_WINDOW8 | GP_BUTTONS1 | GA_GADNUM(10))
#define ID_EMIA_PROFILEBDS \
			(MO_EDITING | WI_WINDOW8 | GP_BUTTONS1 | GA_GADNUM(11))
#define ID_EMIA_BOXBDS	(MO_EDITING | WI_WINDOW8 | GP_BUTTONS1 | GA_GADNUM(12))
#define ID_EMIA_GRIDBDS	(MO_EDITING | WI_WINDOW8 | GP_BUTTONS1 | GA_GADNUM(13))
#define ID_EMIA_SHOWLAT	(MO_EDITING | WI_WINDOW8 | GP_BUTTONS1 | GA_GADNUM(14))
#define ID_EMIA_SHOWLON	(MO_EDITING | WI_WINDOW8 | GP_BUTTONS1 | GA_GADNUM(15))
#define ID_EMIA_MOVEX	(MO_EDITING | WI_WINDOW8 | GP_BUTTONS1 | GA_GADNUM(16))
#define ID_EMIA_MOVEY	(MO_EDITING | WI_WINDOW8 | GP_BUTTONS1 | GA_GADNUM(17))
#define ID_EMIA_MOVEZ	(MO_EDITING | WI_WINDOW8 | GP_BUTTONS1 | GA_GADNUM(18))
#define ID_EMIA_ASPECT	(MO_EDITING | WI_WINDOW8 | GP_BUTTONS1 | GA_GADNUM(19))
#define ID_EMIA_AUTODRAW \
			(MO_EDITING | WI_WINDOW8 | GP_BUTTONS1 | GA_GADNUM(20))
#define ID_EMIA_GBDENS(x) \
			(MO_EDITING | WI_WINDOW8 | GP_BUTTONS2 | GA_GADNUM(x))
#define ID_EMIA_MOVECY	(MO_EDITING | WI_WINDOW8 | GP_CYCLE1   | GA_GADNUM(0))
#define ID_EMIA_GRIDCY	(MO_EDITING | WI_WINDOW8 | GP_CYCLE2   | GA_GADNUM(0))
#define ID_EMIA_VIEWCY	(MO_EDITING | WI_WINDOW8 | GP_CYCLE3   | GA_GADNUM(0))
#define ID_EMIA_SARROWLEFT(x) \
			(MO_EDITING | WI_WINDOW8 | GP_ARROW1   | GA_GADNUM(x))
#define ID_EMIA_SARROWRIGHT(x) \
			(MO_EDITING | WI_WINDOW8 | GP_ARROW2   | GA_GADNUM(x))
#define ID_EMIA_STRING(x) \
			(MO_EDITING | WI_WINDOW8 | GP_STRING1  | GA_GADNUM(x))

/* Motion Time Lines */
#define ID_EMTL_ACTIVATE \
			(MO_EDITING | WI_WINDOW7 | GP_ACTIVEWIN)
#define ID_EMTL_CLOSE	(MO_EDITING | WI_WINDOW7 | GP_BUTTONS1 | GA_GADNUM(0))
#define ID_EMTL_CLOSEQUERY \
			(MO_EDITING | WI_WINDOW7 | GP_BUTTONS1 | GA_GADNUM(50))
#define ID_EMTL_APPLY	(MO_EDITING | WI_WINDOW7 | GP_BUTTONS1 | GA_GADNUM(1))
#define ID_EMTL_ADDKEY	(MO_EDITING | WI_WINDOW7 | GP_BUTTONS1 | GA_GADNUM(2))
#define ID_EMTL_TIMELINEOBJ \
			(MO_EDITING | WI_WINDOW7 | GP_BUTTONS1 | GA_GADNUM(3))
#define ID_EMTL_PLAY	(MO_EDITING | WI_WINDOW7 | GP_BUTTONS1 | GA_GADNUM(4))
#define ID_EMTL_GRID	(MO_EDITING | WI_WINDOW7 | GP_BUTTONS1 | GA_GADNUM(5))
#define ID_EMTL_LINEAR	(MO_EDITING | WI_WINDOW7 | GP_BUTTONS1 | GA_GADNUM(6))
#define ID_EMTL_STRARROWLEFT \
			(MO_EDITING | WI_WINDOW7 | GP_ARROW1   | GA_GADNUM(0))
#define ID_EMTL_STRARROWRIGHT \
			(MO_EDITING | WI_WINDOW7 | GP_ARROW2   | GA_GADNUM(0))
#define ID_EMTL_TXTARROWLEFT \
			(MO_EDITING | WI_WINDOW7 | GP_ARROW3   | GA_GADNUM(0))
#define ID_EMTL_TXTARROWRIGHT \
			(MO_EDITING | WI_WINDOW7 | GP_ARROW4   | GA_GADNUM(0))
#define ID_EMTL_TXTARROWLGLEFT \
			(MO_EDITING | WI_WINDOW7 | GP_ARROW9   | GA_GADNUM(0))
#define ID_EMTL_TXTARROWLGRIGHT \
			(MO_EDITING | WI_WINDOW7 | GP_ARROW10  | GA_GADNUM(0))
#define ID_EMTL_PANPROP	(MO_EDITING | WI_WINDOW7 | GP_PROP1    | GA_GADNUM(0))
#define ID_EMTL_FRAMEPROP \
			(MO_EDITING | WI_WINDOW7 | GP_PROP2    | GA_GADNUM(0))
#define ID_EMTL_CYCLESTR \
			(MO_EDITING | WI_WINDOW7 | GP_STRING1  | GA_GADNUM(0))
#define ID_EMTL_VALSTR(x) \
			(MO_EDITING | WI_WINDOW7 | GP_STRING2  | GA_GADNUM(x))
#define ID_EMTL_CYCLE	(MO_EDITING | WI_WINDOW7 | GP_CYCLE1   | GA_GADNUM(0))
#define ID_EMTL_PARCYCLE \
			(MO_EDITING | WI_WINDOW7 | GP_CYCLE2   | GA_GADNUM(0))

/* Motion Parameter List Window */
#define ID_EMPL_ACTIVATE \
			(MO_EDITING | WI_WINDOW11 | GP_ACTIVEWIN)
#define ID_EMPL_CLOSE	(MO_EDITING | WI_WINDOW11 | GP_BUTTONS1 | GA_GADNUM(0))
#define ID_EMPL_LIST	(MO_EDITING | WI_WINDOW11 | GP_LIST1    | GA_GADNUM(0))

/* Diagnostic Window */
#define ID_DIAG_WINDOW	(MO_EDITING | WI_WINDOW10)
#define ID_DIAG_ACTIVATE \
			(MO_EDITING | WI_WINDOW10 | GP_ACTIVEWIN)
#define ID_DIAG_CLOSE	(MO_EDITING | WI_WINDOW10 | GP_BUTTONS1 | GA_GADNUM(0))
#define ID_DIAG_DIGITIZE \
			(MO_EDITING | WI_WINDOW10 | GP_BUTTONS1 | GA_GADNUM(1))

/* Ecosystem Editing */
#define ID_EETL_WINDOW	(MO_EDITING | WI_WINDOW9)
#define ID_EE_ACTIVATE	(MO_EDITING | WI_WINDOW3 | GP_ACTIVEWIN)
#define ID_EE_CLOSE	(MO_EDITING | WI_WINDOW3 | GP_BUTTONS1 | GA_GADNUM(0))
#define ID_EE_CLOSEQUERY \
			(MO_EDITING | WI_WINDOW3 | GP_BUTTONS1 | GA_GADNUM(50))
#define ID_EE_APPLY	(MO_EDITING | WI_WINDOW3 | GP_BUTTONS1 | GA_GADNUM(1))
#define ID_EE_MAKEKEY	(MO_EDITING | WI_WINDOW3 | GP_BUTTONS1 | GA_GADNUM(2))
#define ID_EE_UPDATEKEYS \
			(MO_EDITING | WI_WINDOW3 | GP_BUTTONS1 | GA_GADNUM(3))
#define ID_EE_NEXTKEY	(MO_EDITING | WI_WINDOW3 | GP_BUTTONS1 | GA_GADNUM(4))
#define ID_EE_PREVKEY	(MO_EDITING | WI_WINDOW3 | GP_BUTTONS1 | GA_GADNUM(5))
#define ID_EE_DELETEKEY	(MO_EDITING | WI_WINDOW3 | GP_BUTTONS1 | GA_GADNUM(6))
#define ID_EE_COPY	(MO_EDITING | WI_WINDOW3 | GP_BUTTONS1 | GA_GADNUM(7))
#define ID_EE_SWAP	(MO_EDITING | WI_WINDOW3 | GP_BUTTONS1 | GA_GADNUM(8))
#define ID_EE_INSERT	(MO_EDITING | WI_WINDOW3 | GP_BUTTONS1 | GA_GADNUM(9))
#define ID_EE_REMOVE	(MO_EDITING | WI_WINDOW3 | GP_BUTTONS1 | GA_GADNUM(10))
#define ID_EE_SAVEALL	(MO_EDITING | WI_WINDOW3 | GP_BUTTONS1 | GA_GADNUM(11))
#define ID_EE_SAVECURRENT \
			(MO_EDITING | WI_WINDOW3 | GP_BUTTONS1 | GA_GADNUM(12))
#define ID_EE_LOADALL	(MO_EDITING | WI_WINDOW3 | GP_BUTTONS1 | GA_GADNUM(13))
#define ID_EE_LOADCURRENT \
			(MO_EDITING | WI_WINDOW3 | GP_BUTTONS1 | GA_GADNUM(14))
#define ID_EE_FIX	(MO_EDITING | WI_WINDOW3 | GP_BUTTONS1 | GA_GADNUM(15))
#define ID_EE_UNDO	(MO_EDITING | WI_WINDOW3 | GP_BUTTONS1 | GA_GADNUM(16))
#define ID_EE_RESTORE	(MO_EDITING | WI_WINDOW3 | GP_BUTTONS1 | GA_GADNUM(17))
#define ID_EE_KEYSCALE	(MO_EDITING | WI_WINDOW3 | GP_BUTTONS1 | GA_GADNUM(18))
#define ID_EE_DELETEALL	(MO_EDITING | WI_WINDOW3 | GP_BUTTONS1 | GA_GADNUM(19))
#define ID_EE_SORT	(MO_EDITING | WI_WINDOW3 | GP_BUTTONS1 | GA_GADNUM(20))
/*
#define ID_EE_COLBT(x)	(MO_EDITING | WI_WINDOW3 | GP_BUTTONS2 | GA_GADNUM(x))
#define ID_EE_COLTXT(x) \
			(MO_EDITING | WI_WINDOW3 | GP_BUTTONS3 | GA_GADNUM(x))
#define ID_EE_MAP	(MO_EDITING | WI_WINDOW3 | GP_BUTTONS4 | GA_GADNUM(0))
#define ID_EE_MAPDRAW	(MO_EDITING | WI_WINDOW3 | GP_BUTTONS5 | GA_GADNUM(0))
*/
#define ID_EE_LIST	(MO_EDITING | WI_WINDOW3 | GP_LIST1    | GA_GADNUM(0))
#define ID_EE_NAMESTR	(MO_EDITING | WI_WINDOW3 | GP_STRING1  | GA_GADNUM(0))
#define ID_EE_FRAMESTR(x) \
			(MO_EDITING | WI_WINDOW3 | GP_STRING2  | GA_GADNUM(x))
#define ID_EE_INTSTR(x)	(MO_EDITING | WI_WINDOW3 | GP_STRING3  | GA_GADNUM(x))
#define ID_EE_INTARROWLEFT(x) \
			(MO_EDITING | WI_WINDOW3 | GP_ARROW1   | GA_GADNUM(x))
#define ID_EE_INTARROWRIGHT(x) \
			(MO_EDITING | WI_WINDOW3 | GP_ARROW2   | GA_GADNUM(x))
#define ID_EE_SARROWLEFT \
			(MO_EDITING | WI_WINDOW3 | GP_ARROW3   | GA_GADNUM(0))
#define ID_EE_SARROWRIGHT \
			(MO_EDITING | WI_WINDOW3 | GP_ARROW4   | GA_GADNUM(0))
#define ID_EE_CLASS	(MO_EDITING | WI_WINDOW3 | GP_CYCLE1   | GA_GADNUM(0))
#define ID_EE_COLOR(x)	(MO_EDITING | WI_WINDOW3 | GP_CYCLE2   | GA_GADNUM(x))
#define ID_EE_TEXCLASS	(MO_EDITING | WI_WINDOW3 | GP_CYCLE3   | GA_GADNUM(0))
#define ID_EE_PROP(x)	(MO_EDITING | WI_WINDOW3 | GP_PROP1    | GA_GADNUM(x))
#define ID_EE_MODELSTR	(MO_EDITING | WI_WINDOW3 | GP_STRING5  | GA_GADNUM(0))
#define ID_EE_PROCEDURAL(x) \
			(MO_EDITING | WI_WINDOW3 | GP_BUTTONS2 | GA_GADNUM(x))

/* Ecosystem Time Lines */
#define ID_EETL_ACTIVATE \
			(MO_EDITING | WI_WINDOW9 | GP_ACTIVEWIN)
#define ID_EETL_CLOSE	(MO_EDITING | WI_WINDOW9 | GP_BUTTONS1 | GA_GADNUM(0))
#define ID_EETL_CLOSEQUERY \
			(MO_EDITING | WI_WINDOW9 | GP_BUTTONS1 | GA_GADNUM(50))
#define ID_EETL_APPLY	(MO_EDITING | WI_WINDOW9 | GP_BUTTONS1 | GA_GADNUM(1))
#define ID_EETL_ADDKEY	(MO_EDITING | WI_WINDOW9 | GP_BUTTONS1 | GA_GADNUM(2))
#define ID_EETL_PLAY	(MO_EDITING | WI_WINDOW9 | GP_BUTTONS1 | GA_GADNUM(3))
#define ID_EETL_GRID	(MO_EDITING | WI_WINDOW9 | GP_BUTTONS1 | GA_GADNUM(4))
#define ID_EETL_LINEAR	(MO_EDITING | WI_WINDOW9 | GP_BUTTONS1 | GA_GADNUM(5))
#define ID_EETL_TIMELINEOBJ(x) \
			(MO_EDITING | WI_WINDOW9 | GP_BUTTONS2 | GA_GADNUM(x))
#define ID_EETL_STRARROWLEFT \
			(MO_EDITING | WI_WINDOW9 | GP_ARROW1   | GA_GADNUM(0))
#define ID_EETL_STRARROWRIGHT \
			(MO_EDITING | WI_WINDOW9 | GP_ARROW2   | GA_GADNUM(0))
#define ID_EETL_TXTARROWLEFT \
			(MO_EDITING | WI_WINDOW9 | GP_ARROW3   | GA_GADNUM(0))
#define ID_EETL_TXTARROWRIGHT \
			(MO_EDITING | WI_WINDOW9 | GP_ARROW4   | GA_GADNUM(0))
#define ID_EETL_TXTARROWLGLEFT \
			(MO_EDITING | WI_WINDOW9 | GP_ARROW9   | GA_GADNUM(0))
#define ID_EETL_TXTARROWLGRIGHT \
			(MO_EDITING | WI_WINDOW9 | GP_ARROW10  | GA_GADNUM(0))
#define ID_EETL_PANPROP	(MO_EDITING | WI_WINDOW9 | GP_PROP1    | GA_GADNUM(0))
#define ID_EETL_FRAMEPROP \
			(MO_EDITING | WI_WINDOW9 | GP_PROP2    | GA_GADNUM(0))
#define ID_EETL_CYCLESTR \
			(MO_EDITING | WI_WINDOW9 | GP_STRING1  | GA_GADNUM(0))
#define ID_EETL_VALSTR(x) \
			(MO_EDITING | WI_WINDOW9 | GP_STRING2  | GA_GADNUM(x))
#define ID_EETL_CYCLE	(MO_EDITING | WI_WINDOW9 | GP_CYCLE1   | GA_GADNUM(0))
#define ID_EETL_PARCYCLE \
			(MO_EDITING | WI_WINDOW9 | GP_CYCLE2   | GA_GADNUM(0))
#define ID_EETL_TLGROUP	(MO_EDITING | WI_WINDOW9 | GP_CYCLE3   | GA_GADNUM(0))

/* Generic Time Lines */
#define ID_GNTL_ACTIVATE(y) \
			(MO_TIMELINES | WI_WINDOW(y) | GP_ACTIVEWIN)
#define ID_GNTL_CLOSE(y) \
			(MO_TIMELINES | WI_WINDOW(y) | GP_BUTTONS1 | GA_GADNUM(0))
#define ID_GNTL_CLOSEQUERY(y) \
			(MO_TIMELINES | WI_WINDOW(y) | GP_BUTTONS1 | GA_GADNUM(50))
#define ID_GNTL_APPLY(y) \
			(MO_TIMELINES | WI_WINDOW(y) | GP_BUTTONS1 | GA_GADNUM(1))
#define ID_GNTL_ADDKEY(y) \
			(MO_TIMELINES | WI_WINDOW(y) | GP_BUTTONS1 | GA_GADNUM(2))
#define ID_GNTL_GRID(y)	(MO_TIMELINES | WI_WINDOW(y) | GP_BUTTONS1 | GA_GADNUM(4))
#define ID_GNTL_LINEAR(y) \
			(MO_TIMELINES | WI_WINDOW(y) | GP_BUTTONS1 | GA_GADNUM(5))
#define ID_GNTL_DELETEKEY(y) \
			(MO_TIMELINES | WI_WINDOW(y) | GP_BUTTONS1 | GA_GADNUM(6))
#define ID_GNTL_PREVKEY(y) \
			(MO_TIMELINES | WI_WINDOW(y) | GP_BUTTONS1 | GA_GADNUM(7))
#define ID_GNTL_NEXTKEY(y) \
			(MO_TIMELINES | WI_WINDOW(y) | GP_BUTTONS1 | GA_GADNUM(8))
#define ID_GNTL_TIMELINEOBJ(y, x) \
			(MO_TIMELINES | WI_WINDOW(y) | GP_BUTTONS2 | GA_GADNUM(x))
#define ID_GNTL_STRARROWLEFT(y) \
			(MO_TIMELINES | WI_WINDOW(y) | GP_ARROW1   | GA_GADNUM(0))
#define ID_GNTL_STRARROWRIGHT(y) \
			(MO_TIMELINES | WI_WINDOW(y) | GP_ARROW2   | GA_GADNUM(0))
#define ID_GNTL_TXTARROWLEFT(y) \
			(MO_TIMELINES | WI_WINDOW(y) | GP_ARROW3   | GA_GADNUM(0))
#define ID_GNTL_TXTARROWRIGHT(y) \
			(MO_TIMELINES | WI_WINDOW(y) | GP_ARROW4   | GA_GADNUM(0))
#define ID_GNTL_TXTARROWLGLEFT(y) \
			(MO_TIMELINES | WI_WINDOW(y) | GP_ARROW9   | GA_GADNUM(0))
#define ID_GNTL_TXTARROWLGRIGHT(y) \
			(MO_TIMELINES | WI_WINDOW(y) | GP_ARROW10  | GA_GADNUM(0))
#define ID_GNTL_PANPROP(y) \
			(MO_TIMELINES | WI_WINDOW(y) | GP_PROP1    | GA_GADNUM(0))
#define ID_GNTL_FRAMEPROP(y) \
			(MO_TIMELINES | WI_WINDOW(y) | GP_PROP2    | GA_GADNUM(0))
#define ID_GNTL_CYCLESTR(y) \
			(MO_TIMELINES | WI_WINDOW(y) | GP_STRING1  | GA_GADNUM(0))
#define ID_GNTL_VALSTR(y, x) \
			(MO_TIMELINES | WI_WINDOW(y) | GP_STRING2  | GA_GADNUM(x))
#define ID_GNTL_CYCLE(y) \
			(MO_TIMELINES | WI_WINDOW(y) | GP_CYCLE1   | GA_GADNUM(0))
#define ID_GNTL_PARCYCLE(y) \
			(MO_TIMELINES | WI_WINDOW(y) | GP_CYCLE2   | GA_GADNUM(0))
#define ID_GNTL_TLGROUP(y) \
			(MO_TIMELINES | WI_WINDOW(y) | GP_CYCLE3   | GA_GADNUM(0))

/* Settings */
#define ID_ES_ACTIVATE	(MO_EDITING | WI_WINDOW4 | GP_ACTIVEWIN)
#define ID_ES_CLOSE	(MO_EDITING | WI_WINDOW4 | GP_BUTTONS1 | GA_GADNUM(0))
#define ID_ES_CLOSEQUERY \
			(MO_EDITING | WI_WINDOW4 | GP_BUTTONS1 | GA_GADNUM(50))
#define ID_ES_APPLY	(MO_EDITING | WI_WINDOW4 | GP_BUTTONS1 | GA_GADNUM(1))
#define ID_ES_FIX	(MO_EDITING | WI_WINDOW4 | GP_BUTTONS1 | GA_GADNUM(2))
#define ID_ES_UNDO	(MO_EDITING | WI_WINDOW4 | GP_BUTTONS1 | GA_GADNUM(3))
#define ID_ES_RESTORE	(MO_EDITING | WI_WINDOW4 | GP_BUTTONS1 | GA_GADNUM(4))
#define ID_ES_SAVE	(MO_EDITING | WI_WINDOW4 | GP_BUTTONS1 | GA_GADNUM(5))
#define ID_ES_LOAD	(MO_EDITING | WI_WINDOW4 | GP_BUTTONS1 | GA_GADNUM(6))
#define ID_ES_FRACTALSET \
			(MO_EDITING | WI_WINDOW4 | GP_BUTTONS1 | GA_GADNUM(7))
#define ID_ES_GETPATH(x) \
			(MO_EDITING | WI_WINDOW4 | GP_BUTTONS2 | GA_GADNUM(x))
#define ID_ES_INTSTR(x) \
			(MO_EDITING | WI_WINDOW4 | GP_STRING1  | GA_GADNUM(x))
#define ID_ES_FLOATSTR(x) \
			(MO_EDITING | WI_WINDOW4 | GP_STRING2  | GA_GADNUM(x))
#define ID_ES_PATHSTR(x) \
			(MO_EDITING | WI_WINDOW4 | GP_STRING3  | GA_GADNUM(x))
#define ID_ES_INTSTRARROWLEFT(x) \
			(MO_EDITING | WI_WINDOW4 | GP_ARROW1   | GA_GADNUM(x))
#define ID_ES_INTSTRARROWRIGHT(x) \
			(MO_EDITING | WI_WINDOW4 | GP_ARROW2   | GA_GADNUM(x))
#define ID_ES_FLOATSTRARROWLEFT(x) \
			(MO_EDITING | WI_WINDOW4 | GP_ARROW3   | GA_GADNUM(x))
#define ID_ES_FLOATSTRARROWRIGHT(x) \
			(MO_EDITING | WI_WINDOW4 | GP_ARROW4   | GA_GADNUM(x))
#define ID_ES_TEXTARROWLEFT(x) \
			(MO_EDITING | WI_WINDOW4 | GP_ARROW5   | GA_GADNUM(x))
#define ID_ES_TEXTARROWRIGHT(x) \
			(MO_EDITING | WI_WINDOW4 | GP_ARROW6   | GA_GADNUM(x))
#define ID_ES_CYCLE(x)	(MO_EDITING | WI_WINDOW4 | GP_CYCLE1   | GA_GADNUM(x))
#define ID_ES_HELP	(MO_EDITING | WI_WINDOW4 | GP_HELP)

/* Scale Keys */
#define ID_PS_WINGRP0	(MO_EDITING | WI_WINDOW12 | GP_OPEN_WINDOW | GA_GADNUM(0))
#define ID_PS_WINGRP1	(MO_EDITING | WI_WINDOW12 | GP_OPEN_WINDOW | GA_GADNUM(1))
#define ID_PS_WINGRP2	(MO_EDITING | WI_WINDOW12 | GP_OPEN_WINDOW | GA_GADNUM(2))
#define ID_PS_ACTIVATE	(MO_EDITING | WI_WINDOW12 | GP_ACTIVEWIN)
#define ID_PS_CLOSE	(MO_EDITING | WI_WINDOW12 | GP_BUTTONS1 | GA_GADNUM(0))
#define ID_PS_CLOSEQUERY \
			(MO_EDITING | WI_WINDOW12 | GP_BUTTONS1 | GA_GADNUM(50))
#define ID_PS_APPLY	(MO_EDITING | WI_WINDOW12 | GP_BUTTONS1 | GA_GADNUM(1))
#define ID_PS_OPERATE	(MO_EDITING | WI_WINDOW12 | GP_BUTTONS1 | GA_GADNUM(2))

/* LightWave I/O */
#define ID_LW_ACTIVATE	(MO_EDITING | WI_WINDOW13 | GP_ACTIVEWIN)
#define ID_LW_CLOSE	(MO_EDITING | WI_WINDOW13 | GP_BUTTONS1 | GA_GADNUM(0))
#define ID_LW_EXPORT	(MO_EDITING | WI_WINDOW13 | GP_BUTTONS1 | GA_GADNUM(2))

/* Ecosystem Model */
#define ID_FM_ACTIVATE	(MO_EDITING | WI_WINDOW14 | GP_ACTIVEWIN)
#define ID_FM_CLOSEQUERY \
			(MO_EDITING | WI_WINDOW14 | GP_BUTTONS1 | GA_GADNUM(0))
#define ID_FM_ADD	(MO_EDITING | WI_WINDOW14 | GP_BUTTONS1 | GA_GADNUM(1))
#define ID_FM_REMOVE	(MO_EDITING | WI_WINDOW14 | GP_BUTTONS1 | GA_GADNUM(2))
#define ID_FM_LOAD	(MO_EDITING | WI_WINDOW14 | GP_BUTTONS1 | GA_GADNUM(3))
#define ID_FM_SAVE	(MO_EDITING | WI_WINDOW14 | GP_BUTTONS1 | GA_GADNUM(4))
#define ID_FM_LIST	(MO_EDITING | WI_WINDOW14 | GP_LIST1    | GA_GADNUM(0))
#define ID_FM_TXTARROWLEFT \
			(MO_EDITING | WI_WINDOW14 | GP_ARROW1   | GA_GADNUM(0))
#define ID_FM_TXTARROWRIGHT \
			(MO_EDITING | WI_WINDOW14 | GP_ARROW2   | GA_GADNUM(0))

/* Anim Control Window */
#define ID_AN_ACTIVATE \
			(MO_EDITING | WI_WINDOW15 | GP_ACTIVEWIN)
#define ID_AN_CLOSE	(MO_EDITING | WI_WINDOW15 | GP_BUTTONS1 | GA_GADNUM(0))
#define ID_AN_RENDER	(MO_EDITING | WI_WINDOW15 | GP_BUTTONS1 | GA_GADNUM(1))
#define ID_AN_SAVE	(MO_EDITING | WI_WINDOW15 | GP_BUTTONS1 | GA_GADNUM(2))
#define ID_AN_GETPATH	(MO_EDITING | WI_WINDOW15 | GP_BUTTONS1 | GA_GADNUM(3))

/* Ecosystem Legend Window */
#define ID_EL_ACTIVATE \
			(MO_EDITING | WI_WINDOW16 | GP_ACTIVEWIN)
#define ID_EL_CLOSE	(MO_EDITING | WI_WINDOW16 | GP_BUTTONS1 | GA_GADNUM(0))
#define ID_EL_COLBUT(x)	(MO_EDITING | WI_WINDOW16 | GP_BUTTONS2 | GA_GADNUM(x))
#define ID_EL_CYCLE(x)	(MO_EDITING | WI_WINDOW16 | GP_CYCLE1   | GA_GADNUM(x))

/* Change Image Scale Window */
#define ID_SC_ACTIVATE \
			(MO_EDITING | WI_WINDOW17 | GP_ACTIVEWIN)
#define ID_SC_CLOSEQUERY \
			(MO_EDITING | WI_WINDOW17 | GP_BUTTONS1 | GA_GADNUM(0))
#define ID_SC_CLOSE	(MO_EDITING | WI_WINDOW17 | GP_BUTTONS1 | GA_GADNUM(1))
#define ID_SC_APPLY	(MO_EDITING | WI_WINDOW17 | GP_BUTTONS1 | GA_GADNUM(2))
#define ID_SC_HALVE	(MO_EDITING | WI_WINDOW17 | GP_BUTTONS1 | GA_GADNUM(3))
#define ID_SC_DOUBLE	(MO_EDITING | WI_WINDOW17 | GP_BUTTONS1 | GA_GADNUM(4))

/* Set Sun Time Window */
#define ID_TS_ACTIVATE \
			(MO_EDITING | WI_WINDOW18 | GP_ACTIVEWIN)
#define ID_TS_CLOSEQUERY \
			(MO_EDITING | WI_WINDOW18 | GP_BUTTONS1 | GA_GADNUM(0))
#define ID_TS_CANCEL	(MO_EDITING | WI_WINDOW18 | GP_BUTTONS1 | GA_GADNUM(1))
#define ID_TS_APPLY	(MO_EDITING | WI_WINDOW18 | GP_BUTTONS1 | GA_GADNUM(2))
#define ID_TS_REVERSE	(MO_EDITING | WI_WINDOW18 | GP_BUTTONS1 | GA_GADNUM(3))
#define ID_TS_MONTHCYCLE \
			(MO_EDITING | WI_WINDOW18 | GP_CYCLE1   | GA_GADNUM(0))
#define ID_TS_DATECYCLE	(MO_EDITING | WI_WINDOW18 | GP_CYCLE1   | GA_GADNUM(1))
#define ID_TS_AMPMCYCLE	(MO_EDITING | WI_WINDOW18 | GP_CYCLE1   | GA_GADNUM(2))
#define ID_TS_REFLONSTR	(MO_EDITING | WI_WINDOW18 | GP_STRING1  | GA_GADNUM(0))
#define ID_TS_TIMESTR	(MO_EDITING | WI_WINDOW18 | GP_STRING1  | GA_GADNUM(1))
#define ID_TS_SUNSTR	(MO_EDITING | WI_WINDOW18 | GP_STRING2  | GA_GADNUM(0))

/* Cloud Editor Window */
#define ID_CL_WINDOW	(MO_EDITING | WI_WINDOW19)	/* cloud editor */
#define ID_CL_ACTIVATE \
			(MO_EDITING | WI_WINDOW19 | GP_ACTIVEWIN)
#define ID_CL_CLOSE	(MO_EDITING | WI_WINDOW19 | GP_BUTTONS1 | GA_GADNUM(0))
#define ID_CL_LOAD	(MO_EDITING | WI_WINDOW19 | GP_BUTTONS1 | GA_GADNUM(1))
#define ID_CL_SAVE	(MO_EDITING | WI_WINDOW19 | GP_BUTTONS1 | GA_GADNUM(2))
#define ID_CL_WAVEADD	(MO_EDITING | WI_WINDOW19 | GP_BUTTONS1 | GA_GADNUM(3))
#define ID_CL_WAVEEDIT	(MO_EDITING | WI_WINDOW19 | GP_BUTTONS1 | GA_GADNUM(4))
#define ID_CL_DRAW	(MO_EDITING | WI_WINDOW19 | GP_BUTTONS1 | GA_GADNUM(5))
#define ID_CL_BOUNDS	(MO_EDITING | WI_WINDOW19 | GP_BUTTONS1 | GA_GADNUM(6))

#define ID_CL_TIMELINES	(MO_EDITING | WI_WINDOW19 | GP_BUTTONS1 | GA_GADNUM(7))
#define ID_CL_DELETEKEY	(MO_EDITING | WI_WINDOW19 | GP_BUTTONS1 | GA_GADNUM(8))
#define ID_CL_SCALEKEYS	(MO_EDITING | WI_WINDOW19 | GP_BUTTONS1 | GA_GADNUM(9))
#define ID_CL_NEXTKEY	(MO_EDITING | WI_WINDOW19 | GP_BUTTONS1 | GA_GADNUM(10))
#define ID_CL_PREVKEY	(MO_EDITING | WI_WINDOW19 | GP_BUTTONS1 | GA_GADNUM(11))
#define ID_CL_UPDATEKEYS \
			(MO_EDITING | WI_WINDOW19 | GP_BUTTONS1 | GA_GADNUM(12))
#define ID_CL_MAKEKEY	(MO_EDITING | WI_WINDOW19 | GP_BUTTONS1 | GA_GADNUM(13))
#define ID_CL_DELKEYS	(MO_EDITING | WI_WINDOW19 | GP_BUTTONS1 | GA_GADNUM(14))

#define ID_CL_CHECK	(MO_EDITING | WI_WINDOW19 | GP_BUTTONS2 | GA_GADNUM(0))
#define ID_CL_FLOATSTR(x) \
			(MO_EDITING | WI_WINDOW19 | GP_STRING1  | GA_GADNUM(x))
#define ID_CL_CLOUDSTR(x) \
			(MO_EDITING | WI_WINDOW19 | GP_STRING2  | GA_GADNUM(x))
#define ID_CL_INTSTR(x) (MO_EDITING | WI_WINDOW19 | GP_STRING3  | GA_GADNUM(x))
#define ID_CL_FRAMESTR	(MO_EDITING | WI_WINDOW19 | GP_STRING4  | GA_GADNUM(0))
#define ID_CL_CYCLE	(MO_EDITING | WI_WINDOW19 | GP_CYCLE1   | GA_GADNUM(0))
#define ID_CL_FLOATARROWLEFT(x) \
			(MO_EDITING | WI_WINDOW19 | GP_ARROW1   | GA_GADNUM(x))
#define ID_CL_FLOATARROWRIGHT(x) \
			(MO_EDITING | WI_WINDOW19 | GP_ARROW2   | GA_GADNUM(x))
#define ID_CL_CLOUDARROWLEFT(x) \
			(MO_EDITING | WI_WINDOW19 | GP_ARROW3   | GA_GADNUM(x))
#define ID_CL_CLOUDARROWRIGHT(x) \
			(MO_EDITING | WI_WINDOW19 | GP_ARROW4   | GA_GADNUM(x))
#define ID_CL_STRARROW(x) \
			(MO_EDITING | WI_WINDOW19 | GP_ARROW5   | GA_GADNUM(x))

/* Settings Editor Pages set by Options Buttons */
#define ID_SB_SETPAGE(x) \
			(MO_EDITING | WI_WINDOW20 | GP_BUTTONS1 | GA_GADNUM(x))

/* Wave Editor Window */
#define ID_WV_WINDOW(y)	(MO_WAVEED | WI_WINDOW(y))	/* wave editor */
#define ID_WV_ACTIVATE(y) \
			(MO_WAVEED | WI_WINDOW(y) | GP_ACTIVEWIN)
#define ID_WV_CLOSE(y)	(MO_WAVEED | WI_WINDOW(y) | GP_BUTTONS1 | GA_GADNUM(0))
#define ID_WV_LOAD(y)	(MO_WAVEED | WI_WINDOW(y) | GP_BUTTONS1 | GA_GADNUM(1))
#define ID_WV_SAVE(y)	(MO_WAVEED | WI_WINDOW(y) | GP_BUTTONS1 | GA_GADNUM(2))
#define ID_WV_ADDWAVE(y) \
			(MO_WAVEED | WI_WINDOW(y) | GP_BUTTONS1 | GA_GADNUM(3))
#define ID_WV_REMOVEWAVE(y) \
			(MO_WAVEED | WI_WINDOW(y) | GP_BUTTONS1 | GA_GADNUM(4))
#define ID_WV_DRAW(y)	(MO_WAVEED | WI_WINDOW(y) | GP_BUTTONS1 | GA_GADNUM(5))
#define ID_WV_MAKEKEY(y) \
			(MO_WAVEED | WI_WINDOW(y) | GP_BUTTONS1 | GA_GADNUM(6))
#define ID_WV_DELKEYS(y) \
			(MO_WAVEED | WI_WINDOW(y) | GP_BUTTONS1 | GA_GADNUM(7))
#define ID_WV_DELETEKEY(y) \
			(MO_WAVEED | WI_WINDOW(y) | GP_BUTTONS1 | GA_GADNUM(8))
#define ID_WV_UPDATEKEYS(y) \
			(MO_WAVEED | WI_WINDOW(y) | GP_BUTTONS1 | GA_GADNUM(9))
#define ID_WV_DRAWDETAIL(y) \
			(MO_WAVEED | WI_WINDOW(y) | GP_BUTTONS1 | GA_GADNUM(10))
#define ID_WV_PREVKEY(y) \
			(MO_WAVEED | WI_WINDOW(y) | GP_BUTTONS1 | GA_GADNUM(11))
#define ID_WV_NEXTKEY(y) \
			(MO_WAVEED | WI_WINDOW(y) | GP_BUTTONS1 | GA_GADNUM(12))
#define ID_WV_SCALEKEYS(y) \
			(MO_WAVEED | WI_WINDOW(y) | GP_BUTTONS1 | GA_GADNUM(13))
#define ID_WV_TIMELINES(y) \
			(MO_WAVEED | WI_WINDOW(y) | GP_BUTTONS1 | GA_GADNUM(14))
#define ID_WV_MAPADDWAVE(y) \
			(MO_WAVEED | WI_WINDOW(y) | GP_BUTTONS1 | GA_GADNUM(15))
#define ID_WV_FLOATSTR(y, x) \
			(MO_WAVEED | WI_WINDOW(y) | GP_STRING1  | GA_GADNUM(x))
#define ID_WV_WAVESTR(y, x) \
			(MO_WAVEED | WI_WINDOW(y) | GP_STRING2  | GA_GADNUM(x))
#define ID_WV_FRAMESTR(y) \
			(MO_WAVEED | WI_WINDOW(y) | GP_STRING3  | GA_GADNUM(0))
#define ID_WV_FLOATARROWLEFT(y, x) \
			(MO_WAVEED | WI_WINDOW(y) | GP_ARROW1   | GA_GADNUM(x))
#define ID_WV_FLOATARROWRIGHT(y, x) \
			(MO_WAVEED | WI_WINDOW(y) | GP_ARROW2   | GA_GADNUM(x))
#define ID_WV_WAVEARROWLEFT(y, x) \
			(MO_WAVEED | WI_WINDOW(y) | GP_ARROW3   | GA_GADNUM(x))
#define ID_WV_WAVEARROWRIGHT(y, x) \
			(MO_WAVEED | WI_WINDOW(y) | GP_ARROW4   | GA_GADNUM(x))
#define ID_WV_STRARROW(y, x) \
			(MO_WAVEED | WI_WINDOW(y) | GP_ARROW5   | GA_GADNUM(x))
#define ID_WV_WAVELIST(y) \
			(MO_WAVEED | WI_WINDOW(y) | GP_LIST1    | GA_GADNUM(0))

/* Foliage Editor Window */
#define ID_FE_WINDOW	(MO_EDITING | WI_WINDOW21)	/* wave editor */
#define ID_FE_ACTIVATE \
			(MO_EDITING | WI_WINDOW21 | GP_ACTIVEWIN)
#define ID_FE_CLOSEQUERY \
			(MO_EDITING | WI_WINDOW21 | GP_BUTTONS1 | GA_GADNUM(0))
#define ID_FE_APPLY	(MO_EDITING | WI_WINDOW21 | GP_BUTTONS1 | GA_GADNUM(1))
#define ID_FE_CLOSE	(MO_EDITING | WI_WINDOW21 | GP_BUTTONS1 | GA_GADNUM(2))
#define ID_FE_SUGGEST	(MO_EDITING | WI_WINDOW21 | GP_BUTTONS1 | GA_GADNUM(3))
#define ID_FE_ADDGROUP	(MO_EDITING | WI_WINDOW21 | GP_BUTTONS1 | GA_GADNUM(4))
#define ID_FE_NEWGROUP	(MO_EDITING | WI_WINDOW21 | GP_BUTTONS1 | GA_GADNUM(5))
#define ID_FE_EXPORT	(MO_EDITING | WI_WINDOW21 | GP_BUTTONS1 | GA_GADNUM(6))
#define ID_FE_ADDIMAGE	(MO_EDITING | WI_WINDOW21 | GP_BUTTONS1 | GA_GADNUM(7))
#define ID_FE_REMOVEIMAGE \
			(MO_EDITING | WI_WINDOW21 | GP_BUTTONS1 | GA_GADNUM(8))
#define ID_FE_VIEWIMAGE	(MO_EDITING | WI_WINDOW21 | GP_BUTTONS1 | GA_GADNUM(9))
#define ID_FE_EXPORTECO	(MO_EDITING | WI_WINDOW21 | GP_BUTTONS1 | GA_GADNUM(10))
#define ID_FE_REMOVEGROUP \
			(MO_EDITING | WI_WINDOW21 | GP_BUTTONS1 | GA_GADNUM(11))
#define ID_FE_IMAGEPATH	(MO_EDITING | WI_WINDOW21 | GP_BUTTONS1 | GA_GADNUM(12))
#define ID_FE_FLOATSTR(x) \
			(MO_EDITING | WI_WINDOW21 | GP_STRING1  | GA_GADNUM(x))
#define ID_FE_ARROWLEFT(x) \
			(MO_EDITING | WI_WINDOW21 | GP_ARROW1   | GA_GADNUM(x))
#define ID_FE_ARROWRIGHT(x) \
			(MO_EDITING | WI_WINDOW21 | GP_ARROW2   | GA_GADNUM(x))
#define ID_FE_PALCOLCYCLE(x) \
			(MO_EDITING | WI_WINDOW21 | GP_CYCLE1   | GA_GADNUM(x))
#define ID_FE_CHECK(x)	(MO_EDITING | WI_WINDOW21 | GP_BUTTONS2 | GA_GADNUM(x))

#define ID_FE_GROUPLIST	(MO_EDITING | WI_WINDOW21 | GP_LIST1    | GA_GADNUM(0))
#define ID_FE_GROUPLISTDBCLICK \
			(MO_EDITING | WI_WINDOW21 | GP_LIST2    | GA_GADNUM(0))
#define ID_FE_IMAGELIST	(MO_EDITING | WI_WINDOW21 | GP_LIST3    | GA_GADNUM(0))
#define ID_FE_IMAGELISTDBCLICK \
			(MO_EDITING | WI_WINDOW21 | GP_LIST4    | GA_GADNUM(0))

/*
** Database Module
*/
#define ID_DE_WINDOW	(MO_DATABASE | WI_WINDOW1)	/* edit database */
#define ID_DL_WINDOW	(MO_DATABASE | WI_WINDOW2)	/* directory list */
#define ID_DB_ACTIVATE	(MO_DATABASE | WI_WINDOW0 | GP_ACTIVEWIN)
#define ID_DB_QUIT	(MO_DATABASE | WI_WINDOW0 | GP_BUTTONS1 | GA_GADNUM(0))
#define ID_DB_LOAD	(MO_DATABASE | WI_WINDOW0 | GP_BUTTONS1 | GA_GADNUM(1))
#define ID_DB_APPEND	(MO_DATABASE | WI_WINDOW0 | GP_BUTTONS1 | GA_GADNUM(2))
#define ID_DB_CREATE	(MO_DATABASE | WI_WINDOW0 | GP_BUTTONS1 | GA_GADNUM(3))
#define ID_DB_EDIT	(MO_DATABASE | WI_WINDOW0 | GP_BUTTONS1 | GA_GADNUM(4))
#define ID_DB_SAVE	(MO_DATABASE | WI_WINDOW0 | GP_BUTTONS1 | GA_GADNUM(5))
#define ID_DB_LOADCONFIG \
			(MO_DATABASE | WI_WINDOW0 | GP_BUTTONS1 | GA_GADNUM(6))
#define ID_DB_SAVECONFIG \
			(MO_DATABASE | WI_WINDOW0 | GP_BUTTONS1 | GA_GADNUM(7))
#define ID_DB_SAVECUR	(MO_DATABASE | WI_WINDOW0 | GP_BUTTONS1 | GA_GADNUM(8))
#define ID_DB_LAYOUT	(MO_DATABASE | WI_WINDOW0 | GP_CYCLE1   | GA_GADNUM(1))

/* Database Editing */
#define ID_DE_ACTIVATE	(MO_DATABASE | WI_WINDOW1 | GP_ACTIVEWIN)
#define ID_DE_APPLY	(MO_DATABASE | WI_WINDOW1 | GP_BUTTONS1 | GA_GADNUM(1))
#define ID_DE_NEW	(MO_DATABASE | WI_WINDOW1 | GP_BUTTONS1 | GA_GADNUM(4))
#define ID_DE_REMOVE	(MO_DATABASE | WI_WINDOW1 | GP_BUTTONS1 | GA_GADNUM(6))
#define ID_DE_LABEL	(MO_DATABASE | WI_WINDOW1 | GP_BUTTONS1 | GA_GADNUM(7))
#define ID_DE_NAME	(MO_DATABASE | WI_WINDOW1 | GP_BUTTONS1 | GA_GADNUM(8))
#define ID_DE_SEARCH	(MO_DATABASE | WI_WINDOW1 | GP_BUTTONS1 | GA_GADNUM(9))
#define ID_DE_SORT	(MO_DATABASE | WI_WINDOW1 | GP_BUTTONS1 | GA_GADNUM(10))
#define ID_DE_ADD	(MO_DATABASE | WI_WINDOW1 | GP_BUTTONS1 | GA_GADNUM(11))
#define ID_DE_CHECK	(MO_DATABASE | WI_WINDOW1 | GP_BUTTONS2 | GA_GADNUM(0))
#define ID_DE_LAYERSEL(x) \
			(MO_DATABASE | WI_WINDOW1 | GP_BUTTONS3 | GA_GADNUM(x))
#define ID_DE_LAYERON(x) \
			(MO_DATABASE | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(x))
#define ID_DE_LAYEROFF(x) \
			(MO_DATABASE | WI_WINDOW1 | GP_BUTTONS5 | GA_GADNUM(x))
#define ID_DE_STRING(x)	(MO_DATABASE | WI_WINDOW1 | GP_STRING1  | GA_GADNUM(x))
#define ID_DE_INTSTR(x)	(MO_DATABASE | WI_WINDOW1 | GP_STRING2  | GA_GADNUM(x))
#define ID_DE_PROP(x)	(MO_DATABASE | WI_WINDOW1 | GP_PROP1    | GA_GADNUM(x))
#define ID_DE_LINECYCLE	(MO_DATABASE | WI_WINDOW1 | GP_CYCLE1   | GA_GADNUM(0))
#define ID_DE_SPECCYCLE	(MO_DATABASE | WI_WINDOW1 | GP_CYCLE1   | GA_GADNUM(1))
#define ID_DE_LIST	(MO_DATABASE | WI_WINDOW1 | GP_LIST1    | GA_GADNUM(0))
#define ID_DE_LISTDBCLICK \
			(MO_DATABASE | WI_WINDOW1 | GP_LIST2    | GA_GADNUM(0))
#define ID_DE_ARROWLEFT(x) \
			(MO_DATABASE | WI_WINDOW1 | GP_ARROW1   | GA_GADNUM(x))
#define ID_DE_ARROWRIGHT(x) \
			(MO_DATABASE | WI_WINDOW1 | GP_ARROW2   | GA_GADNUM(x))
/*
#define ID_DE_LGARROWLEFT \
			(MO_DATABASE | WI_WINDOW1 | GP_ARROW3   | GA_GADNUM(0))
#define ID_DE_LGARROWRIGHT \
			(MO_DATABASE | WI_WINDOW1 | GP_ARROW4   | GA_GADNUM(0))
*/

/* Directory List */
#define ID_DL_ACTIVATE	(MO_DATABASE | WI_WINDOW2 | GP_ACTIVEWIN)
#define ID_DL_CANCEL	(MO_DATABASE | WI_WINDOW2 | GP_BUTTONS1 | GA_GADNUM(0))
#define ID_DL_CLOSEQUERY \
			(MO_DATABASE | WI_WINDOW2 | GP_BUTTONS1 | GA_GADNUM(50))
#define ID_DL_APPLY	(MO_DATABASE | WI_WINDOW2 | GP_BUTTONS1 | GA_GADNUM(1))
#define ID_DL_ADD	(MO_DATABASE | WI_WINDOW2 | GP_BUTTONS1 | GA_GADNUM(2))
#define ID_DL_SWAP	(MO_DATABASE | WI_WINDOW2 | GP_BUTTONS1 | GA_GADNUM(3))
#define ID_DL_MOVE	(MO_DATABASE | WI_WINDOW2 | GP_BUTTONS1 | GA_GADNUM(4))
#define ID_DL_REMOVE	(MO_DATABASE | WI_WINDOW2 | GP_BUTTONS1 | GA_GADNUM(5))
#define ID_DL_DEFAULT	(MO_DATABASE | WI_WINDOW2 | GP_BUTTONS1 | GA_GADNUM(6))
#define ID_DL_READONLY	(MO_DATABASE | WI_WINDOW2 | GP_BUTTONS1 | GA_GADNUM(7))
#define ID_DL_LOAD	(MO_DATABASE | WI_WINDOW2 | GP_BUTTONS1 | GA_GADNUM(8))
#define ID_DL_LIST	(MO_DATABASE | WI_WINDOW2 | GP_LIST1    | GA_GADNUM(0))

/*
** Data Operations Module
*/
#define ID_DC_WINDOW	(MO_DATAOPS | WI_WINDOW2)
#define ID_DI_WINDOW	(MO_DATAOPS | WI_WINDOW3)
#define ID_DM_WINDOW	(MO_DATAOPS | WI_WINDOW4)
#define ID_MD_WINDOW	(MO_DATAOPS | WI_WINDOW5)
#define ID_GR_WINDOW	(MO_DATAOPS | WI_WINDOW6)
#define ID_DO_ACTIVATE	(MO_DATAOPS | WI_WINDOW0 | GP_ACTIVEWIN)
#define ID_DO_QUIT	(MO_DATAOPS | WI_WINDOW0 | GP_BUTTONS1 | GA_GADNUM(0))
#define ID_DO_EXTRACT	(MO_DATAOPS | WI_WINDOW0 | GP_BUTTONS1 | GA_GADNUM(1))
#define ID_DO_IMPORTDLG	(MO_DATAOPS | WI_WINDOW0 | GP_BUTTONS1 | GA_GADNUM(2))
#define ID_DO_IMPORTDXF	(MO_DATAOPS | WI_WINDOW0 | GP_BUTTONS1 | GA_GADNUM(3))
#define ID_DO_IMPORTWDB	(MO_DATAOPS | WI_WINDOW0 | GP_BUTTONS1 | GA_GADNUM(4))
#define ID_DO_FACES	(MO_DATAOPS | WI_WINDOW0 | GP_BUTTONS1 | GA_GADNUM(5))
#define ID_DO_RELELEV	(MO_DATAOPS | WI_WINDOW0 | GP_BUTTONS1 | GA_GADNUM(6))
#define ID_DO_INTERPMAP	(MO_DATAOPS | WI_WINDOW0 | GP_BUTTONS1 | GA_GADNUM(7))
#define ID_DO_LAYOUT	(MO_DATAOPS | WI_WINDOW0 | GP_CYCLE1   | GA_GADNUM(0))

/* DEM Convert */
#define ID_DC_ACTIVATE	(MO_DATAOPS | WI_WINDOW2 | GP_ACTIVEWIN)
#define ID_DC_CLOSE	(MO_DATAOPS | WI_WINDOW2 | GP_BUTTONS1 | GA_GADNUM(0))
#define ID_DC_CONVERT	(MO_DATAOPS | WI_WINDOW2 | GP_BUTTONS1 | GA_GADNUM(1))
#define ID_DC_GETFILE	(MO_DATAOPS | WI_WINDOW2 | GP_BUTTONS1 | GA_GADNUM(2))
#define ID_DC_GETOUTDIR	(MO_DATAOPS | WI_WINDOW2 | GP_BUTTONS1 | GA_GADNUM(3))
#define ID_DC_TEST	(MO_DATAOPS | WI_WINDOW2 | GP_BUTTONS1 | GA_GADNUM(4))
#define ID_DC_ARROWLEFT(x) \
			(MO_DATAOPS | WI_WINDOW2 | GP_ARROW1   | GA_GADNUM(x))
#define ID_DC_ARROWRIGHT(x) \
			(MO_DATAOPS | WI_WINDOW2 | GP_ARROW2   | GA_GADNUM(x))

/* DEM Interpolate */
#define ID_DI_ACTIVATE	(MO_DATAOPS | WI_WINDOW3 | GP_ACTIVEWIN)
#define ID_DI_CLOSE	(MO_DATAOPS | WI_WINDOW3 | GP_BUTTONS1 | GA_GADNUM(0))
#define ID_DI_INTERP	(MO_DATAOPS | WI_WINDOW3 | GP_BUTTONS1 | GA_GADNUM(1))
#define ID_DI_GETFILES	(MO_DATAOPS | WI_WINDOW3 | GP_BUTTONS1 | GA_GADNUM(2))

/* DEM Extract */
#define ID_DM_ACTIVATE	(MO_DATAOPS | WI_WINDOW4 | GP_ACTIVEWIN)
#define ID_DM_CLOSE	(MO_DATAOPS | WI_WINDOW4 | GP_BUTTONS1 | GA_GADNUM(0))
#define ID_DM_EXTRACT	(MO_DATAOPS | WI_WINDOW4 | GP_BUTTONS1 | GA_GADNUM(1))
#define ID_DM_GETFILES	(MO_DATAOPS | WI_WINDOW4 | GP_BUTTONS1 | GA_GADNUM(2))

/* Make DEM */
#define ID_MD_ACTIVATE	(MO_DATAOPS | WI_WINDOW5 | GP_ACTIVEWIN)
#define ID_MD_CLOSE	(MO_DATAOPS | WI_WINDOW5 | GP_BUTTONS1 | GA_GADNUM(0))
#define ID_MD_IMPORT	(MO_DATAOPS | WI_WINDOW5 | GP_BUTTONS1 | GA_GADNUM(1))
#define ID_MD_SAVE	(MO_DATAOPS | WI_WINDOW5 | GP_BUTTONS1 | GA_GADNUM(2))
#define ID_MD_CLEAR	(MO_DATAOPS | WI_WINDOW5 | GP_BUTTONS1 | GA_GADNUM(3))
#define ID_MD_DRAW	(MO_DATAOPS | WI_WINDOW5 | GP_BUTTONS1 | GA_GADNUM(4))
#define ID_MD_MODE(x)	(MO_DATAOPS | WI_WINDOW5 | GP_BUTTONS2 | GA_GADNUM(x))
#define ID_MD_NOREVERSE	(MO_DATAOPS | WI_WINDOW5 | GP_BUTTONS3 | GA_GADNUM(0))
#define ID_MD_INTSTR(x)	(MO_DATAOPS | WI_WINDOW5 | GP_STRING1  | GA_GADNUM(x))
#define ID_MD_FLOATSTR(x) \
			(MO_DATAOPS | WI_WINDOW5 | GP_STRING2  | GA_GADNUM(x))
#define ID_MD_ARROWLEFT(x) \
			(MO_DATAOPS | WI_WINDOW5 | GP_ARROW1   | GA_GADNUM(x))
#define ID_MD_ARROWRIGHT(x) \
			(MO_DATAOPS | WI_WINDOW5 | GP_ARROW2   | GA_GADNUM(x))
#define ID_MD_CYCLE(x)	(MO_DATAOPS | WI_WINDOW5 | GP_CYCLE1   | GA_GADNUM(x))
#define ID_MD_PROP	(MO_DATAOPS | WI_WINDOW5 | GP_PROP1    | GA_GADNUM(0))

/* Make DEM */
#define ID_GR_ACTIVATE	(MO_DATAOPS | WI_WINDOW6 | GP_ACTIVEWIN)
#define ID_GR_CLOSE	(MO_DATAOPS | WI_WINDOW6 | GP_BUTTONS1 | GA_GADNUM(0))
#define ID_GR_MAKEGRID	(MO_DATAOPS | WI_WINDOW6 | GP_BUTTONS1 | GA_GADNUM(1))
#define ID_GR_MAKENOISE	(MO_DATAOPS | WI_WINDOW6 | GP_BUTTONS1 | GA_GADNUM(2))
#define ID_GR_DRAWDEM	(MO_DATAOPS | WI_WINDOW6 | GP_BUTTONS1 | GA_GADNUM(3))
#define ID_GR_SAVEDEM	(MO_DATAOPS | WI_WINDOW6 | GP_BUTTONS1 | GA_GADNUM(4))
#define ID_GR_INTSTR(x)	(MO_DATAOPS | WI_WINDOW6 | GP_STRING1  | GA_GADNUM(x))
#define ID_GR_FLOATSTR(x) \
			(MO_DATAOPS | WI_WINDOW6 | GP_STRING2  | GA_GADNUM(x))
#define ID_GR_ARROW(x) 	(MO_DATAOPS | WI_WINDOW6 | GP_ARROW1   | GA_GADNUM(x))

/*
** New MUI Mapping stuff
*/
#define ID_MA_ACTIVATE	(MO_MAPPING | WI_WINDOW0 | GP_ACTIVEWIN)
#define ID_MC_QUIT	(MO_MAPPING | WI_WINDOW0 | GP_BUTTONS1 | GA_GADNUM(1))
#define ID_MC_ACTIVATE	(MO_MAPPING | WI_WINDOW1 | GP_ACTIVEWIN)

#define ID_MC_ZOOM	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS1 | GA_GADNUM(1))
#define ID_MC_PAN	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS1 | GA_GADNUM(2))
#define ID_MC_CENTER	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS1 | GA_GADNUM(3))
#define ID_MC_AUTO	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS1 | GA_GADNUM(4))

#define ID_MC_AUTOCLEAR	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS2 | GA_GADNUM(1))
#define ID_MC_CLEAR	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS2 | GA_GADNUM(2))
#define ID_MC_DRAW	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS2 | GA_GADNUM(3))
#define ID_MC_REFINE	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS2 | GA_GADNUM(4))

#define ID_MC_TOPO	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS3 | GA_GADNUM(1))
#define ID_MC_VEC	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS3 | GA_GADNUM(2))
#define ID_MC_ECO	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS3 | GA_GADNUM(3))
#define ID_MC_INTER	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS3 | GA_GADNUM(4))

#define ID_MC_DITHER	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS3 | GA_GADNUM(5))
#define ID_MC_MAPSTYLE	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS3 | GA_GADNUM(6))
#define ID_MC_MAPCOLOR	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS3 | GA_GADNUM(7))

#define ID_MC_SCALE	(MO_MAPPING | WI_WINDOW1 | GP_PROP1 | GA_GADNUM(1))
#define ID_MC_SCALELESS	(MO_MAPPING | WI_WINDOW1 | GP_PROP1 | GA_GADNUM(2))
#define ID_MC_SCALEMORE	(MO_MAPPING | WI_WINDOW1 | GP_PROP1 | GA_GADNUM(3))
#define ID_MC_LAT	(MO_MAPPING | WI_WINDOW1 | GP_PROP1 | GA_GADNUM(4))
#define ID_MC_LATLESS	(MO_MAPPING | WI_WINDOW1 | GP_PROP1 | GA_GADNUM(5))
#define ID_MC_LATMORE	(MO_MAPPING | WI_WINDOW1 | GP_PROP1 | GA_GADNUM(6))
#define ID_MC_LON	(MO_MAPPING | WI_WINDOW1 | GP_PROP1 | GA_GADNUM(7))
#define ID_MC_LONLESS	(MO_MAPPING | WI_WINDOW1 | GP_PROP1 | GA_GADNUM(8))
#define ID_MC_LONMORE	(MO_MAPPING | WI_WINDOW1 | GP_PROP1 | GA_GADNUM(9))
#define ID_MC_EXAG	(MO_MAPPING | WI_WINDOW1 | GP_PROP1 | GA_GADNUM(10))
#define ID_MC_EXAGLESS	(MO_MAPPING | WI_WINDOW1 | GP_PROP1 | GA_GADNUM(11))
#define ID_MC_EXAGMORE	(MO_MAPPING | WI_WINDOW1 | GP_PROP1 | GA_GADNUM(12))

#define ID_MC_LOADALL	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(0))
#define ID_MC_LOADACTIVE \
			(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(1))
#define ID_MC_LOADTOPOS	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(2))
#define ID_MC_SAVEALL	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(3))
#define ID_MC_SAVEACTIVE \
			(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(4))
#define ID_MC_PRINT 	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(5))
#define ID_MC_ALIGN 	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(6))
#define ID_MC_COLORMAP 	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(7))
#define ID_MC_VIEWSHED 	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(8))
#define ID_MC_FIXFLATS 	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(9))
#define ID_MC_FINDMOUSE (MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(10))
#define ID_MC_OUTLINE 	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(11))
#define ID_MC_ADDPTSNEW (MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(12))
#define ID_MC_ADDPTSAPPEND \
			(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(13))
#define ID_MC_ADDPTSINSERT \
			(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(14))
#define ID_MC_STREAMNEW (MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(15))
#define ID_MC_STREAMAPPEND \
			(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(16))
#define ID_MC_MODPTS 	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(17))
#define ID_MC_CONFORMALL \
			(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(18))
#define ID_MC_CONFORMACT \
			(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(19))
#define ID_MC_MATCHPTS 	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(20))
#define ID_MC_MOVEORIG 	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(21))
#define ID_MC_INPUT 	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(22))
#define ID_MC_LOADSTATS (MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(23))
#define ID_MC_NORMALIZE (MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(24))
#define ID_MC_GRAPHSTYLE \
			(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(25))
#define ID_MC_GRAPH	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(26))
#define ID_MC_ERASE	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(27))
#define ID_MC_INTERACT	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(28))
#define ID_MC_SETCAM	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(29))
#define ID_MC_SETFOC	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(30))
#define ID_MC_SURFONE	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(31))
#define ID_MC_SURFTWO	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(32))
#define ID_MC_SURFTHREE	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(33))
#define ID_MC_SURFFOUR	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(34))
#define ID_MC_INTERP	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(35))
#define ID_MC_VECCAM	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(36))
#define ID_MC_VECFOC	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(37))
#define ID_MC_CAMVEC	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(38))
#define ID_MC_FOCVEC	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(39))
#define ID_MC_NEWOBJECT	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(40))
#define ID_MC_CTRLTOFR	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(41))
#define ID_MC_REGISTER	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(42))
#define ID_MC_MAPALIGN	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(43))
#define ID_MC_ALIGNCHECK \
			(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(44))
#define ID_MC_FINDMULTI	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(45))
#define ID_MC_ZOOMIN	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(46))
#define ID_MC_ZOOMOUT	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(47))
#define ID_MC_MOVELEFT	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(48))
#define ID_MC_MOVERIGHT	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(49))
#define ID_MC_MOVEUP	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(50))
#define ID_MC_MOVEDOWN	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(51))
#define ID_MC_DUPLICATE	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(52))
#define ID_MC_MAKEDEM	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(53))
#define ID_MC_MAKECLOUD	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(54))
#define ID_MC_BUILDDEM	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(55))
#define ID_MC_FRACTALMAP \
			(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(56))
#define ID_MC_FINDDIST	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(57))
#define ID_MC_PARTICLETREE \
			(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS4 | GA_GADNUM(58))
#define ID_MA_CLOSE	(MO_MAPPING | WI_WINDOW1 | GP_BUTTONS5 | GA_GADNUM(0))

#define ID_MC_FLOATSTR(x) \
			(MO_MAPPING | WI_WINDOW1 | GP_STRING1  | GA_GADNUM(x))
#define ID_MC_INTSTR(x)	(MO_MAPPING | WI_WINDOW1 | GP_STRING2  | GA_GADNUM(x))

/*
** Render Module
*/
#define ID_RN_ACTIVATE	(MO_RENDER | WI_WINDOW0 | GP_ACTIVEWIN)
#define ID_RN_QUIT	(MO_RENDER | WI_WINDOW0 | GP_BUTTONS1 | GA_GADNUM(0))
#define ID_RN_RENDER	(MO_RENDER | WI_WINDOW0 | GP_BUTTONS1 | GA_GADNUM(1))
#define ID_RN_LAYOUT	(MO_RENDER | WI_WINDOW0 | GP_CYCLE1   | GA_GADNUM(0))

#endif
