/* VocabTable.h
**
** #defines for Markov search table.
** Machine generated code, do NOT hand-alter.
** Created from file "info/GrammarTest".
*/

extern unsigned long int MarkovTable[];

#define VE_ADD                    32 /* ADd */
#define VE_ALIAS                  38 /* ALIas */
#define VE_ALL                    39 /* ALL */
#define VE_ALTITUDE               45 /* ALTitude */
#define VE_ANTIALIAS              53 /* ANtialias */
#define VE_ARC                    55 /* ARc */
#define VE_AS                     56 /* AS */
#define VE_ASPECT                 61 /* ASPect */
#define VE_ASYNC                  64 /* ASYnc */
#define VE_AZ                     65 /* AZ */
#define VE_BACKGROUND             79 /* BACkground */
#define VE_BANK                   81 /* BANk */
#define VE_BIAS                   84 /* BIas */
#define VE_BLUE                   87 /* BLue */
#define VE_BORDER                 92 /* BOrder */
#define VE_CAMERA                103 /* CAMEra */
#define VE_CAMVIEW               107 /* CAMView */
#define VE_CENTER                112 /* CEnter */
#define VE_CLEAR                 117 /* CLEar */
#define VE_CLOUDS                121 /* CLOuds */
#define VE_COLOR                 127 /* COLor */
#define VE_COMPOSITE             134 /* COMposite */
#define VE_CONTINUITY            142 /* CONtinuity */
#define VE_CURRENT               148 /* CUrrent */
#define VE_DATABASE              160 /* DATAbase */
#define VE_DATUM                 162 /* DATUm */
#define VE_DEFAULT               170 /* DEFault */
#define VE_DELETE                174 /* DELete */
#define VE_DENSITY               179 /* DENsity */
#define VE_DIR                   182 /* DIR */
#define VE_DIRLIST               186 /* DIRList */
#define VE_DISTRIBUTION          196 /* DIStribution */
#define VE_DRAW                  199 /* DRaw */
#define VE_EARTH                 208 /* EARth */
#define VE_EASE                  210 /* EASe */
#define VE_ECOSYSTEM             218 /* ECosystem */
#define VE_ENABLED               224 /* ENabled */
#define VE_EXAGGERATION          236 /* EXAggeration */
#define VE_EXPORT                240 /* EXPort */
#define VE_FACTOR                252 /* FACtor */
#define VE_FADE                  254 /* FADe */
#define VE_FIELD                 260 /* FIEld */
#define VE_FILENAME              266 /* FILename */
#define VE_FIX                   267 /* FIX */
#define VE_FIXED                 269 /* FIXEd */
#define VE_FLATTEN               275 /* FLATTEN */
#define VE_FLATTENING            278 /* FLATTENIng */
#define VE_FOCUS                 284 /* FOCus */
#define VE_FOG                   285 /* FOG */
#define VE_FORMAT                289 /* FORmat */
#define VE_FRACTAL               296 /* FRACtal */
#define VE_FRAMES                299 /* FRAMes */
#define VE_FULL                  302 /* FUll */
#define VE_GLOBAL                309 /* GLobal */
#define VE_GRADIENT              319 /* GRADient */
#define VE_GRAPH                 321 /* GRAPh */
#define VE_GREEN                 324 /* GREen */
#define VE_GRID                  326 /* GRId */
#define VE_HALF                  336 /* HALf */
#define VE_HAZE                  338 /* HAZe */
#define VE_HEIGHT                343 /* HEight */
#define VE_HIGH                  346 /* HIgh */
#define VE_HORIZON               352 /* HOrizon */
#define VE_HSV                   354 /* HSv */
#define VE_HUE                   356 /* HUe */
#define VE_IFF                   360 /* IFf */
#define VE_IN                    361 /* IN */
#define VE_INQUIRE               366 /* INQuire */
#define VE_KEYFRAME              374 /* Keyframe */
#define VE_LATITUDE              384 /* LAtitude */
#define VE_LINE                  387 /* LIne */
#define VE_LOAD                  393 /* LOAd */
#define VE_LONGITUDE             400 /* LONgitude */
#define VE_LOOKAHEAD             407 /* LOOkahead */
#define VE_LOW                   408 /* LOW */
#define VE_MAKE                  417 /* MAKe */
#define VE_MAP                   418 /* MAP */
#define VE_MAPVIEW               422 /* MAPView */
#define VE_MATCH                 425 /* MATch */
#define VE_MAXIMUM               430 /* MAXimum */
#define VE_MINIMUM               436 /* MInimum */
#define VE_MODE                  441 /* MODE */
#define VE_MODEL                 442 /* MODEL */
#define VE_MODULE                445 /* MODUle */
#define VE_MOTION                449 /* MOTion */
#define VE_NAME                  454 /* NAme */
#define VE_NOGUIWARNINGS         469 /* NOGuiwarnings */
#define VE_NONE                  471 /* NONe */
#define VE_NORMAL                475 /* NORmal */
#define VE_NOTIFYME              481 /* NOTifyme */
#define VE_OFF                   488 /* OFF */
#define VE_OFFSET                491 /* OFFSet */
#define VE_ON                    492 /* ON */
#define VE_OPEN                  496 /* OPEn */
#define VE_OPTIONS               501 /* OPTions */
#define VE_OUT                   503 /* OUt */
#define VE_OVERSCAN              510 /* OVerscan */
#define VE_PALETTE               522 /* PALette */
#define VE_PARAMETERS            530 /* PARameters */
#define VE_PATH                  532 /* PATh */
#define VE_PICTURE               538 /* PIcture */
#define VE_POINT                 542 /* POint */
#define VE_PRIORITY              550 /* PRIority */
#define VE_PROJECT               555 /* PROject */
#define VE_QUARTER               563 /* QUArter */
#define VE_QUIT                  565 /* QUIt */
#define VE_RANDOM                575 /* RANDom */
#define VE_RANGE                 577 /* RANGe */
#define VE_RED                   582 /* RED */
#define VE_REFERENCE             589 /* REFerence */
#define VE_RELEL                 593 /* RELEl */
#define VE_RELIEF                596 /* RELIef */
#define VE_RENDER                600 /* RENder */
#define VE_RGB                   602 /* RGb */
#define VE_ROTATION              609 /* ROtation */
#define VE_SATURATION            630 /* SATuration */
#define VE_SAVE                  632 /* SAVe */
#define VE_SCALE                 637 /* SCAle */
#define VE_SCREEN                641 /* SCReen */
#define VE_SEGMENTS              649 /* SEGments */
#define VE_SET                   650 /* SET */
#define VE_SETTINGS              655 /* SETTings */
#define VE_SHADE                 659 /* SHade */
#define VE_SIZE                  662 /* SIze */
#define VE_SKEW                  666 /* SKEw */
#define VE_SKY                   667 /* SKY */
#define VE_SLOPE                 671 /* SLope */
#define VE_SNOW                  674 /* SNow */
#define VE_START                 681 /* STARt */
#define VE_STATUS                684 /* STATus */
#define VE_STEP                  686 /* STEp */
#define VE_STRETCH               691 /* STRetch */
#define VE_SUN                   694 /* SUN */
#define VE_SURFACE               699 /* SURface */
#define VE_SYNC                  702 /* SYnc */
#define VE_TEMPORARY             716 /* TEMporary */
#define VE_TENSION               721 /* TENsion */
#define VE_TO                    722 /* TO */
#define VE_TREES                 726 /* TRees */
#define VE_TURN                  729 /* TUrn */
#define VE_TYPE                  732 /* TYpe */
#define VE_UNDERSTORY            742 /* Understory */
#define VE_VALUE                 749 /* VAlue */
#define VE_VECTOR                756 /* VECtor */
#define VE_VELOCITY              762 /* VELocity */
#define VE_VERTICAL              768 /* VERtical */
#define VE_VIEW                  771 /* VIew */
#define VE_WIDTH                 777 /* WIdth */
#define VE_WORLD                 781 /* WOrld */
#define VE_X                     782 /* X */
#define VE_Y                     783 /* Y */
#define VE_Z                     784 /* Z */
#define VE_ZBUFFER               791 /* ZBuffer */
#define VE_ZENITH                796 /* ZEnith */


/* EOF */
