#ifndef WCS_STRINGS_H
#define WCS_STRINGS_H 1

/* Locale Catalog Source File
 *
 * Automatically created by SimpleCat V3
 * Do NOT edit by hand!
 *
 * SimpleCat ©1992-2013 Guido Mersmann
 *
 */



/****************************************************************************/


#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif

#ifdef CATCOMP_ARRAY
#undef CATCOMP_NUMBERS
#undef CATCOMP_STRINGS
#define CATCOMP_NUMBERS
#define CATCOMP_STRINGS
#endif

#ifdef CATCOMP_BLOCK
#undef CATCOMP_STRINGS
#define CATCOMP_STRINGS
#endif



/****************************************************************************/


#ifdef CATCOMP_NUMBERS

#define MSG_MENU_PROJECT 0
#define MSG_MENU_PR_NEW 1
#define MSG_MENU_PR_EDIT 2
#define MSG_MENU_PR_OPEN 3
#define MSG_MENU_PR_SAVE 4
#define MSG_MENU_PR_SAVEAS 5
#define MSG_MENU_PR_LOADCONFIG 6
#define MSG_MENU_PR_SAVECONFIG 7
#define MSG_MENU_PR_SAVESCREEN 8
#define MSG_MENU_PR_INFO 9
#define MSG_MENU_PR_VERSION 10
#define MSG_MENU_PR_CREDITS 11
#define MSG_MENU_PR_LOG 12
#define MSG_MENU_PR_QUIT 13
#define MSG_MENU_PR_ICONIFY 14
#define MSG_MENU_MODULES 15
#define MSG_MENU_MOD_DATABASE 16
#define MSG_MENU_MOD_DATAOPS 17
#define MSG_MENU_MOD_MAPVIEW 18
#define MSG_MENU_MOD_PARAMETERS 19
#define MSG_MENU_MOD_RENDER 20
#define MSG_MENU_MOD_MOTIONEDITOR 21
#define MSG_MENU_MOD_COLOREDITOR 22
#define MSG_MENU_MOD_ECOSYSEDITOR 23
#define MSG_MENU_PREFS 24
#define MSG_MENU_PREF_PREFERENCES 25
#define MSG_MENU_PREF_SCREENMODE 26
#define MSG_MENU_PARAMETERS 27
#define MSG_MENU_PAR_LOADALL 28
#define MSG_MENU_PAR_SAVEALL 29
#define MSG_MENU_PAR_FREEZE 30
#define MSG_MENU_PAR_RESTORE 31
#define MSG_TYPENAME_WATER 32
#define MSG_TYPENAME_SNOW 33
#define MSG_TYPENAME_ROCK 34
#define MSG_TYPENAME_GROUND 35
#define MSG_TYPENAME_CONIFER 36
#define MSG_TYPENAME_DECID 37
#define MSG_TYPENAME_LOWVEG 38
#define MSG_TYPENAME_SNAG 39
#define MSG_TYPENAME_STUMP 40
#define MSG_VARNAME_CAMERAALTITUDE 41
#define MSG_VARNAME_CAMERALATITUDE 42
#define MSG_VARNAME_CAMERALONGITUDE 43
#define MSG_VARNAME_FOCUSALTITUDE 44
#define MSG_VARNAME_FOCUSLATITUDE 45
#define MSG_VARNAME_FOCUSLONGITUDE 46
#define MSG_VARNAME_CENTERX 47
#define MSG_VARNAME_CENTERY 48
#define MSG_VARNAME_BANK 49
#define MSG_VARNAME_EARTHROTATION 50
#define MSG_VARNAME_SCALE 51
#define MSG_VARNAME_VIEWARC 52
#define MSG_VARNAME_FLATTENING 53
#define MSG_VARNAME_DATUM 54
#define MSG_VARNAME_VERTICALEXAG 55
#define MSG_VARNAME_SUNLIGHTLAT 56
#define MSG_VARNAME_SUNLIGHTLON 57
#define MSG_VARNAME_HORIZONLINE 58
#define MSG_VARNAME_HORIZONPOINT 59
#define MSG_VARNAME_HORIZONSTRETCH 60
#define MSG_VARNAME_HAZESTART 61
#define MSG_VARNAME_HAZERANGE 62
#define MSG_VARNAME_SHADEFACTOR 63
#define MSG_VARNAME_FOGNONE 64
#define MSG_VARNAME_FOGFULL 65
#define MSG_VARNAME_ZMINIMUM 66
#define MSG_VARNAME_SUNLAT 67
#define MSG_VARNAME_SUNLON 68
#define MSG_VARNAME_SUNSIZE 69
#define MSG_VARNAME_MOONLAT 70
#define MSG_VARNAME_MOONLON 71
#define MSG_VARNAME_MOONSIZE 72
#define MSG_VARNAME_REFLECTION 73
#define MSG_STDMESG_OUTOFMEMORY 74
#define MSG_STDMESG_OPENFILEFAILED 75
#define MSG_STDMESG_READFILEFAILED 76
#define MSG_STDMESG_WRITINGTOFILEFAILED 77
#define MSG_STDMESG_WRONGFILETYPE 78
#define MSG_STDMESG_ILLEGALINSTRUCTION 79
#define MSG_STDMESG_ILLEGALVALUE 80
#define MSG_STDMESG_FILENOTLOADED 81
#define MSG_STDMESG_MODULENOTIMPLEMENTED 82
#define MSG_STDMESG_GUINOTIMPLEMENTED 83
#define MSG_STDMESG_PARAMETERFILELOADED 84
#define MSG_STDMESG_PARAMETERFILESAVED 85
#define MSG_STDMESG_DATABASEFILELOADED 86
#define MSG_STDMESG_DATABASEFILESAVED 87
#define MSG_STDMESG_DEMFILELOADED 88
#define MSG_STDMESG_DEMFILESAVED 89
#define MSG_STDMESG_VECTORFILELOADED 90
#define MSG_STDMESG_VECTORFILESAVED 91
#define MSG_STDMESG_IMAGEFILELOADED 92
#define MSG_STDMESG_IMAGEFILESAVED 93
#define MSG_STDMESG_COLORMAPFILELOADED 94
#define MSG_STDMESG_COLORMAPFILESAVED 95
#define MSG_STDMESG_ENABLE_SOFT_OUTLINE_STYLE 96
#define MSG_STDMESG_MAPPINGMODULE 97
#define MSG_STDMESG_DIRECTORYNOTFOUND 98
#define MSG_STDMESG_OPENWINDOWFAILED 99
#define MSG_STDMESG_EMPTY 100
#define MSG_STDMESG_INCORRECTFILESIZE 101
#define MSG_STDMESG_INCORRECTFILEVERSION 102
#define MSG_STDMESG_RELATIVEELEVATIONFILESAVED 103
#define MSG_STDMESG_VECTOROBJECTSLOADED 104
#define MSG_STDMESG_PROJECTFILELOADED 105
#define MSG_STDMESG_PROJECTFILESAVED 106
#define MSG_STDMESG_DIRECTORYLISTLOADED 107
#define MSG_STDMESG_RENDERTIMEFORFRAME 108
#define MSG_STDMESG_RENDERTIMEFORANIM 109
#define MSG_SCNRMODGUI_NONE 110
#define MSG_SCNRMODGUI_TEXT 111
#define MSG_SCNRMODGUI_STANDARD 112
#define MSG_SCNRMODGUI_MAX 113
#define MSG_SCNRMODGUI_VIDEO 114
#define MSG_SCNRMODGUI_WORLDCONSTRUCTIONSETSCREENMODE 115
#define MSG_SCNRMODGUI_DISPLAYMODE 116
#define MSG_SCNRMODGUI_MODEINFORMATION 117
#define MSG_SCNRMODGUI_MODEESUTOCANNATTRIBUTESN 118
#define MSG_SCNRMODGUI_SAVE 119
#define MSG_SCNRMODGUI_USE 120
#define MSG_SCNRMODGUI_EXIT 121
#define MSG_SCNRMODGUI_MODE0XESXXUTOXCANNSNATTRIBUTES 122
#define MSG_SCNRMODGUI_LACED 123
#define MSG_SCNRMODGUI_GENLOCKABLE 124
#define MSG_SCNRMODGUI_DRAGGABLE 125
#define MSG_SCNRMODGUI_OVERSCAN 126
#define MSG_SCNRMODGUI_WIDTH 127
#define MSG_SCNRMODGUI_HEIGHT 128
#define MSG_AGUI_PARAMETERMODULE 129
#define MSG_AGUI_MOTION 130
#define MSG_AGUI_COLOR 131
#define MSG_AGUI_ECOSYSTEM 132
#define MSG_AGUI_CLOUDS 133
#define MSG_AGUI_WAVES 134
#define MSG_AGUI_DEFAULTS 135
#define MSG_AGUI_PARAMETERSMODULE 136
#define MSG_AGUI_OUTOFMEMORY 137
#define MSG_AGUI_CREATEDEFAULTPARAMETERSFORDATABASEALLCURRENTPARAMETERS 138
#define MSG_AGUI_PARAMETEREDITINGDEFAULTS 139
#define MSG_AGUI_OKCANCEL 140
#define MSG_AGUI_YOUMUSTFIRSTLOADADATABASEBEFOREDEFAULTPARAMETERSCANBEC 141
#define MSG_AGUI_OK 142
#define MSG_AGUI_STANDUP 143
#define MSG_AGUI_LAYDOWN 144
#define MSG_AGUI_LOAD 145
#define MSG_AGUI_APPEND 146
#define MSG_AGUI_CREATE 147
#define MSG_AGUI_EDIT 148
#define MSG_AGUI_SAVE 149
#define MSG_AGUI_DIRLIST 150
#define MSG_AGUI_DATAOPSIMPORTDLG 151
#define MSG_AGUI_DATAOPSIMPORTDXF 152
#define MSG_AGUI_DATAOPSIMPORTWDB 153
#define MSG_AGUI_DATAOPSMODULEINTERPDEM 154
#define MSG_AGUI_DATAOPSMODULEEXTRACTDEM 155
#define MSG_AGUI_RENDERMODULE 156
#define MSG_AGUI_ADATABASEANDPARAMETERFILE 157
#define MSG_AGUI_MODULECONTROLPANEL 158
#define MSG_AGUI_VERSION 159
#define MSG_AGUI_OKAY 160
#define MSG_AGUI_EXTRASMODULE 161
#define MSG_AGUI_PUBLICSCREENSTILLHASVISITORSTRYCLOSINGAGAIN 162
#define MSG_AGUI_CLOSEWARNCANCEL 163
#define MSG_AGUI_QUITPROGRAMREYOUSURE 164
#define MSG_AGUI_WCSPROJECT 165
#define MSG_AGUI_PROJECTPATHSHAVEBEENMODIFIEDSAVETHEMBEFORECLOSING 166
#define MSG_AGUI_PARAMETERSHAVEBEENMODIFIEDSAVETHEMBEFORECLOSING 167
#define MSG_AGUI_DATABASEHASBEENMODIFIEDSAVEITBEFORECLOSING 168
#define MSG_AGUI_MESSAGE 169
#define MSG_AGUI_NOTYETIMPLEMENTEDTAYTUNED 170
#define MSG_AGUI_KEEPCHANGES 171
#define MSG_AGUI_KEEPCANCEL 172
#define MSG_AGUI_SORRYOUMUSTFIRSTLOAD338NBEFOREUSINGTHISFEATURE 173
#define MSG_AGUI_FILEALREADYEXISTSOYOUWISHTOOVERWRITEIT 174
#define MSG_AGUI_INPUTREQUEST 175
#define MSG_AGUI_CANCEL 176
#define MSG_AGUI_LOGSTATUSMODULE 177
#define MSG_AGUI_CANTOPENLOGSTATUSWINDOW 178
#define MSG_AGUI_CLEAR 179
#define MSG_AGUI_HIDE 180
#define MSG_AGUI_CLOSE 181
#define MSG_AGUI_LOGWINDOW 182
#define MSG_AGUI_LOGWINDOWOPENED 183
#define MSG_AGUI_INFO 184
#define MSG_AGUI_TIME 185
#define MSG_AGUI_DATE 186
#define MSG_AGUI_MEMORY 187
#define MSG_AGUI_AVAILABLE 188
#define MSG_AGUI_LARGEST 189
#define MSG_AGUI_CHIP 190
#define MSG_AGUI_FAST 191
#define MSG_AGUI_TOPOMAPS 192
#define MSG_AGUI_INTER 193
#define MSG_AGUI_MAP 194
#define MSG_AGUI_AREXXPORT 195
#define MSG_AGUI_DATABASE 196
#define MSG_AGUI_PARFILE 197
#define MSG_AGUI_SCREENMODE 198
#define MSG_AGUI_FLUSH 199
#define MSG_AGUI_WCSSCREENMODE 200
#define MSG_AGUI_DATABASEMODULE 201
#define MSG_AGUI_DATABASEMODULEAPPEND 202
#define MSG_AGUI_ADATABASE 203
#define MSG_AGUI_DATABASEMODULESAVE 204
#define MSG_AGUI_DATAOPSMODULE 205
#define MSG_AGUI_EXTRACTDEM 206
#define MSG_AGUI_CONVERTDEM 207
#define MSG_AGUI_INTERPDEM 208
#define MSG_AGUI_IMPORTDLG 209
#define MSG_AGUI_IMPORTDXF 210
#define MSG_AGUI_IMPORTWDB 211
#define MSG_AGUI_EXPORTLW 212
#define MSG_AGUI_MOTIONIO 213
#define MSG_AGUI_STATUSLOG 214
#define MSG_AGUI_ERR 215
#define MSG_AGUI_WNG 216
#define MSG_AGUI_MSG 217
#define MSG_AGUI_DTA 218
#define MSG_AGUI_PREV 219
#define MSG_AGUI_NEXT 220
#define MSG_AGUI_ALL 221
#define MSG_AGUI_KEYSEXIST 222
#define MSG_AGUI_ALL0 223
#define MSG_AGUI_NOOTHERKEYS 224
#define MSG_AGUI_NONE 225
#define MSG_AGUI_USE 226
#define MSG_AGUI_LOADMOTION 227
#define MSG_AGUI_SAVEMOTION 228
#define MSG_AGUI_LOADCOLOR 229
#define MSG_AGUI_SAVECOLOR 230
#define MSG_AGUI_LOADECO 231
#define MSG_AGUI_SAVEECO 232
#define MSG_AGUI_LOADSETTINGS 233
#define MSG_AGUI_SAVESETTINGS 234
#define MSG_BITMAPS_IFFFILEPATHNAME 235
#define MSG_BITMAPS_FILEALREADYEXISTSVERWRITEIT 236
#define MSG_BITMAPS_OKCANCEL 237
#define MSG_BITMAPS_CANTOPENIMAGEFILEFOROUTPUTPERATIONTERMINATED 238
#define MSG_BITMAPS_OK 239
#define MSG_BITMAPS_SAVINGIMAGE 240
#define MSG_BITMAPS_YES 241
#define MSG_BITMAPS_NO 242
#define MSG_BITMAPS_ERRORSAVINGIMAGEPERATIONTERMINATED 243
#define MSG_BITMAPS_LOADINGIMAGE 244
#define MSG_BITMAPS_WRONGIMAGESIZE 245
#define MSG_BITMAPS_WRONGIMAGEDEPTH 246
#define MSG_BITMAPS_BACKGROUND 247
#define MSG_BITMAPS_RENDERMODULE 248
#define MSG_BITMAPS_ERRORLOADINGZBUFFERPERATIONTERMINATED 249
#define MSG_BITMAPS_OUTOFMEMORYMERGINGZBUFFERPERATIONTERMINATED 250
#define MSG_BITMAPS_ERROROPENINGZBUFFERFILEFORINPUTPERATIONTERMINATED 251
#define MSG_BITMAPS_ERRORREADINGZBUFFERFILEOTSINGLEPRECISIONFLOATINGPOI 252
#define MSG_BITMAPS_ERRORREADINGZBUFFERFILEOZBODCHUNKPERATIONTERMINATED 253
#define MSG_BITMAPS_ERRORREADINGZBUFFERFILEOZBUFCHUNKPERATIONTERMINATED 254
#define MSG_BITMAPS_ERRORREADINGZBUFFERFILERONGSIZEPERATIONTERMINATED 255
#define MSG_BITMAPS_ERRORLOADINGBACKGROUNDIMAGEPERATIONTERMINATED 256
#define MSG_BITMAPS_OUTOFMEMORYMERGINGBACKGROUNDPERATIONTERMINATED 257
#define MSG_BITMAPS_ERROROPENINGBACKGROUNDFILEFORINPUTPERATIONTERMINATE 258
#define MSG_BITMAPS_ERRORREADINGBACKGROUNDFILERONGSIZEPERATIONTERMINATE 259
#define MSG_BITMAPS_ERRORREADINGBACKGROUNDFILEOBODYCHUNKPERATIONTERMINA 260
#define MSG_BITMAPS_ERRORREADINGBACKGROUNDFILEOBMHDCHUNKPERATIONTERMINA 261
#define MSG_BITMAPS_ERRORREADINGBACKGROUNDFILEOMPRESSIONERRORPERATIONTE 262

#define CATCOMP_LASTID 262

#endif /* CATCOMP_NUMBERS */


/****************************************************************************/


#ifdef CATCOMP_STRINGS

#define MSG_MENU_PROJECT_STR "Project"
#define MSG_MENU_PR_NEW_STR "New..."
#define MSG_MENU_PR_EDIT_STR "Edit..."
#define MSG_MENU_PR_OPEN_STR "Open..."
#define MSG_MENU_PR_SAVE_STR "Save"
#define MSG_MENU_PR_SAVEAS_STR "Save As..."
#define MSG_MENU_PR_LOADCONFIG_STR "Load Config"
#define MSG_MENU_PR_SAVECONFIG_STR "Save Config"
#define MSG_MENU_PR_SAVESCREEN_STR "Save Screen..."
#define MSG_MENU_PR_INFO_STR "Info..."
#define MSG_MENU_PR_VERSION_STR "Version..."
#define MSG_MENU_PR_CREDITS_STR "Credits..."
#define MSG_MENU_PR_LOG_STR "Log..."
#define MSG_MENU_PR_QUIT_STR "Quit..."
#define MSG_MENU_PR_ICONIFY_STR "Iconify..."
#define MSG_MENU_MODULES_STR "Modules"
#define MSG_MENU_MOD_DATABASE_STR "DataBase"
#define MSG_MENU_MOD_DATAOPS_STR "Data Ops"
#define MSG_MENU_MOD_MAPVIEW_STR "Map View"
#define MSG_MENU_MOD_PARAMETERS_STR "Parameters"
#define MSG_MENU_MOD_RENDER_STR "Render"
#define MSG_MENU_MOD_MOTIONEDITOR_STR "Motion Editor"
#define MSG_MENU_MOD_COLOREDITOR_STR "Color Editor"
#define MSG_MENU_MOD_ECOSYSEDITOR_STR "Ecosys Editor"
#define MSG_MENU_PREFS_STR "Preferences"
#define MSG_MENU_PREF_PREFERENCES_STR "Preferences..."
#define MSG_MENU_PREF_SCREENMODE_STR "Screen Mode..."
#define MSG_MENU_PARAMETERS_STR "Parameters"
#define MSG_MENU_PAR_LOADALL_STR "Load All..."
#define MSG_MENU_PAR_SAVEALL_STR "Save All..."
#define MSG_MENU_PAR_FREEZE_STR "Freeze"
#define MSG_MENU_PAR_RESTORE_STR "Restore"
#define MSG_TYPENAME_WATER_STR "Water"
#define MSG_TYPENAME_SNOW_STR "Snow"
#define MSG_TYPENAME_ROCK_STR "Rock"
#define MSG_TYPENAME_GROUND_STR "Ground"
#define MSG_TYPENAME_CONIFER_STR "Conifer"
#define MSG_TYPENAME_DECID_STR "Decid"
#define MSG_TYPENAME_LOWVEG_STR "Low Veg"
#define MSG_TYPENAME_SNAG_STR "Snag"
#define MSG_TYPENAME_STUMP_STR "Stump"
#define MSG_VARNAME_CAMERAALTITUDE_STR "Camera Altitude"
#define MSG_VARNAME_CAMERALATITUDE_STR "Camera Latitude"
#define MSG_VARNAME_CAMERALONGITUDE_STR "Camera Longitude"
#define MSG_VARNAME_FOCUSALTITUDE_STR "Focus Altitude"
#define MSG_VARNAME_FOCUSLATITUDE_STR "Focus Latitude"
#define MSG_VARNAME_FOCUSLONGITUDE_STR "Focus Longitude"
#define MSG_VARNAME_CENTERX_STR "Center X"
#define MSG_VARNAME_CENTERY_STR "Center Y"
#define MSG_VARNAME_BANK_STR "Bank"
#define MSG_VARNAME_EARTHROTATION_STR "Earth Rotation"
#define MSG_VARNAME_SCALE_STR "Scale"
#define MSG_VARNAME_VIEWARC_STR "View Arc"
#define MSG_VARNAME_FLATTENING_STR "Flattening"
#define MSG_VARNAME_DATUM_STR "Datum"
#define MSG_VARNAME_VERTICALEXAG_STR "Vertical Exag"
#define MSG_VARNAME_SUNLIGHTLAT_STR "Sun Light Lat"
#define MSG_VARNAME_SUNLIGHTLON_STR "Sun Light Lon"
#define MSG_VARNAME_HORIZONLINE_STR "Horizon Line"
#define MSG_VARNAME_HORIZONPOINT_STR "Horizon Point"
#define MSG_VARNAME_HORIZONSTRETCH_STR "Horizon Stretch"
#define MSG_VARNAME_HAZESTART_STR "Haze Start"
#define MSG_VARNAME_HAZERANGE_STR "Haze Range"
#define MSG_VARNAME_SHADEFACTOR_STR "Shade Factor"
#define MSG_VARNAME_FOGNONE_STR "Fog None"
#define MSG_VARNAME_FOGFULL_STR "Fog Full"
#define MSG_VARNAME_ZMINIMUM_STR "Z Minimum"
#define MSG_VARNAME_SUNLAT_STR "Sun Lat"
#define MSG_VARNAME_SUNLON_STR "Sun Lon"
#define MSG_VARNAME_SUNSIZE_STR "Sun Size"
#define MSG_VARNAME_MOONLAT_STR "Moon Lat"
#define MSG_VARNAME_MOONLON_STR "Moon Lon"
#define MSG_VARNAME_MOONSIZE_STR "Moon Size"
#define MSG_VARNAME_REFLECTION_STR "Reflection %"
#define MSG_STDMESG_OUTOFMEMORY_STR " Out of memory!"
#define MSG_STDMESG_OPENFILEFAILED_STR " Open file failed!"
#define MSG_STDMESG_READFILEFAILED_STR " Read file failed!"
#define MSG_STDMESG_WRITINGTOFILEFAILED_STR " Writing to file failed!"
#define MSG_STDMESG_WRONGFILETYPE_STR " Wrong file type!"
#define MSG_STDMESG_ILLEGALINSTRUCTION_STR " Illegal instruction!"
#define MSG_STDMESG_ILLEGALVALUE_STR " Illegal value!"
#define MSG_STDMESG_FILENOTLOADED_STR " File not loaded!"
#define MSG_STDMESG_MODULENOTIMPLEMENTED_STR " Module not implemented."
#define MSG_STDMESG_GUINOTIMPLEMENTED_STR " GUI not implemented."
#define MSG_STDMESG_PARAMETERFILELOADED_STR " Parameter file loaded."
#define MSG_STDMESG_PARAMETERFILESAVED_STR " Parameter file saved."
#define MSG_STDMESG_DATABASEFILELOADED_STR " Database file loaded."
#define MSG_STDMESG_DATABASEFILESAVED_STR " Database file saved."
#define MSG_STDMESG_DEMFILELOADED_STR " DEM file loaded."
#define MSG_STDMESG_DEMFILESAVED_STR " DEM file saved."
#define MSG_STDMESG_VECTORFILELOADED_STR " Vector file loaded."
#define MSG_STDMESG_VECTORFILESAVED_STR " Vector file saved."
#define MSG_STDMESG_IMAGEFILELOADED_STR " Image file loaded."
#define MSG_STDMESG_IMAGEFILESAVED_STR " Image file saved."
#define MSG_STDMESG_COLORMAPFILELOADED_STR " Color Map file loaded."
#define MSG_STDMESG_COLORMAPFILESAVED_STR " Color Map file saved."
#define MSG_STDMESG_ENABLE_SOFT_OUTLINE_STYLE_STR "\33t"
#define MSG_STDMESG_MAPPINGMODULE_STR " Mapping Module."
#define MSG_STDMESG_DIRECTORYNOTFOUND_STR " Directory not found!"
#define MSG_STDMESG_OPENWINDOWFAILED_STR " Open window failed!"
#define MSG_STDMESG_EMPTY_STR ""
#define MSG_STDMESG_INCORRECTFILESIZE_STR " Incorrect file size!"
#define MSG_STDMESG_INCORRECTFILEVERSION_STR " Incorrect file version!"
#define MSG_STDMESG_RELATIVEELEVATIONFILESAVED_STR " Relative Elevation File Saved."
#define MSG_STDMESG_VECTOROBJECTSLOADED_STR " Vector objects loaded."
#define MSG_STDMESG_PROJECTFILELOADED_STR " Project file loaded."
#define MSG_STDMESG_PROJECTFILESAVED_STR " Project file saved."
#define MSG_STDMESG_DIRECTORYLISTLOADED_STR " Directory List loaded"
#define MSG_STDMESG_RENDERTIMEFORFRAME_STR " Render time for frame"
#define MSG_STDMESG_RENDERTIMEFORANIM_STR " Render time for anim,"
#define MSG_SCNRMODGUI_NONE_STR "None"
#define MSG_SCNRMODGUI_TEXT_STR "Text"
#define MSG_SCNRMODGUI_STANDARD_STR "Standard"
#define MSG_SCNRMODGUI_MAX_STR "Max"
#define MSG_SCNRMODGUI_VIDEO_STR "Video"
#define MSG_SCNRMODGUI_WORLDCONSTRUCTIONSETSCREENMODE_STR "World Construction Set Screenmode"
#define MSG_SCNRMODGUI_DISPLAYMODE_STR "\33cDisplay Mode"
#define MSG_SCNRMODGUI_MODEINFORMATION_STR "\33cMode Information"
#define MSG_SCNRMODGUI_MODEESUTOCANNATTRIBUTESN_STR "Mode:           \nRes :                      \nAuto:            \nScan:                   \n\nAttributes\n\n\n"
#define MSG_SCNRMODGUI_SAVE_STR "\33cSave"
#define MSG_SCNRMODGUI_USE_STR "\33cUse"
#define MSG_SCNRMODGUI_EXIT_STR "\33cExit"
#define MSG_SCNRMODGUI_MODE0XESXXUTOXCANNSNATTRIBUTES_STR "Mode: 0x%08lx\nRes : %dx%d - %dx%d\nAuto: %dx%d\nScan: %dns\n\nAttributes\n"
#define MSG_SCNRMODGUI_LACED_STR "Laced\x20"
#define MSG_SCNRMODGUI_GENLOCKABLE_STR "Genlockable\x20"
#define MSG_SCNRMODGUI_DRAGGABLE_STR "Draggable\x20"
#define MSG_SCNRMODGUI_OVERSCAN_STR "Overscan:\x20"
#define MSG_SCNRMODGUI_WIDTH_STR "Width\x20"
#define MSG_SCNRMODGUI_HEIGHT_STR "Height\x20"
#define MSG_AGUI_PARAMETERMODULE_STR "Parameter Module"
#define MSG_AGUI_MOTION_STR "\33l Motion\x20"
#define MSG_AGUI_COLOR_STR "\33l Color\x20"
#define MSG_AGUI_ECOSYSTEM_STR "\33l Ecosystem\x20"
#define MSG_AGUI_CLOUDS_STR "\33l Clouds\x20"
#define MSG_AGUI_WAVES_STR "\33l Waves\x20"
#define MSG_AGUI_DEFAULTS_STR "\33l Defaults\x20"
#define MSG_AGUI_PARAMETERSMODULE_STR "Parameters Module"
#define MSG_AGUI_OUTOFMEMORY_STR "Out of Memory!"
#define MSG_AGUI_CREATEDEFAULTPARAMETERSFORDATABASEALLCURRENTPARAMETERS_STR "Create Default Parameters for Database %s? All current Parameters will be overwritten."
#define MSG_AGUI_PARAMETEREDITINGDEFAULTS_STR "Parameter Editing: Defaults"
#define MSG_AGUI_OKCANCEL_STR "OK|Cancel"
#define MSG_AGUI_YOUMUSTFIRSTLOADADATABASEBEFOREDEFAULTPARAMETERSCANBEC_STR "You must first load a Database before Default Parameters can be computed."
#define MSG_AGUI_OK_STR "OK"
#define MSG_AGUI_STANDUP_STR "Stand Up"
#define MSG_AGUI_LAYDOWN_STR "Lay Down"
#define MSG_AGUI_LOAD_STR "\33l Load\x20"
#define MSG_AGUI_APPEND_STR "\33l Append\x20"
#define MSG_AGUI_CREATE_STR "\33l Create\x20"
#define MSG_AGUI_EDIT_STR "\33l Edit\x20"
#define MSG_AGUI_SAVE_STR "\33l Save\x20"
#define MSG_AGUI_DIRLIST_STR "\33l Dir List\x20"
#define MSG_AGUI_DATAOPSIMPORTDLG_STR "Data Ops: Import DLG"
#define MSG_AGUI_DATAOPSIMPORTDXF_STR "Data Ops: Import DXF"
#define MSG_AGUI_DATAOPSIMPORTWDB_STR "Data Ops: Import WDB"
#define MSG_AGUI_DATAOPSMODULEINTERPDEM_STR "Data Ops Module: Interp DEM"
#define MSG_AGUI_DATAOPSMODULEEXTRACTDEM_STR "Data Ops Module: Extract DEM"
#define MSG_AGUI_RENDERMODULE_STR "Render Module"
#define MSG_AGUI_ADATABASEANDPARAMETERFILE_STR "a Database and Parameter file"
#define MSG_AGUI_MODULECONTROLPANEL_STR "Module Control Panel"
#define MSG_AGUI_VERSION_STR "Version"
#define MSG_AGUI_OKAY_STR "\33cOkay"
#define MSG_AGUI_EXTRASMODULE_STR "Extras Module"
#define MSG_AGUI_PUBLICSCREENSTILLHASVISITORSTRYCLOSINGAGAIN_STR "Public Screen still has visitors. Try closing again?"
#define MSG_AGUI_CLOSEWARNCANCEL_STR "Close|Warn|Cancel"
#define MSG_AGUI_QUITPROGRAMREYOUSURE_STR "Quit Program\nAre you sure?"
#define MSG_AGUI_WCSPROJECT_STR "WCS Project"
#define MSG_AGUI_PROJECTPATHSHAVEBEENMODIFIEDSAVETHEMBEFORECLOSING_STR "Project paths have been modified. Save them before closing?"
#define MSG_AGUI_PARAMETERSHAVEBEENMODIFIEDSAVETHEMBEFORECLOSING_STR "Parameters have been modified. Save them before closing?"
#define MSG_AGUI_DATABASEHASBEENMODIFIEDSAVEITBEFORECLOSING_STR "Database has been modified. Save it before closing?"
#define MSG_AGUI_MESSAGE_STR "Message"
#define MSG_AGUI_NOTYETIMPLEMENTEDTAYTUNED_STR "Not yet implemented.\nStay Tuned!"
#define MSG_AGUI_KEEPCHANGES_STR "Keep changes?"
#define MSG_AGUI_KEEPCANCEL_STR "Keep|Cancel"
#define MSG_AGUI_SORRYOUMUSTFIRSTLOAD338NBEFOREUSINGTHISFEATURE_STR "Sorry!\nYou must first load\n\338%s\0332\nbefore using this feature."
#define MSG_AGUI_FILEALREADYEXISTSOYOUWISHTOOVERWRITEIT_STR "File already exists.\nDo you wish to overwrite it?"
#define MSG_AGUI_INPUTREQUEST_STR "Input Request"
#define MSG_AGUI_CANCEL_STR "\33cCancel"
#define MSG_AGUI_LOGSTATUSMODULE_STR "Log Status Module"
#define MSG_AGUI_CANTOPENLOGSTATUSWINDOW_STR "Can't Open Log Status Window!"
#define MSG_AGUI_CLEAR_STR "\33cClear"
#define MSG_AGUI_HIDE_STR "\33cHide"
#define MSG_AGUI_CLOSE_STR "\33cClose"
#define MSG_AGUI_LOGWINDOW_STR "Log Window"
#define MSG_AGUI_LOGWINDOWOPENED_STR "Log window opened."
#define MSG_AGUI_INFO_STR "Info"
#define MSG_AGUI_TIME_STR "\33rTime\x20"
#define MSG_AGUI_DATE_STR "\33rDate\x20"
#define MSG_AGUI_MEMORY_STR "\33rMemory:"
#define MSG_AGUI_AVAILABLE_STR "\33rAvailable\x20"
#define MSG_AGUI_LARGEST_STR "\33rLargest\x20"
#define MSG_AGUI_CHIP_STR "\33cChip"
#define MSG_AGUI_FAST_STR "\33cFast"
#define MSG_AGUI_TOPOMAPS_STR "\33rTopo Maps\x20"
#define MSG_AGUI_INTER_STR "\33cInter"
#define MSG_AGUI_MAP_STR "\33cMap"
#define MSG_AGUI_AREXXPORT_STR "\33rARexx Port\x20"
#define MSG_AGUI_DATABASE_STR "\33rDatabase\x20"
#define MSG_AGUI_PARFILE_STR "\33rPar File\x20"
#define MSG_AGUI_SCREENMODE_STR "\33rScreenMode\x20"
#define MSG_AGUI_FLUSH_STR "\33cFlush"
#define MSG_AGUI_WCSSCREENMODE_STR "WCS: Screen Mode"
#define MSG_AGUI_DATABASEMODULE_STR "Database Module"
#define MSG_AGUI_DATABASEMODULEAPPEND_STR "Database Moldule: Append"
#define MSG_AGUI_ADATABASE_STR "a Database"
#define MSG_AGUI_DATABASEMODULESAVE_STR "Database Module: Save"
#define MSG_AGUI_DATAOPSMODULE_STR "DataOps Module"
#define MSG_AGUI_EXTRACTDEM_STR "\33l Extract DEM\x20"
#define MSG_AGUI_CONVERTDEM_STR "\33l Convert DEM\x20"
#define MSG_AGUI_INTERPDEM_STR "\33l Interp DEM\x20"
#define MSG_AGUI_IMPORTDLG_STR "\33l Import DLG\x20"
#define MSG_AGUI_IMPORTDXF_STR "\33l Import DXF"
#define MSG_AGUI_IMPORTWDB_STR "\33l Import WDB\x20"
#define MSG_AGUI_EXPORTLW_STR "\33l Export LW\x20"
#define MSG_AGUI_MOTIONIO_STR "\33l Motion I/O\x20"
#define MSG_AGUI_STATUSLOG_STR "Status Log"
#define MSG_AGUI_ERR_STR "ERR:"
#define MSG_AGUI_WNG_STR "WNG:"
#define MSG_AGUI_MSG_STR "MSG:"
#define MSG_AGUI_DTA_STR "DTA:"
#define MSG_AGUI_PREV_STR "\33cPrev"
#define MSG_AGUI_NEXT_STR "\33cNext"
#define MSG_AGUI_ALL_STR "All (%d)"
#define MSG_AGUI_KEYSEXIST_STR "Keys Exist (%d)"
#define MSG_AGUI_ALL0_STR "\33cAll (0)"
#define MSG_AGUI_NOOTHERKEYS_STR "No Other Keys"
#define MSG_AGUI_NONE_STR " -none-\x20"
#define MSG_AGUI_USE_STR "Use"
#define MSG_AGUI_LOADMOTION_STR "Load Motion..."
#define MSG_AGUI_SAVEMOTION_STR "Save Motion..."
#define MSG_AGUI_LOADCOLOR_STR "Load Color..."
#define MSG_AGUI_SAVECOLOR_STR "Save Color..."
#define MSG_AGUI_LOADECO_STR "Load Eco..."
#define MSG_AGUI_SAVEECO_STR "Save Eco..."
#define MSG_AGUI_LOADSETTINGS_STR "Load Settings..."
#define MSG_AGUI_SAVESETTINGS_STR "Save Settings..."
#define MSG_BITMAPS_IFFFILEPATHNAME_STR "IFF File Path/Name"
#define MSG_BITMAPS_FILEALREADYEXISTSVERWRITEIT_STR "File already exists!\nOverwrite it?"
#define MSG_BITMAPS_OKCANCEL_STR "OK|CANCEL"
#define MSG_BITMAPS_CANTOPENIMAGEFILEFOROUTPUTPERATIONTERMINATED_STR "Can't open image file for output!\nOperation terminated."
#define MSG_BITMAPS_OK_STR "OK"
#define MSG_BITMAPS_SAVINGIMAGE_STR "Saving Image"
#define MSG_BITMAPS_YES_STR "YES"
#define MSG_BITMAPS_NO_STR "NO"
#define MSG_BITMAPS_ERRORSAVINGIMAGEPERATIONTERMINATED_STR "Error saving image!\nOperation terminated."
#define MSG_BITMAPS_LOADINGIMAGE_STR "Loading Image"
#define MSG_BITMAPS_WRONGIMAGESIZE_STR "Wrong image size"
#define MSG_BITMAPS_WRONGIMAGEDEPTH_STR "Wrong image depth"
#define MSG_BITMAPS_BACKGROUND_STR "Background"
#define MSG_BITMAPS_RENDERMODULE_STR "Render Module"
#define MSG_BITMAPS_ERRORLOADINGZBUFFERPERATIONTERMINATED_STR "Error loading Z Buffer!\nOperation terminated."
#define MSG_BITMAPS_OUTOFMEMORYMERGINGZBUFFERPERATIONTERMINATED_STR "Out of memory merging Z Buffer!\nOperation terminated."
#define MSG_BITMAPS_ERROROPENINGZBUFFERFILEFORINPUTPERATIONTERMINATED_STR "Error opening Z Buffer file for input!\nOperation terminated."
#define MSG_BITMAPS_ERRORREADINGZBUFFERFILEOTSINGLEPRECISIONFLOATINGPOI_STR "Error reading Z Buffer file!\nNot single precision floating point.\nOperation terminated."
#define MSG_BITMAPS_ERRORREADINGZBUFFERFILEOZBODCHUNKPERATIONTERMINATED_STR "Error reading Z Buffer file!\nNo ZBOD chunk.\nOperation terminated."
#define MSG_BITMAPS_ERRORREADINGZBUFFERFILEOZBUFCHUNKPERATIONTERMINATED_STR "Error reading Z Buffer file!\nNo ZBUF chunk.\nOperation terminated."
#define MSG_BITMAPS_ERRORREADINGZBUFFERFILERONGSIZEPERATIONTERMINATED_STR "Error reading Z Buffer file!\nWrong Size.\nOperation terminated."
#define MSG_BITMAPS_ERRORLOADINGBACKGROUNDIMAGEPERATIONTERMINATED_STR "Error loading background image!\nOperation terminated."
#define MSG_BITMAPS_OUTOFMEMORYMERGINGBACKGROUNDPERATIONTERMINATED_STR "Out of memory merging background!\nOperation terminated."
#define MSG_BITMAPS_ERROROPENINGBACKGROUNDFILEFORINPUTPERATIONTERMINATE_STR "Error opening Background file for input!\nOperation terminated."
#define MSG_BITMAPS_ERRORREADINGBACKGROUNDFILERONGSIZEPERATIONTERMINATE_STR "Error reading Background file!\nWrong Size.\nOperation terminated."
#define MSG_BITMAPS_ERRORREADINGBACKGROUNDFILEOBODYCHUNKPERATIONTERMINA_STR "Error reading Background file!\nNo BODY Chunk.\nOperation terminated."
#define MSG_BITMAPS_ERRORREADINGBACKGROUNDFILEOBMHDCHUNKPERATIONTERMINA_STR "Error reading Background file!\nNo BMHD Chunk.\nOperation terminated."
#define MSG_BITMAPS_ERRORREADINGBACKGROUNDFILEOMPRESSIONERRORPERATIONTE_STR "Error reading Background file!\nCompression error.\nOperation terminated."

#endif /* CATCOMP_STRINGS */


/****************************************************************************/


#ifdef CATCOMP_BLOCK

const char CatCompBlock[] =
{
    "\x00\x00\x00\x00\x00\x08"
    MSG_MENU_PROJECT_STR "\x00"
    "\x00\x00\x00\x01\x00\x08"
    MSG_MENU_PR_NEW_STR "\x00\x00"
    "\x00\x00\x00\x02\x00\x08"
    MSG_MENU_PR_EDIT_STR "\x00"
    "\x00\x00\x00\x03\x00\x08"
    MSG_MENU_PR_OPEN_STR "\x00"
    "\x00\x00\x00\x04\x00\x06"
    MSG_MENU_PR_SAVE_STR "\x00\x00"
    "\x00\x00\x00\x05\x00\x0C"
    MSG_MENU_PR_SAVEAS_STR "\x00\x00"
    "\x00\x00\x00\x06\x00\x0C"
    MSG_MENU_PR_LOADCONFIG_STR "\x00"
    "\x00\x00\x00\x07\x00\x0C"
    MSG_MENU_PR_SAVECONFIG_STR "\x00"
    "\x00\x00\x00\x08\x00\x10"
    MSG_MENU_PR_SAVESCREEN_STR "\x00\x00"
    "\x00\x00\x00\x09\x00\x08"
    MSG_MENU_PR_INFO_STR "\x00"
    "\x00\x00\x00\x0A\x00\x0C"
    MSG_MENU_PR_VERSION_STR "\x00\x00"
    "\x00\x00\x00\x0B\x00\x0C"
    MSG_MENU_PR_CREDITS_STR "\x00\x00"
    "\x00\x00\x00\x0C\x00\x08"
    MSG_MENU_PR_LOG_STR "\x00\x00"
    "\x00\x00\x00\x0D\x00\x08"
    MSG_MENU_PR_QUIT_STR "\x00"
    "\x00\x00\x00\x0E\x00\x0C"
    MSG_MENU_PR_ICONIFY_STR "\x00\x00"
    "\x00\x00\x00\x0F\x00\x08"
    MSG_MENU_MODULES_STR "\x00"
    "\x00\x00\x00\x10\x00\x0A"
    MSG_MENU_MOD_DATABASE_STR "\x00\x00"
    "\x00\x00\x00\x11\x00\x0A"
    MSG_MENU_MOD_DATAOPS_STR "\x00\x00"
    "\x00\x00\x00\x12\x00\x0A"
    MSG_MENU_MOD_MAPVIEW_STR "\x00\x00"
    "\x00\x00\x00\x13\x00\x0C"
    MSG_MENU_MOD_PARAMETERS_STR "\x00\x00"
    "\x00\x00\x00\x14\x00\x08"
    MSG_MENU_MOD_RENDER_STR "\x00\x00"
    "\x00\x00\x00\x15\x00\x0E"
    MSG_MENU_MOD_MOTIONEDITOR_STR "\x00"
    "\x00\x00\x00\x16\x00\x0E"
    MSG_MENU_MOD_COLOREDITOR_STR "\x00\x00"
    "\x00\x00\x00\x17\x00\x0E"
    MSG_MENU_MOD_ECOSYSEDITOR_STR "\x00"
    "\x00\x00\x00\x18\x00\x0C"
    MSG_MENU_PREFS_STR "\x00"
    "\x00\x00\x00\x19\x00\x10"
    MSG_MENU_PREF_PREFERENCES_STR "\x00\x00"
    "\x00\x00\x00\x1A\x00\x10"
    MSG_MENU_PREF_SCREENMODE_STR "\x00\x00"
    "\x00\x00\x00\x1B\x00\x0C"
    MSG_MENU_PARAMETERS_STR "\x00\x00"
    "\x00\x00\x00\x1C\x00\x0C"
    MSG_MENU_PAR_LOADALL_STR "\x00"
    "\x00\x00\x00\x1D\x00\x0C"
    MSG_MENU_PAR_SAVEALL_STR "\x00"
    "\x00\x00\x00\x1E\x00\x08"
    MSG_MENU_PAR_FREEZE_STR "\x00\x00"
    "\x00\x00\x00\x1F\x00\x08"
    MSG_MENU_PAR_RESTORE_STR "\x00"
    "\x00\x00\x00\x20\x00\x06"
    MSG_TYPENAME_WATER_STR "\x00"
    "\x00\x00\x00\x21\x00\x06"
    MSG_TYPENAME_SNOW_STR "\x00\x00"
    "\x00\x00\x00\x22\x00\x06"
    MSG_TYPENAME_ROCK_STR "\x00\x00"
    "\x00\x00\x00\x23\x00\x08"
    MSG_TYPENAME_GROUND_STR "\x00\x00"
    "\x00\x00\x00\x24\x00\x08"
    MSG_TYPENAME_CONIFER_STR "\x00"
    "\x00\x00\x00\x25\x00\x06"
    MSG_TYPENAME_DECID_STR "\x00"
    "\x00\x00\x00\x26\x00\x08"
    MSG_TYPENAME_LOWVEG_STR "\x00"
    "\x00\x00\x00\x27\x00\x06"
    MSG_TYPENAME_SNAG_STR "\x00\x00"
    "\x00\x00\x00\x28\x00\x06"
    MSG_TYPENAME_STUMP_STR "\x00"
    "\x00\x00\x00\x29\x00\x10"
    MSG_VARNAME_CAMERAALTITUDE_STR "\x00"
    "\x00\x00\x00\x2A\x00\x10"
    MSG_VARNAME_CAMERALATITUDE_STR "\x00"
    "\x00\x00\x00\x2B\x00\x12"
    MSG_VARNAME_CAMERALONGITUDE_STR "\x00\x00"
    "\x00\x00\x00\x2C\x00\x10"
    MSG_VARNAME_FOCUSALTITUDE_STR "\x00\x00"
    "\x00\x00\x00\x2D\x00\x10"
    MSG_VARNAME_FOCUSLATITUDE_STR "\x00\x00"
    "\x00\x00\x00\x2E\x00\x10"
    MSG_VARNAME_FOCUSLONGITUDE_STR "\x00"
    "\x00\x00\x00\x2F\x00\x0A"
    MSG_VARNAME_CENTERX_STR "\x00\x00"
    "\x00\x00\x00\x30\x00\x0A"
    MSG_VARNAME_CENTERY_STR "\x00\x00"
    "\x00\x00\x00\x31\x00\x06"
    MSG_VARNAME_BANK_STR "\x00\x00"
    "\x00\x00\x00\x32\x00\x10"
    MSG_VARNAME_EARTHROTATION_STR "\x00\x00"
    "\x00\x00\x00\x33\x00\x06"
    MSG_VARNAME_SCALE_STR "\x00"
    "\x00\x00\x00\x34\x00\x0A"
    MSG_VARNAME_VIEWARC_STR "\x00\x00"
    "\x00\x00\x00\x35\x00\x0C"
    MSG_VARNAME_FLATTENING_STR "\x00\x00"
    "\x00\x00\x00\x36\x00\x06"
    MSG_VARNAME_DATUM_STR "\x00"
    "\x00\x00\x00\x37\x00\x0E"
    MSG_VARNAME_VERTICALEXAG_STR "\x00"
    "\x00\x00\x00\x38\x00\x0E"
    MSG_VARNAME_SUNLIGHTLAT_STR "\x00"
    "\x00\x00\x00\x39\x00\x0E"
    MSG_VARNAME_SUNLIGHTLON_STR "\x00"
    "\x00\x00\x00\x3A\x00\x0E"
    MSG_VARNAME_HORIZONLINE_STR "\x00\x00"
    "\x00\x00\x00\x3B\x00\x0E"
    MSG_VARNAME_HORIZONPOINT_STR "\x00"
    "\x00\x00\x00\x3C\x00\x10"
    MSG_VARNAME_HORIZONSTRETCH_STR "\x00"
    "\x00\x00\x00\x3D\x00\x0C"
    MSG_VARNAME_HAZESTART_STR "\x00\x00"
    "\x00\x00\x00\x3E\x00\x0C"
    MSG_VARNAME_HAZERANGE_STR "\x00\x00"
    "\x00\x00\x00\x3F\x00\x0E"
    MSG_VARNAME_SHADEFACTOR_STR "\x00\x00"
    "\x00\x00\x00\x40\x00\x0A"
    MSG_VARNAME_FOGNONE_STR "\x00\x00"
    "\x00\x00\x00\x41\x00\x0A"
    MSG_VARNAME_FOGFULL_STR "\x00\x00"
    "\x00\x00\x00\x42\x00\x0A"
    MSG_VARNAME_ZMINIMUM_STR "\x00"
    "\x00\x00\x00\x43\x00\x08"
    MSG_VARNAME_SUNLAT_STR "\x00"
    "\x00\x00\x00\x44\x00\x08"
    MSG_VARNAME_SUNLON_STR "\x00"
    "\x00\x00\x00\x45\x00\x0A"
    MSG_VARNAME_SUNSIZE_STR "\x00\x00"
    "\x00\x00\x00\x46\x00\x0A"
    MSG_VARNAME_MOONLAT_STR "\x00\x00"
    "\x00\x00\x00\x47\x00\x0A"
    MSG_VARNAME_MOONLON_STR "\x00\x00"
    "\x00\x00\x00\x48\x00\x0A"
    MSG_VARNAME_MOONSIZE_STR "\x00"
    "\x00\x00\x00\x49\x00\x0E"
    MSG_VARNAME_REFLECTION_STR "\x00\x00"
    "\x00\x00\x00\x4A\x00\x10"
    MSG_STDMESG_OUTOFMEMORY_STR "\x00"
    "\x00\x00\x00\x4B\x00\x14"
    MSG_STDMESG_OPENFILEFAILED_STR "\x00\x00"
    "\x00\x00\x00\x4C\x00\x14"
    MSG_STDMESG_READFILEFAILED_STR "\x00\x00"
    "\x00\x00\x00\x4D\x00\x1A"
    MSG_STDMESG_WRITINGTOFILEFAILED_STR "\x00\x00"
    "\x00\x00\x00\x4E\x00\x12"
    MSG_STDMESG_WRONGFILETYPE_STR "\x00"
    "\x00\x00\x00\x4F\x00\x16"
    MSG_STDMESG_ILLEGALINSTRUCTION_STR "\x00"
    "\x00\x00\x00\x50\x00\x10"
    MSG_STDMESG_ILLEGALVALUE_STR "\x00"
    "\x00\x00\x00\x51\x00\x12"
    MSG_STDMESG_FILENOTLOADED_STR "\x00"
    "\x00\x00\x00\x52\x00\x1A"
    MSG_STDMESG_MODULENOTIMPLEMENTED_STR "\x00\x00"
    "\x00\x00\x00\x53\x00\x16"
    MSG_STDMESG_GUINOTIMPLEMENTED_STR "\x00"
    "\x00\x00\x00\x54\x00\x18"
    MSG_STDMESG_PARAMETERFILELOADED_STR "\x00"
    "\x00\x00\x00\x55\x00\x18"
    MSG_STDMESG_PARAMETERFILESAVED_STR "\x00\x00"
    "\x00\x00\x00\x56\x00\x18"
    MSG_STDMESG_DATABASEFILELOADED_STR "\x00\x00"
    "\x00\x00\x00\x57\x00\x16"
    MSG_STDMESG_DATABASEFILESAVED_STR "\x00"
    "\x00\x00\x00\x58\x00\x12"
    MSG_STDMESG_DEMFILELOADED_STR "\x00"
    "\x00\x00\x00\x59\x00\x12"
    MSG_STDMESG_DEMFILESAVED_STR "\x00\x00"
    "\x00\x00\x00\x5A\x00\x16"
    MSG_STDMESG_VECTORFILELOADED_STR "\x00\x00"
    "\x00\x00\x00\x5B\x00\x14"
    MSG_STDMESG_VECTORFILESAVED_STR "\x00"
    "\x00\x00\x00\x5C\x00\x14"
    MSG_STDMESG_IMAGEFILELOADED_STR "\x00"
    "\x00\x00\x00\x5D\x00\x14"
    MSG_STDMESG_IMAGEFILESAVED_STR "\x00\x00"
    "\x00\x00\x00\x5E\x00\x18"
    MSG_STDMESG_COLORMAPFILELOADED_STR "\x00"
    "\x00\x00\x00\x5F\x00\x18"
    MSG_STDMESG_COLORMAPFILESAVED_STR "\x00\x00"
    "\x00\x00\x00\x60\x00\x04"
    MSG_STDMESG_ENABLE_SOFT_OUTLINE_STYLE_STR "\x00\x00"
    "\x00\x00\x00\x61\x00\x12"
    MSG_STDMESG_MAPPINGMODULE_STR "\x00\x00"
    "\x00\x00\x00\x62\x00\x16"
    MSG_STDMESG_DIRECTORYNOTFOUND_STR "\x00"
    "\x00\x00\x00\x63\x00\x16"
    MSG_STDMESG_OPENWINDOWFAILED_STR "\x00\x00"
    "\x00\x00\x00\x64\x00\x02"
    MSG_STDMESG_EMPTY_STR "\x00\x00"
    "\x00\x00\x00\x65\x00\x16"
    MSG_STDMESG_INCORRECTFILESIZE_STR "\x00"
    "\x00\x00\x00\x66\x00\x1A"
    MSG_STDMESG_INCORRECTFILEVERSION_STR "\x00\x00"
    "\x00\x00\x00\x67\x00\x20"
    MSG_STDMESG_RELATIVEELEVATIONFILESAVED_STR "\x00"
    "\x00\x00\x00\x68\x00\x18"
    MSG_STDMESG_VECTOROBJECTSLOADED_STR "\x00"
    "\x00\x00\x00\x69\x00\x16"
    MSG_STDMESG_PROJECTFILELOADED_STR "\x00"
    "\x00\x00\x00\x6A\x00\x16"
    MSG_STDMESG_PROJECTFILESAVED_STR "\x00\x00"
    "\x00\x00\x00\x6B\x00\x18"
    MSG_STDMESG_DIRECTORYLISTLOADED_STR "\x00\x00"
    "\x00\x00\x00\x6C\x00\x18"
    MSG_STDMESG_RENDERTIMEFORFRAME_STR "\x00\x00"
    "\x00\x00\x00\x6D\x00\x18"
    MSG_STDMESG_RENDERTIMEFORANIM_STR "\x00\x00"
    "\x00\x00\x00\x6E\x00\x06"
    MSG_SCNRMODGUI_NONE_STR "\x00\x00"
    "\x00\x00\x00\x6F\x00\x06"
    MSG_SCNRMODGUI_TEXT_STR "\x00\x00"
    "\x00\x00\x00\x70\x00\x0A"
    MSG_SCNRMODGUI_STANDARD_STR "\x00\x00"
    "\x00\x00\x00\x71\x00\x04"
    MSG_SCNRMODGUI_MAX_STR "\x00"
    "\x00\x00\x00\x72\x00\x06"
    MSG_SCNRMODGUI_VIDEO_STR "\x00"
    "\x00\x00\x00\x73\x00\x22"
    MSG_SCNRMODGUI_WORLDCONSTRUCTIONSETSCREENMODE_STR "\x00"
    "\x00\x00\x00\x74\x00\x10"
    MSG_SCNRMODGUI_DISPLAYMODE_STR "\x00\x00"
    "\x00\x00\x00\x75\x00\x14"
    MSG_SCNRMODGUI_MODEINFORMATION_STR "\x00\x00"
    "\x00\x00\x00\x76\x00\x68"
    MSG_SCNRMODGUI_MODEESUTOCANNATTRIBUTESN_STR "\x00\x00"
    "\x00\x00\x00\x77\x00\x08"
    MSG_SCNRMODGUI_SAVE_STR "\x00\x00"
    "\x00\x00\x00\x78\x00\x06"
    MSG_SCNRMODGUI_USE_STR "\x00"
    "\x00\x00\x00\x79\x00\x08"
    MSG_SCNRMODGUI_EXIT_STR "\x00\x00"
    "\x00\x00\x00\x7A\x00\x46"
    MSG_SCNRMODGUI_MODE0XESXXUTOXCANNSNATTRIBUTES_STR "\x00"
    "\x00\x00\x00\x7B\x00\x08"
    MSG_SCNRMODGUI_LACED_STR "\x00\x00"
    "\x00\x00\x00\x7C\x00\x0E"
    MSG_SCNRMODGUI_GENLOCKABLE_STR "\x00\x00"
    "\x00\x00\x00\x7D\x00\x0C"
    MSG_SCNRMODGUI_DRAGGABLE_STR "\x00\x00"
    "\x00\x00\x00\x7E\x00\x0C"
    MSG_SCNRMODGUI_OVERSCAN_STR "\x00\x00"
    "\x00\x00\x00\x7F\x00\x08"
    MSG_SCNRMODGUI_WIDTH_STR "\x00\x00"
    "\x00\x00\x00\x80\x00\x08"
    MSG_SCNRMODGUI_HEIGHT_STR "\x00"
    "\x00\x00\x00\x81\x00\x12"
    MSG_AGUI_PARAMETERMODULE_STR "\x00\x00"
    "\x00\x00\x00\x82\x00\x0C"
    MSG_AGUI_MOTION_STR "\x00\x00"
    "\x00\x00\x00\x83\x00\x0A"
    MSG_AGUI_COLOR_STR "\x00"
    "\x00\x00\x00\x84\x00\x0E"
    MSG_AGUI_ECOSYSTEM_STR "\x00"
    "\x00\x00\x00\x85\x00\x0C"
    MSG_AGUI_CLOUDS_STR "\x00\x00"
    "\x00\x00\x00\x86\x00\x0A"
    MSG_AGUI_WAVES_STR "\x00"
    "\x00\x00\x00\x87\x00\x0E"
    MSG_AGUI_DEFAULTS_STR "\x00\x00"
    "\x00\x00\x00\x88\x00\x12"
    MSG_AGUI_PARAMETERSMODULE_STR "\x00"
    "\x00\x00\x00\x89\x00\x10"
    MSG_AGUI_OUTOFMEMORY_STR "\x00\x00"
    "\x00\x00\x00\x8A\x00\x58"
    MSG_AGUI_CREATEDEFAULTPARAMETERSFORDATABASEALLCURRENTPARAMETERS_STR "\x00\x00"
    "\x00\x00\x00\x8B\x00\x1C"
    MSG_AGUI_PARAMETEREDITINGDEFAULTS_STR "\x00"
    "\x00\x00\x00\x8C\x00\x0A"
    MSG_AGUI_OKCANCEL_STR "\x00"
    "\x00\x00\x00\x8D\x00\x4A"
    MSG_AGUI_YOUMUSTFIRSTLOADADATABASEBEFOREDEFAULTPARAMETERSCANBEC_STR "\x00"
    "\x00\x00\x00\x8E\x00\x04"
    MSG_AGUI_OK_STR "\x00\x00"
    "\x00\x00\x00\x8F\x00\x0A"
    MSG_AGUI_STANDUP_STR "\x00\x00"
    "\x00\x00\x00\x90\x00\x0A"
    MSG_AGUI_LAYDOWN_STR "\x00\x00"
    "\x00\x00\x00\x91\x00\x0A"
    MSG_AGUI_LOAD_STR "\x00\x00"
    "\x00\x00\x00\x92\x00\x0C"
    MSG_AGUI_APPEND_STR "\x00\x00"
    "\x00\x00\x00\x93\x00\x0C"
    MSG_AGUI_CREATE_STR "\x00\x00"
    "\x00\x00\x00\x94\x00\x0A"
    MSG_AGUI_EDIT_STR "\x00\x00"
    "\x00\x00\x00\x95\x00\x0A"
    MSG_AGUI_SAVE_STR "\x00\x00"
    "\x00\x00\x00\x96\x00\x0E"
    MSG_AGUI_DIRLIST_STR "\x00\x00"
    "\x00\x00\x00\x97\x00\x16"
    MSG_AGUI_DATAOPSIMPORTDLG_STR "\x00\x00"
    "\x00\x00\x00\x98\x00\x16"
    MSG_AGUI_DATAOPSIMPORTDXF_STR "\x00\x00"
    "\x00\x00\x00\x99\x00\x16"
    MSG_AGUI_DATAOPSIMPORTWDB_STR "\x00\x00"
    "\x00\x00\x00\x9A\x00\x1C"
    MSG_AGUI_DATAOPSMODULEINTERPDEM_STR "\x00"
    "\x00\x00\x00\x9B\x00\x1E"
    MSG_AGUI_DATAOPSMODULEEXTRACTDEM_STR "\x00\x00"
    "\x00\x00\x00\x9C\x00\x0E"
    MSG_AGUI_RENDERMODULE_STR "\x00"
    "\x00\x00\x00\x9D\x00\x1E"
    MSG_AGUI_ADATABASEANDPARAMETERFILE_STR "\x00"
    "\x00\x00\x00\x9E\x00\x16"
    MSG_AGUI_MODULECONTROLPANEL_STR "\x00\x00"
    "\x00\x00\x00\x9F\x00\x08"
    MSG_AGUI_VERSION_STR "\x00"
    "\x00\x00\x00\xA0\x00\x08"
    MSG_AGUI_OKAY_STR "\x00\x00"
    "\x00\x00\x00\xA1\x00\x0E"
    MSG_AGUI_EXTRASMODULE_STR "\x00"
    "\x00\x00\x00\xA2\x00\x36"
    MSG_AGUI_PUBLICSCREENSTILLHASVISITORSTRYCLOSINGAGAIN_STR "\x00\x00"
    "\x00\x00\x00\xA3\x00\x12"
    MSG_AGUI_CLOSEWARNCANCEL_STR "\x00"
    "\x00\x00\x00\xA4\x00\x1C"
    MSG_AGUI_QUITPROGRAMREYOUSURE_STR "\x00\x00"
    "\x00\x00\x00\xA5\x00\x0C"
    MSG_AGUI_WCSPROJECT_STR "\x00"
    "\x00\x00\x00\xA6\x00\x3C"
    MSG_AGUI_PROJECTPATHSHAVEBEENMODIFIEDSAVETHEMBEFORECLOSING_STR "\x00"
    "\x00\x00\x00\xA7\x00\x3A"
    MSG_AGUI_PARAMETERSHAVEBEENMODIFIEDSAVETHEMBEFORECLOSING_STR "\x00\x00"
    "\x00\x00\x00\xA8\x00\x34"
    MSG_AGUI_DATABASEHASBEENMODIFIEDSAVEITBEFORECLOSING_STR "\x00"
    "\x00\x00\x00\xA9\x00\x08"
    MSG_AGUI_MESSAGE_STR "\x00"
    "\x00\x00\x00\xAA\x00\x22"
    MSG_AGUI_NOTYETIMPLEMENTEDTAYTUNED_STR "\x00\x00"
    "\x00\x00\x00\xAB\x00\x0E"
    MSG_AGUI_KEEPCHANGES_STR "\x00"
    "\x00\x00\x00\xAC\x00\x0C"
    MSG_AGUI_KEEPCANCEL_STR "\x00"
    "\x00\x00\x00\xAD\x00\x3E"
    MSG_AGUI_SORRYOUMUSTFIRSTLOAD338NBEFOREUSINGTHISFEATURE_STR "\x00\x00"
    "\x00\x00\x00\xAE\x00\x32"
    MSG_AGUI_FILEALREADYEXISTSOYOUWISHTOOVERWRITEIT_STR "\x00"
    "\x00\x00\x00\xAF\x00\x0E"
    MSG_AGUI_INPUTREQUEST_STR "\x00"
    "\x00\x00\x00\xB0\x00\x0A"
    MSG_AGUI_CANCEL_STR "\x00\x00"
    "\x00\x00\x00\xB1\x00\x12"
    MSG_AGUI_LOGSTATUSMODULE_STR "\x00"
    "\x00\x00\x00\xB2\x00\x1E"
    MSG_AGUI_CANTOPENLOGSTATUSWINDOW_STR "\x00"
    "\x00\x00\x00\xB3\x00\x08"
    MSG_AGUI_CLEAR_STR "\x00"
    "\x00\x00\x00\xB4\x00\x08"
    MSG_AGUI_HIDE_STR "\x00\x00"
    "\x00\x00\x00\xB5\x00\x08"
    MSG_AGUI_CLOSE_STR "\x00"
    "\x00\x00\x00\xB6\x00\x0C"
    MSG_AGUI_LOGWINDOW_STR "\x00\x00"
    "\x00\x00\x00\xB7\x00\x14"
    MSG_AGUI_LOGWINDOWOPENED_STR "\x00\x00"
    "\x00\x00\x00\xB8\x00\x06"
    MSG_AGUI_INFO_STR "\x00\x00"
    "\x00\x00\x00\xB9\x00\x08"
    MSG_AGUI_TIME_STR "\x00"
    "\x00\x00\x00\xBA\x00\x08"
    MSG_AGUI_DATE_STR "\x00"
    "\x00\x00\x00\xBB\x00\x0A"
    MSG_AGUI_MEMORY_STR "\x00"
    "\x00\x00\x00\xBC\x00\x0E"
    MSG_AGUI_AVAILABLE_STR "\x00\x00"
    "\x00\x00\x00\xBD\x00\x0C"
    MSG_AGUI_LARGEST_STR "\x00\x00"
    "\x00\x00\x00\xBE\x00\x08"
    MSG_AGUI_CHIP_STR "\x00\x00"
    "\x00\x00\x00\xBF\x00\x08"
    MSG_AGUI_FAST_STR "\x00\x00"
    "\x00\x00\x00\xC0\x00\x0E"
    MSG_AGUI_TOPOMAPS_STR "\x00\x00"
    "\x00\x00\x00\xC1\x00\x08"
    MSG_AGUI_INTER_STR "\x00"
    "\x00\x00\x00\xC2\x00\x06"
    MSG_AGUI_MAP_STR "\x00"
    "\x00\x00\x00\xC3\x00\x0E"
    MSG_AGUI_AREXXPORT_STR "\x00"
    "\x00\x00\x00\xC4\x00\x0C"
    MSG_AGUI_DATABASE_STR "\x00"
    "\x00\x00\x00\xC5\x00\x0C"
    MSG_AGUI_PARFILE_STR "\x00"
    "\x00\x00\x00\xC6\x00\x0E"
    MSG_AGUI_SCREENMODE_STR "\x00"
    "\x00\x00\x00\xC7\x00\x08"
    MSG_AGUI_FLUSH_STR "\x00"
    "\x00\x00\x00\xC8\x00\x12"
    MSG_AGUI_WCSSCREENMODE_STR "\x00\x00"
    "\x00\x00\x00\xC9\x00\x10"
    MSG_AGUI_DATABASEMODULE_STR "\x00"
    "\x00\x00\x00\xCA\x00\x1A"
    MSG_AGUI_DATABASEMODULEAPPEND_STR "\x00\x00"
    "\x00\x00\x00\xCB\x00\x0C"
    MSG_AGUI_ADATABASE_STR "\x00\x00"
    "\x00\x00\x00\xCC\x00\x16"
    MSG_AGUI_DATABASEMODULESAVE_STR "\x00"
    "\x00\x00\x00\xCD\x00\x10"
    MSG_AGUI_DATAOPSMODULE_STR "\x00\x00"
    "\x00\x00\x00\xCE\x00\x10"
    MSG_AGUI_EXTRACTDEM_STR "\x00"
    "\x00\x00\x00\xCF\x00\x10"
    MSG_AGUI_CONVERTDEM_STR "\x00"
    "\x00\x00\x00\xD0\x00\x10"
    MSG_AGUI_INTERPDEM_STR "\x00\x00"
    "\x00\x00\x00\xD1\x00\x10"
    MSG_AGUI_IMPORTDLG_STR "\x00\x00"
    "\x00\x00\x00\xD2\x00\x0E"
    MSG_AGUI_IMPORTDXF_STR "\x00"
    "\x00\x00\x00\xD3\x00\x10"
    MSG_AGUI_IMPORTWDB_STR "\x00\x00"
    "\x00\x00\x00\xD4\x00\x0E"
    MSG_AGUI_EXPORTLW_STR "\x00"
    "\x00\x00\x00\xD5\x00\x10"
    MSG_AGUI_MOTIONIO_STR "\x00\x00"
    "\x00\x00\x00\xD6\x00\x0C"
    MSG_AGUI_STATUSLOG_STR "\x00\x00"
    "\x00\x00\x00\xD7\x00\x06"
    MSG_AGUI_ERR_STR "\x00\x00"
    "\x00\x00\x00\xD8\x00\x06"
    MSG_AGUI_WNG_STR "\x00\x00"
    "\x00\x00\x00\xD9\x00\x06"
    MSG_AGUI_MSG_STR "\x00\x00"
    "\x00\x00\x00\xDA\x00\x06"
    MSG_AGUI_DTA_STR "\x00\x00"
    "\x00\x00\x00\xDB\x00\x08"
    MSG_AGUI_PREV_STR "\x00\x00"
    "\x00\x00\x00\xDC\x00\x08"
    MSG_AGUI_NEXT_STR "\x00\x00"
    "\x00\x00\x00\xDD\x00\x0A"
    MSG_AGUI_ALL_STR "\x00\x00"
    "\x00\x00\x00\xDE\x00\x10"
    MSG_AGUI_KEYSEXIST_STR "\x00"
    "\x00\x00\x00\xDF\x00\x0A"
    MSG_AGUI_ALL0_STR "\x00"
    "\x00\x00\x00\xE0\x00\x0E"
    MSG_AGUI_NOOTHERKEYS_STR "\x00"
    "\x00\x00\x00\xE1\x00\x0A"
    MSG_AGUI_NONE_STR "\x00\x00"
    "\x00\x00\x00\xE2\x00\x04"
    MSG_AGUI_USE_STR "\x00"
    "\x00\x00\x00\xE3\x00\x10"
    MSG_AGUI_LOADMOTION_STR "\x00\x00"
    "\x00\x00\x00\xE4\x00\x10"
    MSG_AGUI_SAVEMOTION_STR "\x00\x00"
    "\x00\x00\x00\xE5\x00\x0E"
    MSG_AGUI_LOADCOLOR_STR "\x00"
    "\x00\x00\x00\xE6\x00\x0E"
    MSG_AGUI_SAVECOLOR_STR "\x00"
    "\x00\x00\x00\xE7\x00\x0C"
    MSG_AGUI_LOADECO_STR "\x00"
    "\x00\x00\x00\xE8\x00\x0C"
    MSG_AGUI_SAVEECO_STR "\x00"
    "\x00\x00\x00\xE9\x00\x12"
    MSG_AGUI_LOADSETTINGS_STR "\x00\x00"
    "\x00\x00\x00\xEA\x00\x12"
    MSG_AGUI_SAVESETTINGS_STR "\x00\x00"
    "\x00\x00\x00\xEB\x00\x14"
    MSG_BITMAPS_IFFFILEPATHNAME_STR "\x00\x00"
    "\x00\x00\x00\xEC\x00\x24"
    MSG_BITMAPS_FILEALREADYEXISTSVERWRITEIT_STR "\x00\x00"
    "\x00\x00\x00\xED\x00\x0A"
    MSG_BITMAPS_OKCANCEL_STR "\x00"
    "\x00\x00\x00\xEE\x00\x38"
    MSG_BITMAPS_CANTOPENIMAGEFILEFOROUTPUTPERATIONTERMINATED_STR "\x00"
    "\x00\x00\x00\xEF\x00\x04"
    MSG_BITMAPS_OK_STR "\x00\x00"
    "\x00\x00\x00\xF0\x00\x0E"
    MSG_BITMAPS_SAVINGIMAGE_STR "\x00\x00"
    "\x00\x00\x00\xF1\x00\x04"
    MSG_BITMAPS_YES_STR "\x00"
    "\x00\x00\x00\xF2\x00\x04"
    MSG_BITMAPS_NO_STR "\x00\x00"
    "\x00\x00\x00\xF3\x00\x2A"
    MSG_BITMAPS_ERRORSAVINGIMAGEPERATIONTERMINATED_STR "\x00"
    "\x00\x00\x00\xF4\x00\x0E"
    MSG_BITMAPS_LOADINGIMAGE_STR "\x00"
    "\x00\x00\x00\xF5\x00\x12"
    MSG_BITMAPS_WRONGIMAGESIZE_STR "\x00\x00"
    "\x00\x00\x00\xF6\x00\x12"
    MSG_BITMAPS_WRONGIMAGEDEPTH_STR "\x00"
    "\x00\x00\x00\xF7\x00\x0C"
    MSG_BITMAPS_BACKGROUND_STR "\x00\x00"
    "\x00\x00\x00\xF8\x00\x0E"
    MSG_BITMAPS_RENDERMODULE_STR "\x00"
    "\x00\x00\x00\xF9\x00\x2E"
    MSG_BITMAPS_ERRORLOADINGZBUFFERPERATIONTERMINATED_STR "\x00"
    "\x00\x00\x00\xFA\x00\x36"
    MSG_BITMAPS_OUTOFMEMORYMERGINGZBUFFERPERATIONTERMINATED_STR "\x00"
    "\x00\x00\x00\xFB\x00\x3E"
    MSG_BITMAPS_ERROROPENINGZBUFFERFILEFORINPUTPERATIONTERMINATED_STR "\x00\x00"
    "\x00\x00\x00\xFC\x00\x58"
    MSG_BITMAPS_ERRORREADINGZBUFFERFILEOTSINGLEPRECISIONFLOATINGPOI_STR "\x00"
    "\x00\x00\x00\xFD\x00\x42"
    MSG_BITMAPS_ERRORREADINGZBUFFERFILEOZBODCHUNKPERATIONTERMINATED_STR "\x00"
    "\x00\x00\x00\xFE\x00\x42"
    MSG_BITMAPS_ERRORREADINGZBUFFERFILEOZBUFCHUNKPERATIONTERMINATED_STR "\x00"
    "\x00\x00\x00\xFF\x00\x40"
    MSG_BITMAPS_ERRORREADINGZBUFFERFILERONGSIZEPERATIONTERMINATED_STR "\x00\x00"
    "\x00\x00\x01\x00\x00\x36"
    MSG_BITMAPS_ERRORLOADINGBACKGROUNDIMAGEPERATIONTERMINATED_STR "\x00"
    "\x00\x00\x01\x01\x00\x38"
    MSG_BITMAPS_OUTOFMEMORYMERGINGBACKGROUNDPERATIONTERMINATED_STR "\x00"
    "\x00\x00\x01\x02\x00\x40"
    MSG_BITMAPS_ERROROPENINGBACKGROUNDFILEFORINPUTPERATIONTERMINATE_STR "\x00\x00"
    "\x00\x00\x01\x03\x00\x42"
    MSG_BITMAPS_ERRORREADINGBACKGROUNDFILERONGSIZEPERATIONTERMINATE_STR "\x00\x00"
    "\x00\x00\x01\x04\x00\x44"
    MSG_BITMAPS_ERRORREADINGBACKGROUNDFILEOBODYCHUNKPERATIONTERMINA_STR "\x00"
    "\x00\x00\x01\x05\x00\x44"
    MSG_BITMAPS_ERRORREADINGBACKGROUNDFILEOBMHDCHUNKPERATIONTERMINA_STR "\x00"
    "\x00\x00\x01\x06\x00\x48"
    MSG_BITMAPS_ERRORREADINGBACKGROUNDFILEOMPRESSIONERRORPERATIONTE_STR "\x00"
};

#endif /* CATCOMP_BLOCK */


/****************************************************************************/



#endif /* WCS_STRINGS_H */

