#ifndef WCS_STRINGS_H
#define WCS_STRINGS_H 1

/* Locale Catalog Source File
 *
 * Automatically created by SimpleCat V3
 * Do NOT edit by hand!
 *
 * SimpleCat ©1992-2013 Guido Mersmann
 *
 */



/****************************************************************************/


#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif

#ifdef CATCOMP_ARRAY
#undef CATCOMP_NUMBERS
#undef CATCOMP_STRINGS
#define CATCOMP_NUMBERS
#define CATCOMP_STRINGS
#endif

#ifdef CATCOMP_BLOCK
#undef CATCOMP_STRINGS
#define CATCOMP_STRINGS
#endif



/****************************************************************************/


#ifdef CATCOMP_NUMBERS

#define MSG_MENU_PROJECT 0
#define MSG_MENU_PR_NEW 1
#define MSG_MENU_PR_EDIT 2
#define MSG_MENU_PR_OPEN 3
#define MSG_MENU_PR_SAVE 4
#define MSG_MENU_PR_SAVEAS 5
#define MSG_MENU_PR_LOADCONFIG 6
#define MSG_MENU_PR_SAVECONFIG 7
#define MSG_MENU_PR_SAVESCREEN 8
#define MSG_MENU_PR_INFO 9
#define MSG_MENU_PR_VERSION 10
#define MSG_MENU_PR_CREDITS 11
#define MSG_MENU_PR_LOG 12
#define MSG_MENU_PR_QUIT 13
#define MSG_MENU_PR_ICONIFY 14
#define MSG_MENU_MODULES 15
#define MSG_MENU_MOD_DATABASE 16
#define MSG_MENU_MOD_DATAOPS 17
#define MSG_MENU_MOD_MAPVIEW 18
#define MSG_MENU_MOD_PARAMETERS 19
#define MSG_MENU_MOD_RENDER 20
#define MSG_MENU_MOD_MOTIONEDITOR 21
#define MSG_MENU_MOD_COLOREDITOR 22
#define MSG_MENU_MOD_ECOSYSEDITOR 23
#define MSG_MENU_PREFS 24
#define MSG_MENU_PREF_PREFERENCES 25
#define MSG_MENU_PREF_SCREENMODE 26
#define MSG_MENU_PARAMETERS 27
#define MSG_MENU_PAR_LOADALL 28
#define MSG_MENU_PAR_SAVEALL 29
#define MSG_MENU_PAR_FREEZE 30
#define MSG_MENU_PAR_RESTORE 31
#define MSG_TYPENAME_WATER 32
#define MSG_TYPENAME_SNOW 33
#define MSG_TYPENAME_ROCK 34
#define MSG_TYPENAME_GROUND 35
#define MSG_TYPENAME_CONIFER 36
#define MSG_TYPENAME_DECID 37
#define MSG_TYPENAME_LOWVEG 38
#define MSG_TYPENAME_SNAG 39
#define MSG_TYPENAME_STUMP 40
#define MSG_VARNAME_CAMERAALTITUDE 41
#define MSG_VARNAME_CAMERALATITUDE 42
#define MSG_VARNAME_CAMERALONGITUDE 43
#define MSG_VARNAME_FOCUSALTITUDE 44
#define MSG_VARNAME_FOCUSLATITUDE 45
#define MSG_VARNAME_FOCUSLONGITUDE 46
#define MSG_VARNAME_CENTERX 47
#define MSG_VARNAME_CENTERY 48
#define MSG_VARNAME_BANK 49
#define MSG_VARNAME_EARTHROTATION 50
#define MSG_VARNAME_SCALE 51
#define MSG_VARNAME_VIEWARC 52
#define MSG_VARNAME_FLATTENING 53
#define MSG_VARNAME_DATUM 54
#define MSG_VARNAME_VERTICALEXAG 55
#define MSG_VARNAME_SUNLIGHTLAT 56
#define MSG_VARNAME_SUNLIGHTLON 57
#define MSG_VARNAME_HORIZONLINE 58
#define MSG_VARNAME_HORIZONPOINT 59
#define MSG_VARNAME_HORIZONSTRETCH 60
#define MSG_VARNAME_HAZESTART 61
#define MSG_VARNAME_HAZERANGE 62
#define MSG_VARNAME_SHADEFACTOR 63
#define MSG_VARNAME_FOGNONE 64
#define MSG_VARNAME_FOGFULL 65
#define MSG_VARNAME_ZMINIMUM 66
#define MSG_VARNAME_SUNLAT 67
#define MSG_VARNAME_SUNLON 68
#define MSG_VARNAME_SUNSIZE 69
#define MSG_VARNAME_MOONLAT 70
#define MSG_VARNAME_MOONLON 71
#define MSG_VARNAME_MOONSIZE 72
#define MSG_VARNAME_REFLECTION 73
#define MSG_STDMESG_OUTOFMEMORY 74
#define MSG_STDMESG_OPENFILEFAILED 75
#define MSG_STDMESG_READFILEFAILED 76
#define MSG_STDMESG_WRITINGTOFILEFAILED 77
#define MSG_STDMESG_WRONGFILETYPE 78
#define MSG_STDMESG_ILLEGALINSTRUCTION 79
#define MSG_STDMESG_ILLEGALVALUE 80
#define MSG_STDMESG_FILENOTLOADED 81
#define MSG_STDMESG_MODULENOTIMPLEMENTED 82
#define MSG_STDMESG_GUINOTIMPLEMENTED 83
#define MSG_STDMESG_PARAMETERFILELOADED 84
#define MSG_STDMESG_PARAMETERFILESAVED 85
#define MSG_STDMESG_DATABASEFILELOADED 86
#define MSG_STDMESG_DATABASEFILESAVED 87
#define MSG_STDMESG_DEMFILELOADED 88
#define MSG_STDMESG_DEMFILESAVED 89
#define MSG_STDMESG_VECTORFILELOADED 90
#define MSG_STDMESG_VECTORFILESAVED 91
#define MSG_STDMESG_IMAGEFILELOADED 92
#define MSG_STDMESG_IMAGEFILESAVED 93
#define MSG_STDMESG_COLORMAPFILELOADED 94
#define MSG_STDMESG_COLORMAPFILESAVED 95
#define MSG_STDMESG_ENABLE_SOFT_OUTLINE_STYLE 96
#define MSG_STDMESG_MAPPINGMODULE 97
#define MSG_STDMESG_DIRECTORYNOTFOUND 98
#define MSG_STDMESG_OPENWINDOWFAILED 99
#define MSG_STDMESG_EMPTY 100
#define MSG_STDMESG_INCORRECTFILESIZE 101
#define MSG_STDMESG_INCORRECTFILEVERSION 102
#define MSG_STDMESG_RELATIVEELEVATIONFILESAVED 103
#define MSG_STDMESG_VECTOROBJECTSLOADED 104
#define MSG_STDMESG_PROJECTFILELOADED 105
#define MSG_STDMESG_PROJECTFILESAVED 106
#define MSG_STDMESG_DIRECTORYLISTLOADED 107
#define MSG_STDMESG_RENDERTIMEFORFRAME 108
#define MSG_STDMESG_RENDERTIMEFORANIM 109
#define MSG_SCNRMODGUI_NONE 110
#define MSG_SCNRMODGUI_TEXT 111
#define MSG_SCNRMODGUI_STANDARD 112
#define MSG_SCNRMODGUI_MAX 113
#define MSG_SCNRMODGUI_VIDEO 114
#define MSG_SCNRMODGUI_WORLDCONSTRUCTIONSETSCREENMODE 115
#define MSG_SCNRMODGUI_DISPLAYMODE 116
#define MSG_SCNRMODGUI_MODEINFORMATION 117
#define MSG_SCNRMODGUI_MODEESUTOCANNATTRIBUTESN 118
#define MSG_SCNRMODGUI_SAVE 119
#define MSG_SCNRMODGUI_USE 120
#define MSG_SCNRMODGUI_EXIT 121
#define MSG_SCNRMODGUI_MODE0XESXXUTOXCANNSNATTRIBUTES 122
#define MSG_SCNRMODGUI_LACED 123
#define MSG_SCNRMODGUI_GENLOCKABLE 124
#define MSG_SCNRMODGUI_DRAGGABLE 125
#define MSG_SCNRMODGUI_OVERSCAN 126
#define MSG_SCNRMODGUI_WIDTH 127
#define MSG_SCNRMODGUI_HEIGHT 128

#define CATCOMP_LASTID 128

#endif /* CATCOMP_NUMBERS */


/****************************************************************************/


#ifdef CATCOMP_STRINGS

#define MSG_MENU_PROJECT_STR "Project"
#define MSG_MENU_PR_NEW_STR "New..."
#define MSG_MENU_PR_EDIT_STR "Edit..."
#define MSG_MENU_PR_OPEN_STR "Open..."
#define MSG_MENU_PR_SAVE_STR "Save"
#define MSG_MENU_PR_SAVEAS_STR "Save As..."
#define MSG_MENU_PR_LOADCONFIG_STR "Load Config"
#define MSG_MENU_PR_SAVECONFIG_STR "Save Config"
#define MSG_MENU_PR_SAVESCREEN_STR "Save Screen..."
#define MSG_MENU_PR_INFO_STR "Info..."
#define MSG_MENU_PR_VERSION_STR "Version..."
#define MSG_MENU_PR_CREDITS_STR "Credits..."
#define MSG_MENU_PR_LOG_STR "Log..."
#define MSG_MENU_PR_QUIT_STR "Quit..."
#define MSG_MENU_PR_ICONIFY_STR "Iconify..."
#define MSG_MENU_MODULES_STR "Modules"
#define MSG_MENU_MOD_DATABASE_STR "DataBase"
#define MSG_MENU_MOD_DATAOPS_STR "Data Ops"
#define MSG_MENU_MOD_MAPVIEW_STR "Map View"
#define MSG_MENU_MOD_PARAMETERS_STR "Parameters"
#define MSG_MENU_MOD_RENDER_STR "Render"
#define MSG_MENU_MOD_MOTIONEDITOR_STR "Motion Editor"
#define MSG_MENU_MOD_COLOREDITOR_STR "Color Editor"
#define MSG_MENU_MOD_ECOSYSEDITOR_STR "Ecosys Editor"
#define MSG_MENU_PREFS_STR "Preferences"
#define MSG_MENU_PREF_PREFERENCES_STR "Preferences..."
#define MSG_MENU_PREF_SCREENMODE_STR "Screen Mode..."
#define MSG_MENU_PARAMETERS_STR "Parameters"
#define MSG_MENU_PAR_LOADALL_STR "Load All..."
#define MSG_MENU_PAR_SAVEALL_STR "Save All..."
#define MSG_MENU_PAR_FREEZE_STR "Freeze"
#define MSG_MENU_PAR_RESTORE_STR "Restore"
#define MSG_TYPENAME_WATER_STR "Water"
#define MSG_TYPENAME_SNOW_STR "Snow"
#define MSG_TYPENAME_ROCK_STR "Rock"
#define MSG_TYPENAME_GROUND_STR "Ground"
#define MSG_TYPENAME_CONIFER_STR "Conifer"
#define MSG_TYPENAME_DECID_STR "Decid"
#define MSG_TYPENAME_LOWVEG_STR "Low Veg"
#define MSG_TYPENAME_SNAG_STR "Snag"
#define MSG_TYPENAME_STUMP_STR "Stump"
#define MSG_VARNAME_CAMERAALTITUDE_STR "Camera Altitude"
#define MSG_VARNAME_CAMERALATITUDE_STR "Camera Latitude"
#define MSG_VARNAME_CAMERALONGITUDE_STR "Camera Longitude"
#define MSG_VARNAME_FOCUSALTITUDE_STR "Focus Altitude"
#define MSG_VARNAME_FOCUSLATITUDE_STR "Focus Latitude"
#define MSG_VARNAME_FOCUSLONGITUDE_STR "Focus Longitude"
#define MSG_VARNAME_CENTERX_STR "Center X"
#define MSG_VARNAME_CENTERY_STR "Center Y"
#define MSG_VARNAME_BANK_STR "Bank"
#define MSG_VARNAME_EARTHROTATION_STR "Earth Rotation"
#define MSG_VARNAME_SCALE_STR "Scale"
#define MSG_VARNAME_VIEWARC_STR "View Arc"
#define MSG_VARNAME_FLATTENING_STR "Flattening"
#define MSG_VARNAME_DATUM_STR "Datum"
#define MSG_VARNAME_VERTICALEXAG_STR "Vertical Exag"
#define MSG_VARNAME_SUNLIGHTLAT_STR "Sun Light Lat"
#define MSG_VARNAME_SUNLIGHTLON_STR "Sun Light Lon"
#define MSG_VARNAME_HORIZONLINE_STR "Horizon Line"
#define MSG_VARNAME_HORIZONPOINT_STR "Horizon Point"
#define MSG_VARNAME_HORIZONSTRETCH_STR "Horizon Stretch"
#define MSG_VARNAME_HAZESTART_STR "Haze Start"
#define MSG_VARNAME_HAZERANGE_STR "Haze Range"
#define MSG_VARNAME_SHADEFACTOR_STR "Shade Factor"
#define MSG_VARNAME_FOGNONE_STR "Fog None"
#define MSG_VARNAME_FOGFULL_STR "Fog Full"
#define MSG_VARNAME_ZMINIMUM_STR "Z Minimum"
#define MSG_VARNAME_SUNLAT_STR "Sun Lat"
#define MSG_VARNAME_SUNLON_STR "Sun Lon"
#define MSG_VARNAME_SUNSIZE_STR "Sun Size"
#define MSG_VARNAME_MOONLAT_STR "Moon Lat"
#define MSG_VARNAME_MOONLON_STR "Moon Lon"
#define MSG_VARNAME_MOONSIZE_STR "Moon Size"
#define MSG_VARNAME_REFLECTION_STR "Reflection %"
#define MSG_STDMESG_OUTOFMEMORY_STR " Out of memory!"
#define MSG_STDMESG_OPENFILEFAILED_STR " Open file failed!"
#define MSG_STDMESG_READFILEFAILED_STR " Read file failed!"
#define MSG_STDMESG_WRITINGTOFILEFAILED_STR " Writing to file failed!"
#define MSG_STDMESG_WRONGFILETYPE_STR " Wrong file type!"
#define MSG_STDMESG_ILLEGALINSTRUCTION_STR " Illegal instruction!"
#define MSG_STDMESG_ILLEGALVALUE_STR " Illegal value!"
#define MSG_STDMESG_FILENOTLOADED_STR " File not loaded!"
#define MSG_STDMESG_MODULENOTIMPLEMENTED_STR " Module not implemented."
#define MSG_STDMESG_GUINOTIMPLEMENTED_STR " GUI not implemented."
#define MSG_STDMESG_PARAMETERFILELOADED_STR " Parameter file loaded."
#define MSG_STDMESG_PARAMETERFILESAVED_STR " Parameter file saved."
#define MSG_STDMESG_DATABASEFILELOADED_STR " Database file loaded."
#define MSG_STDMESG_DATABASEFILESAVED_STR " Database file saved."
#define MSG_STDMESG_DEMFILELOADED_STR " DEM file loaded."
#define MSG_STDMESG_DEMFILESAVED_STR " DEM file saved."
#define MSG_STDMESG_VECTORFILELOADED_STR " Vector file loaded."
#define MSG_STDMESG_VECTORFILESAVED_STR " Vector file saved."
#define MSG_STDMESG_IMAGEFILELOADED_STR " Image file loaded."
#define MSG_STDMESG_IMAGEFILESAVED_STR " Image file saved."
#define MSG_STDMESG_COLORMAPFILELOADED_STR " Color Map file loaded."
#define MSG_STDMESG_COLORMAPFILESAVED_STR " Color Map file saved."
#define MSG_STDMESG_ENABLE_SOFT_OUTLINE_STYLE_STR "\33t"
#define MSG_STDMESG_MAPPINGMODULE_STR " Mapping Module."
#define MSG_STDMESG_DIRECTORYNOTFOUND_STR " Directory not found!"
#define MSG_STDMESG_OPENWINDOWFAILED_STR " Open window failed!"
#define MSG_STDMESG_EMPTY_STR ""
#define MSG_STDMESG_INCORRECTFILESIZE_STR " Incorrect file size!"
#define MSG_STDMESG_INCORRECTFILEVERSION_STR " Incorrect file version!"
#define MSG_STDMESG_RELATIVEELEVATIONFILESAVED_STR " Relative Elevation File Saved."
#define MSG_STDMESG_VECTOROBJECTSLOADED_STR " Vector objects loaded."
#define MSG_STDMESG_PROJECTFILELOADED_STR " Project file loaded."
#define MSG_STDMESG_PROJECTFILESAVED_STR " Project file saved."
#define MSG_STDMESG_DIRECTORYLISTLOADED_STR " Directory List loaded"
#define MSG_STDMESG_RENDERTIMEFORFRAME_STR " Render time for frame"
#define MSG_STDMESG_RENDERTIMEFORANIM_STR " Render time for anim,"
#define MSG_SCNRMODGUI_NONE_STR "None"
#define MSG_SCNRMODGUI_TEXT_STR "Text"
#define MSG_SCNRMODGUI_STANDARD_STR "Standard"
#define MSG_SCNRMODGUI_MAX_STR "Max"
#define MSG_SCNRMODGUI_VIDEO_STR "Video"
#define MSG_SCNRMODGUI_WORLDCONSTRUCTIONSETSCREENMODE_STR "World Construction Set Screenmode"
#define MSG_SCNRMODGUI_DISPLAYMODE_STR "\33cDisplay Mode"
#define MSG_SCNRMODGUI_MODEINFORMATION_STR "\33cMode Information"
#define MSG_SCNRMODGUI_MODEESUTOCANNATTRIBUTESN_STR "Mode:           \nRes :                      \nAuto:            \nScan:                   \n\nAttributes\n\n\n"
#define MSG_SCNRMODGUI_SAVE_STR "\33cSave"
#define MSG_SCNRMODGUI_USE_STR "\33cUse"
#define MSG_SCNRMODGUI_EXIT_STR "\33cExit"
#define MSG_SCNRMODGUI_MODE0XESXXUTOXCANNSNATTRIBUTES_STR "Mode: 0x%08lx\nRes : %dx%d - %dx%d\nAuto: %dx%d\nScan: %dns\n\nAttributes\n"
#define MSG_SCNRMODGUI_LACED_STR "Laced\x20"
#define MSG_SCNRMODGUI_GENLOCKABLE_STR "Genlockable\x20"
#define MSG_SCNRMODGUI_DRAGGABLE_STR "Draggable\x20"
#define MSG_SCNRMODGUI_OVERSCAN_STR "Overscan:\x20"
#define MSG_SCNRMODGUI_WIDTH_STR "Width\x20"
#define MSG_SCNRMODGUI_HEIGHT_STR "Height\x20"

#endif /* CATCOMP_STRINGS */


/****************************************************************************/


#ifdef CATCOMP_BLOCK

const char CatCompBlock[] =
{
    "\x00\x00\x00\x00\x00\x08"
    MSG_MENU_PROJECT_STR "\x00"
    "\x00\x00\x00\x01\x00\x08"
    MSG_MENU_PR_NEW_STR "\x00\x00"
    "\x00\x00\x00\x02\x00\x08"
    MSG_MENU_PR_EDIT_STR "\x00"
    "\x00\x00\x00\x03\x00\x08"
    MSG_MENU_PR_OPEN_STR "\x00"
    "\x00\x00\x00\x04\x00\x06"
    MSG_MENU_PR_SAVE_STR "\x00\x00"
    "\x00\x00\x00\x05\x00\x0C"
    MSG_MENU_PR_SAVEAS_STR "\x00\x00"
    "\x00\x00\x00\x06\x00\x0C"
    MSG_MENU_PR_LOADCONFIG_STR "\x00"
    "\x00\x00\x00\x07\x00\x0C"
    MSG_MENU_PR_SAVECONFIG_STR "\x00"
    "\x00\x00\x00\x08\x00\x10"
    MSG_MENU_PR_SAVESCREEN_STR "\x00\x00"
    "\x00\x00\x00\x09\x00\x08"
    MSG_MENU_PR_INFO_STR "\x00"
    "\x00\x00\x00\x0A\x00\x0C"
    MSG_MENU_PR_VERSION_STR "\x00\x00"
    "\x00\x00\x00\x0B\x00\x0C"
    MSG_MENU_PR_CREDITS_STR "\x00\x00"
    "\x00\x00\x00\x0C\x00\x08"
    MSG_MENU_PR_LOG_STR "\x00\x00"
    "\x00\x00\x00\x0D\x00\x08"
    MSG_MENU_PR_QUIT_STR "\x00"
    "\x00\x00\x00\x0E\x00\x0C"
    MSG_MENU_PR_ICONIFY_STR "\x00\x00"
    "\x00\x00\x00\x0F\x00\x08"
    MSG_MENU_MODULES_STR "\x00"
    "\x00\x00\x00\x10\x00\x0A"
    MSG_MENU_MOD_DATABASE_STR "\x00\x00"
    "\x00\x00\x00\x11\x00\x0A"
    MSG_MENU_MOD_DATAOPS_STR "\x00\x00"
    "\x00\x00\x00\x12\x00\x0A"
    MSG_MENU_MOD_MAPVIEW_STR "\x00\x00"
    "\x00\x00\x00\x13\x00\x0C"
    MSG_MENU_MOD_PARAMETERS_STR "\x00\x00"
    "\x00\x00\x00\x14\x00\x08"
    MSG_MENU_MOD_RENDER_STR "\x00\x00"
    "\x00\x00\x00\x15\x00\x0E"
    MSG_MENU_MOD_MOTIONEDITOR_STR "\x00"
    "\x00\x00\x00\x16\x00\x0E"
    MSG_MENU_MOD_COLOREDITOR_STR "\x00\x00"
    "\x00\x00\x00\x17\x00\x0E"
    MSG_MENU_MOD_ECOSYSEDITOR_STR "\x00"
    "\x00\x00\x00\x18\x00\x0C"
    MSG_MENU_PREFS_STR "\x00"
    "\x00\x00\x00\x19\x00\x10"
    MSG_MENU_PREF_PREFERENCES_STR "\x00\x00"
    "\x00\x00\x00\x1A\x00\x10"
    MSG_MENU_PREF_SCREENMODE_STR "\x00\x00"
    "\x00\x00\x00\x1B\x00\x0C"
    MSG_MENU_PARAMETERS_STR "\x00\x00"
    "\x00\x00\x00\x1C\x00\x0C"
    MSG_MENU_PAR_LOADALL_STR "\x00"
    "\x00\x00\x00\x1D\x00\x0C"
    MSG_MENU_PAR_SAVEALL_STR "\x00"
    "\x00\x00\x00\x1E\x00\x08"
    MSG_MENU_PAR_FREEZE_STR "\x00\x00"
    "\x00\x00\x00\x1F\x00\x08"
    MSG_MENU_PAR_RESTORE_STR "\x00"
    "\x00\x00\x00\x20\x00\x06"
    MSG_TYPENAME_WATER_STR "\x00"
    "\x00\x00\x00\x21\x00\x06"
    MSG_TYPENAME_SNOW_STR "\x00\x00"
    "\x00\x00\x00\x22\x00\x06"
    MSG_TYPENAME_ROCK_STR "\x00\x00"
    "\x00\x00\x00\x23\x00\x08"
    MSG_TYPENAME_GROUND_STR "\x00\x00"
    "\x00\x00\x00\x24\x00\x08"
    MSG_TYPENAME_CONIFER_STR "\x00"
    "\x00\x00\x00\x25\x00\x06"
    MSG_TYPENAME_DECID_STR "\x00"
    "\x00\x00\x00\x26\x00\x08"
    MSG_TYPENAME_LOWVEG_STR "\x00"
    "\x00\x00\x00\x27\x00\x06"
    MSG_TYPENAME_SNAG_STR "\x00\x00"
    "\x00\x00\x00\x28\x00\x06"
    MSG_TYPENAME_STUMP_STR "\x00"
    "\x00\x00\x00\x29\x00\x10"
    MSG_VARNAME_CAMERAALTITUDE_STR "\x00"
    "\x00\x00\x00\x2A\x00\x10"
    MSG_VARNAME_CAMERALATITUDE_STR "\x00"
    "\x00\x00\x00\x2B\x00\x12"
    MSG_VARNAME_CAMERALONGITUDE_STR "\x00\x00"
    "\x00\x00\x00\x2C\x00\x10"
    MSG_VARNAME_FOCUSALTITUDE_STR "\x00\x00"
    "\x00\x00\x00\x2D\x00\x10"
    MSG_VARNAME_FOCUSLATITUDE_STR "\x00\x00"
    "\x00\x00\x00\x2E\x00\x10"
    MSG_VARNAME_FOCUSLONGITUDE_STR "\x00"
    "\x00\x00\x00\x2F\x00\x0A"
    MSG_VARNAME_CENTERX_STR "\x00\x00"
    "\x00\x00\x00\x30\x00\x0A"
    MSG_VARNAME_CENTERY_STR "\x00\x00"
    "\x00\x00\x00\x31\x00\x06"
    MSG_VARNAME_BANK_STR "\x00\x00"
    "\x00\x00\x00\x32\x00\x10"
    MSG_VARNAME_EARTHROTATION_STR "\x00\x00"
    "\x00\x00\x00\x33\x00\x06"
    MSG_VARNAME_SCALE_STR "\x00"
    "\x00\x00\x00\x34\x00\x0A"
    MSG_VARNAME_VIEWARC_STR "\x00\x00"
    "\x00\x00\x00\x35\x00\x0C"
    MSG_VARNAME_FLATTENING_STR "\x00\x00"
    "\x00\x00\x00\x36\x00\x06"
    MSG_VARNAME_DATUM_STR "\x00"
    "\x00\x00\x00\x37\x00\x0E"
    MSG_VARNAME_VERTICALEXAG_STR "\x00"
    "\x00\x00\x00\x38\x00\x0E"
    MSG_VARNAME_SUNLIGHTLAT_STR "\x00"
    "\x00\x00\x00\x39\x00\x0E"
    MSG_VARNAME_SUNLIGHTLON_STR "\x00"
    "\x00\x00\x00\x3A\x00\x0E"
    MSG_VARNAME_HORIZONLINE_STR "\x00\x00"
    "\x00\x00\x00\x3B\x00\x0E"
    MSG_VARNAME_HORIZONPOINT_STR "\x00"
    "\x00\x00\x00\x3C\x00\x10"
    MSG_VARNAME_HORIZONSTRETCH_STR "\x00"
    "\x00\x00\x00\x3D\x00\x0C"
    MSG_VARNAME_HAZESTART_STR "\x00\x00"
    "\x00\x00\x00\x3E\x00\x0C"
    MSG_VARNAME_HAZERANGE_STR "\x00\x00"
    "\x00\x00\x00\x3F\x00\x0E"
    MSG_VARNAME_SHADEFACTOR_STR "\x00\x00"
    "\x00\x00\x00\x40\x00\x0A"
    MSG_VARNAME_FOGNONE_STR "\x00\x00"
    "\x00\x00\x00\x41\x00\x0A"
    MSG_VARNAME_FOGFULL_STR "\x00\x00"
    "\x00\x00\x00\x42\x00\x0A"
    MSG_VARNAME_ZMINIMUM_STR "\x00"
    "\x00\x00\x00\x43\x00\x08"
    MSG_VARNAME_SUNLAT_STR "\x00"
    "\x00\x00\x00\x44\x00\x08"
    MSG_VARNAME_SUNLON_STR "\x00"
    "\x00\x00\x00\x45\x00\x0A"
    MSG_VARNAME_SUNSIZE_STR "\x00\x00"
    "\x00\x00\x00\x46\x00\x0A"
    MSG_VARNAME_MOONLAT_STR "\x00\x00"
    "\x00\x00\x00\x47\x00\x0A"
    MSG_VARNAME_MOONLON_STR "\x00\x00"
    "\x00\x00\x00\x48\x00\x0A"
    MSG_VARNAME_MOONSIZE_STR "\x00"
    "\x00\x00\x00\x49\x00\x0E"
    MSG_VARNAME_REFLECTION_STR "\x00\x00"
    "\x00\x00\x00\x4A\x00\x10"
    MSG_STDMESG_OUTOFMEMORY_STR "\x00"
    "\x00\x00\x00\x4B\x00\x14"
    MSG_STDMESG_OPENFILEFAILED_STR "\x00\x00"
    "\x00\x00\x00\x4C\x00\x14"
    MSG_STDMESG_READFILEFAILED_STR "\x00\x00"
    "\x00\x00\x00\x4D\x00\x1A"
    MSG_STDMESG_WRITINGTOFILEFAILED_STR "\x00\x00"
    "\x00\x00\x00\x4E\x00\x12"
    MSG_STDMESG_WRONGFILETYPE_STR "\x00"
    "\x00\x00\x00\x4F\x00\x16"
    MSG_STDMESG_ILLEGALINSTRUCTION_STR "\x00"
    "\x00\x00\x00\x50\x00\x10"
    MSG_STDMESG_ILLEGALVALUE_STR "\x00"
    "\x00\x00\x00\x51\x00\x12"
    MSG_STDMESG_FILENOTLOADED_STR "\x00"
    "\x00\x00\x00\x52\x00\x1A"
    MSG_STDMESG_MODULENOTIMPLEMENTED_STR "\x00\x00"
    "\x00\x00\x00\x53\x00\x16"
    MSG_STDMESG_GUINOTIMPLEMENTED_STR "\x00"
    "\x00\x00\x00\x54\x00\x18"
    MSG_STDMESG_PARAMETERFILELOADED_STR "\x00"
    "\x00\x00\x00\x55\x00\x18"
    MSG_STDMESG_PARAMETERFILESAVED_STR "\x00\x00"
    "\x00\x00\x00\x56\x00\x18"
    MSG_STDMESG_DATABASEFILELOADED_STR "\x00\x00"
    "\x00\x00\x00\x57\x00\x16"
    MSG_STDMESG_DATABASEFILESAVED_STR "\x00"
    "\x00\x00\x00\x58\x00\x12"
    MSG_STDMESG_DEMFILELOADED_STR "\x00"
    "\x00\x00\x00\x59\x00\x12"
    MSG_STDMESG_DEMFILESAVED_STR "\x00\x00"
    "\x00\x00\x00\x5A\x00\x16"
    MSG_STDMESG_VECTORFILELOADED_STR "\x00\x00"
    "\x00\x00\x00\x5B\x00\x14"
    MSG_STDMESG_VECTORFILESAVED_STR "\x00"
    "\x00\x00\x00\x5C\x00\x14"
    MSG_STDMESG_IMAGEFILELOADED_STR "\x00"
    "\x00\x00\x00\x5D\x00\x14"
    MSG_STDMESG_IMAGEFILESAVED_STR "\x00\x00"
    "\x00\x00\x00\x5E\x00\x18"
    MSG_STDMESG_COLORMAPFILELOADED_STR "\x00"
    "\x00\x00\x00\x5F\x00\x18"
    MSG_STDMESG_COLORMAPFILESAVED_STR "\x00\x00"
    "\x00\x00\x00\x60\x00\x04"
    MSG_STDMESG_ENABLE_SOFT_OUTLINE_STYLE_STR "\x00\x00"
    "\x00\x00\x00\x61\x00\x12"
    MSG_STDMESG_MAPPINGMODULE_STR "\x00\x00"
    "\x00\x00\x00\x62\x00\x16"
    MSG_STDMESG_DIRECTORYNOTFOUND_STR "\x00"
    "\x00\x00\x00\x63\x00\x16"
    MSG_STDMESG_OPENWINDOWFAILED_STR "\x00\x00"
    "\x00\x00\x00\x64\x00\x02"
    MSG_STDMESG_EMPTY_STR "\x00\x00"
    "\x00\x00\x00\x65\x00\x16"
    MSG_STDMESG_INCORRECTFILESIZE_STR "\x00"
    "\x00\x00\x00\x66\x00\x1A"
    MSG_STDMESG_INCORRECTFILEVERSION_STR "\x00\x00"
    "\x00\x00\x00\x67\x00\x20"
    MSG_STDMESG_RELATIVEELEVATIONFILESAVED_STR "\x00"
    "\x00\x00\x00\x68\x00\x18"
    MSG_STDMESG_VECTOROBJECTSLOADED_STR "\x00"
    "\x00\x00\x00\x69\x00\x16"
    MSG_STDMESG_PROJECTFILELOADED_STR "\x00"
    "\x00\x00\x00\x6A\x00\x16"
    MSG_STDMESG_PROJECTFILESAVED_STR "\x00\x00"
    "\x00\x00\x00\x6B\x00\x18"
    MSG_STDMESG_DIRECTORYLISTLOADED_STR "\x00\x00"
    "\x00\x00\x00\x6C\x00\x18"
    MSG_STDMESG_RENDERTIMEFORFRAME_STR "\x00\x00"
    "\x00\x00\x00\x6D\x00\x18"
    MSG_STDMESG_RENDERTIMEFORANIM_STR "\x00\x00"
    "\x00\x00\x00\x6E\x00\x06"
    MSG_SCNRMODGUI_NONE_STR "\x00\x00"
    "\x00\x00\x00\x6F\x00\x06"
    MSG_SCNRMODGUI_TEXT_STR "\x00\x00"
    "\x00\x00\x00\x70\x00\x0A"
    MSG_SCNRMODGUI_STANDARD_STR "\x00\x00"
    "\x00\x00\x00\x71\x00\x04"
    MSG_SCNRMODGUI_MAX_STR "\x00"
    "\x00\x00\x00\x72\x00\x06"
    MSG_SCNRMODGUI_VIDEO_STR "\x00"
    "\x00\x00\x00\x73\x00\x22"
    MSG_SCNRMODGUI_WORLDCONSTRUCTIONSETSCREENMODE_STR "\x00"
    "\x00\x00\x00\x74\x00\x10"
    MSG_SCNRMODGUI_DISPLAYMODE_STR "\x00\x00"
    "\x00\x00\x00\x75\x00\x14"
    MSG_SCNRMODGUI_MODEINFORMATION_STR "\x00\x00"
    "\x00\x00\x00\x76\x00\x68"
    MSG_SCNRMODGUI_MODEESUTOCANNATTRIBUTESN_STR "\x00\x00"
    "\x00\x00\x00\x77\x00\x08"
    MSG_SCNRMODGUI_SAVE_STR "\x00\x00"
    "\x00\x00\x00\x78\x00\x06"
    MSG_SCNRMODGUI_USE_STR "\x00"
    "\x00\x00\x00\x79\x00\x08"
    MSG_SCNRMODGUI_EXIT_STR "\x00\x00"
    "\x00\x00\x00\x7A\x00\x46"
    MSG_SCNRMODGUI_MODE0XESXXUTOXCANNSNATTRIBUTES_STR "\x00"
    "\x00\x00\x00\x7B\x00\x08"
    MSG_SCNRMODGUI_LACED_STR "\x00\x00"
    "\x00\x00\x00\x7C\x00\x0E"
    MSG_SCNRMODGUI_GENLOCKABLE_STR "\x00\x00"
    "\x00\x00\x00\x7D\x00\x0C"
    MSG_SCNRMODGUI_DRAGGABLE_STR "\x00\x00"
    "\x00\x00\x00\x7E\x00\x0C"
    MSG_SCNRMODGUI_OVERSCAN_STR "\x00\x00"
    "\x00\x00\x00\x7F\x00\x08"
    MSG_SCNRMODGUI_WIDTH_STR "\x00\x00"
    "\x00\x00\x00\x80\x00\x08"
    MSG_SCNRMODGUI_HEIGHT_STR "\x00"
};

#endif /* CATCOMP_BLOCK */


/****************************************************************************/



#endif /* WCS_STRINGS_H */

