#!/bin/bash
# rejects commits of UTF-8 text files. 
# copy this file to .git/hooks

#set -e  # Abort on Errors
#set -x  # show commands

WINUAEIP=""   # will be set automatically in CheckSshWinUAE

function CheckNoUTF8 {
FILE_LIST="$(git diff --cached --name-only)"

for FILE in $FILE_LIST; do
    if [ $(file "$FILE" | grep -c "UTF-8") -ne "0" ]; then
        echo "Local pre-commit hook"
        echo "Error: File $FILE is UTF-8 encoded. Change that to ISO 8859-1 for Amiga and try again!"
        echo "Commit refused."
	exit 1
    fi
done
}

function CheckSimpleCat {
# check WCS.cs (SimpleCat) is ISO-8859
file /home/developer/Desktop/SelcoGit/3DNature/Amiga/WCS.cs | grep "ISO-8859"
if [ $? -ne 0 ]; then
   echo "Local pre-commit hook"
   echo "Error: File $FILE is not ISO-8859 encoded. Change that to ISO 8859-1 for Amiga and try again!"
   echo "Commit refused."
   exit 1
fi
}

function CheckSshWinUAE {
#check if we can ssh to WinUAE
#We want to run test on WinUAE later below in this script after building all. Check ssh to WinUAE now and abort before wasting time on building all configurations
WINUAEIP=$(netstat -rn | awk '/^[0-9]+/{ if($2!="0.0.0.0") {print $2;}}')
sshpass -p amigarulez! ssh -p 22222 ich@"$WINUAEIP" 'Ram:'
if [ $? -ne 0 ]; then
   echo "Local pre-commit hook"
   echo "Cannot ssh to WinUAE ("$WINUAEIP"). amigasshd -p22222 started?"
   echo "Commit aborted."
   exit 1
fi
}

function CheckSASC {
#check, if WCS is still compileable with SAS/C, also builds wcs_test_sasc_render
cd /home/developer/Desktop/SelcoGit/3DNature/Amiga/
./build_wcs_sasc.sh
if [ $? -ne 0 ]; then
   echo "Local pre-commit hook"
   echo "build_wcs_sasc.sh failed!"
   echo "Commit refused."
   exit 1
fi
}

function BuildAllEclipse {
#check if all eclipse build configurations can be build
cd /home/developer/Desktop/SelcoGit/3DNature/Amiga/
./make_all_configurations.sh
if [ $? -ne 0 ]; then
   echo "Local pre-commit hook"
   echo "make_all_configurations.sh"
   echo "Commit refused."
   exit 1
fi
}

function TestConvertOnWinUAE68020 {
# Run tests on WinUAE
echo "------------------"
echo "| Test on WinUAE |"
echo "------------------"

if [ -z $WINUAEIP ]; then
   CheckSshWinUAE
fi

# ack is like grep but with output
# we need grep (ack) "All tests passed." at the end to get a return code
sshpass -p amigarulez! ssh -p 22222 ich@"$WINUAEIP" "vbox:SelcoGit/3DNature/amiga && stack 100000 && test_68020/wcs_test_68020" | ack --passthru  "All tests passed."
if [ $? -ne 0 ]; then
   echo "Local pre-commit hook"
   echo "test_68020/wcs_test_68020 failed!"
   echo "Commit refused."
   exit 1
fi
}

############################################################################################################################################

function TestConvertOnArosI386 {
#Run Tests on AROS i386
echo "--------------------"
echo "| Test on AROS 386 |"
echo "--------------------"
# Samba does not work on AROS so far (first char of all names missing), so copy all files
# copy Amiga WCS-Install-Dir in case we want to do manual testing...
rsync -avz /home/developer/Desktop/WCS/ ~/Desktop/SelcoGit/alt-abiv0-linux-i386-d/bin/linux-i386/AROS/WCS
# copy Build/Test-Files
mkdir -p ~/Desktop/SelcoGit/alt-abiv0-linux-i386-d/bin/linux-i386/AROS/VBox/SelcoGit/3DNature/Amiga
rsync -avz ~/Desktop/SelcoGit/3DNature/Amiga/ ~/Desktop/SelcoGit/alt-abiv0-linux-i386-d/bin/linux-i386/AROS/VBox/SelcoGit/3DNature/Amiga/

# create an assign VBox: to be identical with WinUAE-Tests and create a user-startup that runs our tests and exits afterwards
echo "assign VBOX: Sys:VBox"                            > ~/Desktop/SelcoGit/alt-abiv0-linux-i386-d/bin/linux-i386/AROS/S/user-startup
echo "; BEGIN WCS"                                     >> ~/Desktop/SelcoGit/alt-abiv0-linux-i386-d/bin/linux-i386/AROS/S/user-startup
echo "assign WCS: Sys:WCS"                            >> ~/Desktop/SelcoGit/alt-abiv0-linux-i386-d/bin/linux-i386/AROS/S/user-startup
echo "assign WCSFrames: WCS:WCSFRAMES"                 >> ~/Desktop/SelcoGit/alt-abiv0-linux-i386-d/bin/linux-i386/AROS/S/user-startup
echo "assign WCSProjects: WCS:WCSProjects"             >> ~/Desktop/SelcoGit/alt-abiv0-linux-i386-d/bin/linux-i386/AROS/S/user-startup
echo "assign locale: VBox:SelcoGit/3DNature/Amiga add" >> ~/Desktop/SelcoGit/alt-abiv0-linux-i386-d/bin/linux-i386/AROS/S/user-startup
echo "; END WCS"                                       >> ~/Desktop/SelcoGit/alt-abiv0-linux-i386-d/bin/linux-i386/AROS/S/user-startup
echo ";-------------------"                            >> ~/Desktop/SelcoGit/alt-abiv0-linux-i386-d/bin/linux-i386/AROS/S/user-startup
echo "; run test tests"                                >> ~/Desktop/SelcoGit/alt-abiv0-linux-i386-d/bin/linux-i386/AROS/S/user-startup
echo "stack 100000"                                    >> ~/Desktop/SelcoGit/alt-abiv0-linux-i386-d/bin/linux-i386/AROS/S/user-startup
echo "cd VBox:SelcoGit/3DNature/Amiga"                 >> ~/Desktop/SelcoGit/alt-abiv0-linux-i386-d/bin/linux-i386/AROS/S/user-startup
# all stuff written to Debug: goes to the Linux console (stderr, i.e. use 2>&1)
echo "test_i386-aros/WCS_test_i386-aros > Debug:"      >> ~/Desktop/SelcoGit/alt-abiv0-linux-i386-d/bin/linux-i386/AROS/S/user-startup
echo ";-------------------"                            >> ~/Desktop/SelcoGit/alt-abiv0-linux-i386-d/bin/linux-i386/AROS/S/user-startup
echo ";exit AROS when done"                            >> ~/Desktop/SelcoGit/alt-abiv0-linux-i386-d/bin/linux-i386/AROS/S/user-startup
echo "shutdown"                                        >> ~/Desktop/SelcoGit/alt-abiv0-linux-i386-d/bin/linux-i386/AROS/S/user-startup
# now fire up AROS and let it do the tests.

pushd . 
cd ~/Desktop/SelcoGit/alt-abiv0-linux-i386-d/bin/linux-i386/AROS
Arch/linux/AROSBootstrap 2>&1 | ack --passthru  "All tests passed."
if [ $? -ne 0 ]; then
   echo "Local pre-commit hook"
   echo "test_i386-aros/WCS_test_i386-aros failed!"
   echo "Commit refused."
   exit 1
fi
popd
}


############################################################################################################################################

function TestConvertOnArosX86_64 {
#Run Tests on AROS x86-64
echo "-----------------------"
echo "| Test on AROS x86-64 |"
echo "-----------------------"
# Samba does not work on AROS x86-64 so far at all, so copy all files
# copy Amiga WCS-Install-Dir in case we want to do manual testing... 
rsync -avz /home/developer/Desktop/WCS/ ~/Desktop/SelcoGit/core-linux-x86_64-d/bin/linux-x86_64/AROS/WCS
# copy Build/Test-Files
mkdir -p ~/Desktop/SelcoGit/core-linux-x86_64-d/bin/linux-x86_64/AROS/VBox/SelcoGit/3DNature/Amiga
rsync -avz ~/Desktop/SelcoGit/3DNature/Amiga/ ~/Desktop/SelcoGit/core-linux-x86_64-d/bin/linux-x86_64/AROS/VBox/SelcoGit/3DNature/Amiga

# create an assign VBox: to be identical with WinUAE-Tests and create a user-startup that runs our tests and exits afterwards
echo "assign VBOX: Sys:VBox"                             > ~/Desktop/SelcoGit/core-linux-x86_64-d/bin/linux-x86_64/AROS/S/user-startup
echo "; BEGIN WCS"                                     >> ~/Desktop/SelcoGit/core-linux-x86_64-d/bin/linux-x86_64/AROS/S/user-startup
echo "assign WCS: Sys:WCS"                             >> ~/Desktop/SelcoGit/core-linux-x86_64-d/bin/linux-x86_64/AROS/S/user-startup
echo "assign WCSFrames: WCS:WCSFRAMES"                 >> ~/Desktop/SelcoGit/core-linux-x86_64-d/bin/linux-x86_64/AROS/S/user-startup
echo "assign WCSProjects: WCS:WCSProjects"             >> ~/Desktop/SelcoGit/core-linux-x86_64-d/bin/linux-x86_64/AROS/S/user-startup
echo "assign locale: VBox:SelcoGit/3DNature/Amiga add" >> ~/Desktop/SelcoGit/core-linux-x86_64-d/bin/linux-x86_64/AROS/S/user-startup
echo "; END WCS"                                       >> ~/Desktop/SelcoGit/core-linux-x86_64-d/bin/linux-x86_64/AROS/S/user-startup
echo ";-------------------"                             >> ~/Desktop/SelcoGit/core-linux-x86_64-d/bin/linux-x86_64/AROS/S/user-startup
echo "; run test tests"                                 >> ~/Desktop/SelcoGit/core-linux-x86_64-d/bin/linux-x86_64/AROS/S/user-startup
echo "stack 100000"                                     >> ~/Desktop/SelcoGit/core-linux-x86_64-d/bin/linux-x86_64/AROS/S/user-startup
echo "cd VBox:SelcoGit/3DNature/Amiga"                  >> ~/Desktop/SelcoGit/core-linux-x86_64-d/bin/linux-x86_64/AROS/S/user-startup
# all stuff written to Debug: goes to the Linux console (stderr, i.e. use 2>&1)
echo "test_x86_64-aros/WCS_test_x86_64-aros.unstripped > Debug:"   >> ~/Desktop/SelcoGit/core-linux-x86_64-d/bin/linux-x86_64/AROS/S/user-startup
echo ";-------------------"                             >> ~/Desktop/SelcoGit/core-linux-x86_64-d/bin/linux-x86_64/AROS/S/user-startup
echo ";exit AROS when done"                             >> ~/Desktop/SelcoGit/core-linux-x86_64-d/bin/linux-x86_64/AROS/S/user-startup
echo "shutdown"                                         >> ~/Desktop/SelcoGit/core-linux-x86_64-d/bin/linux-x86_64/AROS/S/user-startup
# now fire up AROS and let it do the tests.

pushd . 
cd ~/Desktop/SelcoGit/core-linux-x86_64-d/bin/linux-x86_64/AROS
boot/linux/AROSBootstrap --config-debug=mungwall 2>&1 | ack --passthru  "All tests passed."
if [ $? -ne 0 ]; then
   echo "Local pre-commit hook"
   echo "test_x86_64-aros/WCS_test_x86_64-aros failed!"
   echo "Commit refused."
   exit 1
fi
popd
}


################################################################
################################################################
function RenderTest_Generic {
    local LABEL=$1
    local SSH_COMMAND=$2
    local IMAGE_PREFIX=$3
    local MAX_PIXEL_DIFFER=$4

    if [ -z $WINUAEIP ]; then
       CheckSshWinUAE
    fi


    # Verzeichnis vorbereiten
    rm -rf ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages
    mkdir -p ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages

    # Remote-Ausfuehrung
    Error=0
    ErrorString=""
    sshpass -p amigarulez! ssh -p 22222 ich@"$WINUAEIP" "vbox:SelcoGit/3DNature/amiga && stack 100000 && $SSH_COMMAND"

    # Montage der Bilder
    montage \
        -label $LABEL ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages/CanyonSet000 \
        -label $LABEL ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages/RMNP000 \
        -label $LABEL ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages/DemoFrame001 \
        -label $LABEL ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages/WorldTest001 \
        -geometry 752x480 -tile 2x2 $IMAGE_PREFIX.jpg
    eog $IMAGE_PREFIX.jpg &

    # Fehlerueberpruefung fuer jede Datei
    for file in "RMNP000" "CanyonSet000" "DemoFrame001" "WorldTest001"
    do

      # Fuehre den compare-Befehl aus und speichere die Ausgabe in einer Variablen
#set -x
      difference=$(compare -metric AE -fuzz 6% test_files/reference/ref_wcs2.031_$file RenderTestImages/$file null: 2>&1)

      # Extrahiere die Differenz von der Ausgabe (da compare Fehlerausgaben als Rueckgabewerte sendet)
      # In diesem Fall wird die Differenz auf die Standardfehlerausgabe geschrieben, daher "2>&1".
      # Die Ausgabe ist eine Zahl (die Anzahl der unterschiedlichen Pixel).
      difference_value=$(echo "$difference" | awk '/^[0-9]+/{print $1}')
echo "differenz_value=$difference_value"
      # Vergleiche, ob die Differenz groesser als 10 ist
      if [ "$(echo "$difference_value > 0" | bc -l)" -ne 0 ]; then
echo "Diff zu gross"
        LastError=1
        Error=$(expr $Error + $LastError)

        if [ $LastError -ne 0 ]; then
            ErrorString="$ErrorString $file"
        fi
else
echo "Diff nicht gruesser 10"
      fi
#set +x
    done

    # Fehlerbehandlung
    if [ $Error -ne 0 ]; then
        echo "Local pre-commit hook"
        echo "$SSH_COMMAND failed ($ErrorString)!"
#        echo "Commit refused."
         echo "ignored for now, test will move later."
#        exit 1
    fi
}

################################################################
function RenderTest_WinUAE_SASC {
    RenderTest_Generic "SAS/C" "wcs_test_sasc_render" "BigSasC" "ref"
}

################################################################
function RenderTest_WinUAE_68020 {
    RenderTest_Generic "68020" "test_68020_render/wcs_test_68020_render" "Big68020" "ref"
}

################################################################
function RenderTest_WinUAE_68020_60 {
    RenderTest_Generic "68020_60" "test_68020-60_render/wcs_test_68020-60_render" "Big68020_60" "ref"
}

################################################################
function RenderTest_WinUAE_68040 {
    RenderTest_Generic "68040" "test_68040_render/wcs_test_68040_render" "Big68040" "ref"
}

################################################################
function RenderTest_WinUAE_68060 {
    RenderTest_Generic "68060" "test_68060_render/wcs_test_68060_render" "Big68060" "ref"
}

#######################################################################################

# Wenn Parameter uebergeben wurden, fuehre die angegebenen Funktionen aus
if [ "$#" -gt 0 ]; then
    for func in "$@"; do
        if type "$func" &>/dev/null; then
            $func
        else
            echo "Funktion '$func' existiert nicht!"
        fi
    done
else
    # Wenn keine Parameter uebergeben wurden, fuehre alle Funktionen aus
    CheckNoUTF8
    CheckSimpleCat
    CheckSshWinUAE
    CheckSASC
    BuildAllEclipse
    TestConvertOnWinUAE68020
    TestConvertOnArosI386
    TestConvertOnArosX86_64
    RenderTest_WinUAE_SASC       # 6%
    RenderTest_WinUAE_68020      # schwarze Sonne/Mond
    RenderTest_WinUAE_68020_60
    RenderTest_WinUAE_68040      # schwarze Sonne/Mond
    RenderTest_WinUAE_68060
fi
