#!/bin/bash
# rejects commits of UTF-8 text files. 
# copy this file to .git/hooks

FILE_LIST="$(git diff --cached --name-only)"

for FILE in $FILE_LIST; do
    if [ $(file "$FILE" | grep -c "UTF-8") -ne 0 ]; then
        echo "Local pre-commit hook"
        echo "Error: File $FILE is UTF-8 encoded. Change that to ISO 8859-1 for Amiga and try again!"
        echo "Commit refused."
	exit 1
    fi
done

# check WCS.cs (SimpleCat) is ISO-8859
if [ $(file /home/developer/Desktop/SelcoGit/3DNature/Amiga/WCS.cs | grep "ISO-8859") -ne 0 ] then
   echo "Local pre-commit hook"
   echo "Error: File $FILE is not ISO-8859 encoded. Change that to ISO 8859-1 for Amiga and try again!"
   echo "Commit refused."
   exit 1
fi

#check, if WCS is still compileable with SAS/C
cd /home/developer/Desktop/SelcoGit/3DNature/Amiga/
./build_wcs_sasc.sh

#check if all eclipse build configurations can be build
cd /home/developer/Desktop/SelcoGit/3DNature/Amiga/
./make_all_configurations.sh
