// IdentityDefines.h

#ifndef NVW_IDENTITYDEFINES_H
#define NVW_IDENTITYDEFINES_H

#define NVW_FILE_VERSION				.01

#define NVW_NATUREVIEW_BASENAMETEXT		"NatureView"
#define NVW_NATUREVIEW_NAMETEXT			NVW_NATUREVIEW_BASENAMETEXT " Express"
#define NVW_NATUREVIEW_NAMETEXT_HTML	NVW_NATUREVIEW_BASENAMETEXT "&nbsp;Express"
#define NVW_COMPANY_NAMETEXT			"3D Nature"
#define NVW_COMPANY_NAMETEXT_HTML		"3D&nbsp;Nature"
#define NVW_COMPANY_LONGNAMETEXT		NVW_COMPANY_NAMETEXT", LLC"
#define NVW_COMPANY_LONGNAMETEXT_HTML	NVW_COMPANY_NAMETEXT_HTML", LLC"
#define NVW_NATUREVIEW_CLASSPREFIX		"NVW"
#define NVW_VIEWER_VERSION				2
#define NVW_VIEWER_REVISION				.05
#define NVW_VIEWER_VERSIONTEXT			"2.05b"
#define NVW_NATUREVIEW_COPYRIGHTTEXT	"Copyright 2003-2006, "NVW_COMPANY_LONGNAMETEXT
#define NVW_NATUREVIEW_COPYRIGHTTEXT_HTML	"Copyright 2003-2006, "NVW_COMPANY_LONGNAMETEXT_HTML
#define NVW_NATUREVIEW_FLAVORTEXT		""

#define NVW_NATUREVIEW_FILEEXTTEXT			"nvw"
#define NVW_NATUREVIEW_COMPFILEEXTTEXT		"nvz"

#endif // NVW_IDENTITYDEFINES_H
