//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EXEIcons.rc
//
#define IDS_DRIVETIP                    1
#define IDS_ENABLECATTIP                2
#define IDS_EYEPOINTSTIP                3
#define IDS_FOLLOWTIP                   4
#define IDS_GOTOTIP                     5
#define IDS_NEXTVPTIP                   6
#define IDS_PREVVPTIP                   7
#define IDS_OPTIONSTIP                  8
#define IDS_PAUSETIP                    9
#define IDS_ROTATETIP                   10
#define IDS_SLIDETIP                    11
#define IDS_STOPTIP                     12
#define IDS_UNDOTIP                     13
#define IDS_EXITTIP                     14
#define IDS_HELPTIP                     15
#define IDS_HOMETIP                     16
#define IDS_ROTRTTIP                    17
#define IDS_ROTLTTIP                    18
#define IDS_ROTUPTIP                    19
#define IDS_ROTDNTIP                    20
#define IDS_ROTCLKTIP                   21
#define IDS_ROTCCLKTIP                  22
#define IDS_MVFWDTIP                    23
#define IDS_MVBKTIP                     24
#define IDS_MVLTTIP                     25
#define IDS_MVRTTIP                     26
#define IDS_CLIMBTIP                    27
#define IDS_CLOSETIP                    28
#define IDS_DRAGWINTIP                  29
#define IDS_HOTNAVTIP                   30
#define IDS_THROTTLETIP                 31
#define IDS_INFOTIP                     32
#define IDS_HOTTURNTIP                  33
#define IDS_NAVPANELTIP                 34
#define IDS_INFOPANELTIP                35
#define IDS_DRIVEPANELTIP               36
#define IDS_ACTIONTIP                   37
#define IDS_ABOUTTIP                    38
#define IDI_ICON1                       101
#define IDD_INFOPANEL                   104
#define IDD_HELPPANEL                   105
#define IDD_BUSYDIALOG                  127
#define IDD_BUSYDIALOGCANCEL            128
#define IDR_INFOPANEL_NORMAL_JPEG       129
#define IDD_DATAPANEL                   129
#define IDR_INFOPANEL_NORMAL_HOVER_JPEG 130
#define IDD_HTMLPANEL                   130
#define IDR_DRIVEPANEL_NORMAL_JPEG      136
#define IDB_BACK                        136
#define IDR_DRIVEPANEL_NORMAL_HOVER_JPEG 137
#define IDR_DRIVEPANEL_SEL_JPEG         138
#define IDB_FWD                         138
#define IDR_DRIVEPANEL_SEL_HOVER_JPEG   139
#define IDB_STOP                        139
#define IDR_NAVPANEL_NORMAL_JPEG        140
#define IDB_BITMAP1                     140
#define IDB_REFRESH                     140
#define IDR_NAVPANEL_NORMAL_HOVER_JPEG  141
#define IDR_NAVPANEL_SEL_JPEG           142
#define IDR_NAVPANEL_SEL_HOVER_JPEG     143
#define IDR_INFOPANEL_INDEX_PNG         144
#define IDR_DRIVEPANEL_INDEX_PNG        145
#define IDR_NAVPANEL_INDEX_PNG          146
#define IDR_SLIDE_KNOB_PNG              147
#define IDC_MVFWD                       1001
#define IDC_MVBK                        1002
#define IDC_MVRT                        1003
#define IDC_MVLT                        1004
#define IDC_ELEVSLIDE                   1005
#define IDC_SPEEDSLIDE                  1006
#define IDC_EYEPOINTS                   1007
#define IDC_PAUSE                       1008
#define IDC_HOME                        1009
#define IDC_STOP                        1010
#define IDC_ROTUP                       1011
#define IDC_ROTDN                       1012
#define IDC_ROTRT                       1013
#define IDC_ROTLT                       1014
#define IDC_CATAGORIES                  1015
#define IDC_GOTO                        1016
#define IDC_ROTATE                      1017
#define IDC_DRIVE                       1018
#define IDC_SLIDE                       1019
#define IDC_UNDO                        1020
#define IDC_FOLLOW                      1021
#define IDC_VIEWPOINTS                  1022
#define IDC_INFOTEXT                    1022
#define IDC_NEXTVIEW                    1023
#define IDC_HELPTEXT                    1023
#define IDC_PREVVIEW                    1024
#define IDC_OPTIONS                     1025
#define IDC_EXIT                        1026
#define IDC_HELPBUTTON                  1027
#define IDC_BUSYPROGRESS                1028
#define IDC_BUSYTEXT                    1029
#define IDC_CANCELBUTTON                1030
#define IDC_CLIMB                       1031
#define IDC_HOTNAV                      1032
#define IDC_HOTTURN                     1033
#define IDC_DATATEXT                    1033
#define IDC_QUERY                       1034
#define IDC_EDIT                        1035
#define IDC_BACK                        1036
#define IDC_FWD                         1037
#define IDC_INFO                        1038
#define IDC_REFRESH                     1039
#define IDC_NAV                         1040
#define IDC_ACTIONMODE                  1041
#define IDC_SHOWDRIVE                   1042
#define IDC_CREDITS                     1043
#define IDC_DRAG                        10000
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1044
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
