// UsefulUnit.h
// Unit conversion code from Useful.h
// Built from Useful.h on 060403 by CXH

#ifndef WCS_USEFULUNIT_H
#define WCS_USEFULUNIT_H

enum
	{
	// SI Units
	WCS_USEFUL_UNIT_XUNIT = 0,
	WCS_USEFUL_UNIT_ANGSTROM,
	WCS_USEFUL_UNIT_MILLIMICRON,
	WCS_USEFUL_UNIT_MICRON,
	WCS_USEFUL_UNIT_MILLIMETER,
	WCS_USEFUL_UNIT_CENTIMETER,
	WCS_USEFUL_UNIT_DECIMETER,
	WCS_USEFUL_UNIT_METER,
	WCS_USEFUL_UNIT_KILOMETER,
	WCS_USEFUL_UNIT_MEGAMETER,

	// English units
	WCS_USEFUL_UNIT_INCH,
	WCS_USEFUL_UNIT_FEET,
	WCS_USEFUL_UNIT_YARD,
	WCS_USEFUL_UNIT_ROD,
	WCS_USEFUL_UNIT_MILE_US_STATUTE,
	WCS_USEFUL_UNIT_FEET_US_SURVEY, // NOT THE COMMON FOOT

	// More exotic units
	WCS_USEFUL_UNIT_FURLONG,
	WCS_USEFUL_UNIT_CHAIN_GUNTER,
	WCS_USEFUL_UNIT_CHAIN_RAMDEN,
	WCS_USEFUL_UNIT_LINK_GUNTER,
	WCS_USEFUL_UNIT_LINK_RAMDEN,
	WCS_USEFUL_UNIT_FATHOM,
	WCS_USEFUL_UNIT_MILE_NAUT_BRIT,
	WCS_USEFUL_UNIT_MILE_NAUT_INT,
	WCS_USEFUL_UNIT_LEAGUE_NAUT_BRIT,
	WCS_USEFUL_UNIT_LEAGUE_NAUT_INT,
	WCS_USEFUL_UNIT_LEAGUE,
	WCS_USEFUL_UNIT_MIL,
	WCS_USEFUL_UNIT_ROPE,
	WCS_USEFUL_UNIT_CUBIT,
	WCS_USEFUL_UNIT_AU,
	WCS_USEFUL_UNIT_LIGHTYEAR,
	WCS_USEFUL_UNIT_PARSEC,
	WCS_USEFUL_UNIT_MAXIMUM
	};

#define WCSW_FP_CONVERT_STRING "%.12f"

double ConvertToMeters(double OrigVal, int FromUnit);
double ConvertFromMeters(double MeterVal, int ToUnit);
int GetUpconvertUnit(int Unit);
int GetDownconvertUnit(int Unit);
char *GetUnitName(int Unit);
char *GetUnitSuffix(int Unit);
int MatchUnitSuffix(char *Suffix);
int GetNormalizedUnit(int Unit, double Meters);

#endif // WCS_USEFULUNIT_H
