######################################################################
# Automatically generated by qmake (1.07a) Tue Feb 8 10:41:34 2005
######################################################################

#TEMPLATE = vclib
TEMPLATE = lib
INCLUDEPATH += .

# Input
HEADERS += wcs-client.h ..\client.h
SOURCES += wcs-client.cpp ..\datatypes.cpp ..\scthread.cpp
