// VocabTable.h
//
// #defines for Markov search table.
// Machine generated code, do NOT hand-alter.
// Created from file "commandlist".


extern unsigned long int MarkovTable[];

#define VE_ADD                    29 /* ADd */
#define VE_ALIAS                  33 /* ALias */
#define VE_ANTIALIAS              41 /* ANtialias */
#define VE_ARCVIEW                47 /* ARcview */
#define VE_AS                     48 /* AS */
#define VE_ASPECT                 53 /* ASPect */
#define VE_ASSIGN                 57 /* ASSign */
#define VE_BACKGROUND             70 /* BACkground */
#define VE_BANK                   72 /* BANk */
#define VE_BORDER                 78 /* BORder */
#define VE_BOTTOM                 82 /* BOTtom */
#define VE_BY                     83 /* BY */
#define VE_CAMERA                 94 /* CAMEra */
#define VE_CAMVIEW                98 /* CAMView */
#define VE_CLEAR                 103 /* CLEar */
#define VE_CLOSE                 107 /* CLOSe */
#define VE_CLOUD                 109 /* CLOUD */
#define VE_CLOUDS                110 /* CLOUDS */
#define VE_COLOR                 116 /* COLor */
#define VE_COMMENT               122 /* COMMent */
#define VE_COMPOSITE             128 /* COMPosite */
#define VE_CONFIRM               134 /* CONFirm */
#define VE_CONTENTS              139 /* CONTents */
#define VE_CREATE                144 /* CReate */
#define VE_CURRENT               150 /* CUrrent */
#define VE_DATABASE              164 /* DAtabase */
#define VE_DEBUG                 171 /* DEBug */
#define VE_DEFAULT               177 /* DEFAult */
#define VE_DEFORM                180 /* DEFOrm */
#define VE_DEPTH                 183 /* DEPth */
#define VE_DESELECT              189 /* DESelect */
#define VE_DIRLIST               196 /* DIRlist */
#define VE_DISTRIBUTION          206 /* DIStribution */
#define VE_DLG                   208 /* DLg */
#define VE_DOMINANCE             216 /* DOminance */
#define VE_DRAW                  219 /* DRaw */
#define VE_DXF                   221 /* DXf */
#define VE_ECHO                  229 /* ECHo */
#define VE_ECOSYSTEM             236 /* ECOsystem */
#define VE_EFFECT                241 /* EFFECT */
#define VE_EFFECTS               242 /* EFFECTS */
#define VE_ENABLED               249 /* ENAbled */
#define VE_END                   250 /* END */
#define VE_EXAGGERATION          263 /* EXAggeration */
#define VE_EXIT                  265 /* EXIt */
#define VE_EXPORT                269 /* EXPort */
#define VE_FACTOR                282 /* FACtor */
#define VE_FADE                  284 /* FADe */
#define VE_FDMS                  287 /* FDms */
#define VE_FIELD                 293 /* FIEld */
#define VE_FILE                  295 /* FILE */
#define VE_FILENAME              299 /* FILEName */
#define VE_FIX                   300 /* FIX */
#define VE_FIXED                 302 /* FIXEd */
#define VE_FLATTEN               308 /* FLatten */
#define VE_FORCE                 313 /* FORCe */
#define VE_FORMAT                316 /* FORMat */
#define VE_FRACTAL               323 /* FRACtal */
#define VE_FRAME                 325 /* FRAME */
#define VE_FRAMES                326 /* FRAMES */
#define VE_FRAMESAVE             329 /* FRAMESAve */
#define VE_FULL                  332 /* FUll */
#define VE_GENERATE              342 /* GEnerate */
#define VE_GLOBAL                347 /* GLobal */
#define VE_GRADIENT              355 /* GRAdient */
#define VE_GRID                  357 /* GRId */
#define VE_HALF                  365 /* HALf */
#define VE_HAZE                  367 /* HAZe */
#define VE_HEIGHT                372 /* HEight */
#define VE_HIGH                  375 /* HIgh */
#define VE_HORIZON               381 /* HOrizon */
#define VE_IMAGE                 388 /* IMAGE */
#define VE_IMAGES                389 /* IMAGES */
#define VE_IMPORT                393 /* IMPort */
#define VE_INTER                 397 /* INter */
#define VE_JUMP                  401 /* Jump */
#define VE_KEYFRAME              409 /* Keyframe */
#define VE_LATITUDE              421 /* LATitude */
#define VE_LAYER                 424 /* LAYer */
#define VE_LEVEL                 428 /* LEvel */
#define VE_LIGHT                 433 /* LIGht */
#define VE_LINE                  435 /* LINe */
#define VE_LOAD                  441 /* LOAd */
#define VE_LONGITUDE             448 /* LONgitude */
#define VE_LOOKAHEAD             455 /* LOOkahead */
#define VE_LOW                   456 /* LOW */
#define VE_MAP                   463 /* MAP */
#define VE_MAPS                  465 /* MAPS */
#define VE_MAPVIEW               469 /* MAPView */
#define VE_MATCH                 472 /* MATch */
#define VE_MAXIMUM               477 /* MAXimum */
#define VE_MEDIUM                482 /* MEdium */
#define VE_MODE                  486 /* MODe */
#define VE_MOON                  488 /* MOOn */
#define VE_NAME                  493 /* NAme */
#define VE_NORMAL                498 /* NOrmal */
#define VE_OFF                   505 /* OFF */
#define VE_OFFSET                508 /* OFFSet */
#define VE_ON                    509 /* ON */
#define VE_OPEN                  512 /* OPen */
#define VE_ORIGIN                517 /* ORigin */
#define VE_OVERSCAN              524 /* OVerscan */
#define VE_PALETTE               536 /* PALette */
#define VE_PARAMETERS            544 /* PARameters */
#define VE_PATH                  546 /* PATh */
#define VE_PICTURE               552 /* PIcture */
#define VE_POSITION              559 /* POsition */
#define VE_PREVIEW               567 /* PREview */
#define VE_PRIORITY              573 /* PRIority */
#define VE_PROJECT               578 /* PROject */
#define VE_QUALITY               587 /* QUALity */
#define VE_QUARTER               591 /* QUARter */
#define VE_QUIET                 595 /* QUIEt */
#define VE_QUIT                  596 /* QUIT */
#define VE_RANDOM                604 /* RAndom */
#define VE_REFERENCE             617 /* REFerence */
#define VE_RELIEF                621 /* RELief */
#define VE_REM                   622 /* REM */
#define VE_RENDER                626 /* RENder */
#define VE_REQUEST               631 /* REQuest */
#define VE_REVERSE               636 /* REVerse */
#define VE_RUN                   638 /* RUn */
#define VE_SAVE                  651 /* SAVE */
#define VE_SAVEAS                653 /* SAVEAs */
#define VE_SCREEN                659 /* SCREen */
#define VE_SCRIPT                662 /* SCRIpt */
#define VE_SEGMENTS              671 /* SEGments */
#define VE_SELECT                675 /* SELect */
#define VE_SET                   676 /* SET */
#define VE_SETTINGS              681 /* SETTings */
#define VE_SHADE                 686 /* SHADE */
#define VE_SHADOWS               689 /* SHADOws */
#define VE_SIZE                  692 /* SIze */
#define VE_SKY                   694 /* SKy */
#define VE_SNOW                  697 /* SNow */
#define VE_SPECIAL               704 /* SPECial */
#define VE_SPEED                 706 /* SPEEd */
#define VE_START                 711 /* STArt */
#define VE_STEP                  713 /* STEp */
#define VE_SUN                   716 /* SUN */
#define VE_SURFACE               721 /* SURface */
#define VE_TARGET                732 /* TArget */
#define VE_TEMPORARY             740 /* TEmporary */
#define VE_TITLE                 744 /* TItle */
#define VE_TO                    745 /* TO */
#define VE_TOP                   746 /* TOP */
#define VE_TREES                 750 /* TRees */
#define VE_TURNS                 754 /* TUrns */
#define VE_VARIABLE              763 /* VAriable */
#define VE_VECTOR                769 /* VECtor */
#define VE_VELOCITY              775 /* VELocity */
#define VE_WCSFRAMES             787 /* WCSFrames */
#define VE_WCSPROJECTS           795 /* WCSProjects */
#define VE_WDB                   797 /* WDb */
#define VE_WIDTH                 802 /* WIDth */
#define VE_WINDOW                806 /* WINdow */
#define VE_Z                     807 /* Z */
#define VE_ZBUFFER               814 /* ZBUFFER */
#define VE_ZBUFFERSAVE           818 /* ZBUFFERSave */
#define VE_ZENITH                823 /* ZEnith */


/* EOF */
