// ProjectDispatch.h
// Defines for the dispatch functions for setting and getting values from the Project object
// of World Construction Set.
// Created 3/4/96 by GRH
// Copyright 1996 by Questar Productions

#ifndef WCS_PROJECTDISPATCH_H
#define WCS_PROJECTDISPATCH_H


#define WCS_DEFINED_PROJECTCLASSES	8
#define WCS_MAXPROJ_NOTIFY_CHANGES	10

// Class
#define WCS_PROJECTCLASS_ALL			~0
#define WCS_PROJECTCLASS_PATHS			101
#define WCS_PROJECTCLASS_DATABASE		102
#define WCS_PROJECTCLASS_PARAMETERS		103
#define WCS_PROJECTCLASS_PLUGINS		104
#define WCS_PROJECTCLASS_WIZARD			105
#define WCS_PROJECTCLASS_GUICONFIG		106
#define WCS_PROJECTCLASS_PREFS			107
#define WCS_PROJECTCLASS_USERDATA		108
#define WCS_PROJECTCLASS_MODULE			109

// Subclass
#define WCS_PATHS_DIRLIST				220
#define WCS_PATHS_DEFAULTDIR			221
#define WCS_SUBCLASS_MODULE_OPEN		222
#define WCS_SUBCLASS_MODULE_CLOSE		223
#define WCS_SUBCLASS_PROJPREFS_UNITS	224
#define WCS_SUBCLASS_PROJPREFS_CONFIG	225


// Item
// SubClass = 0 for short integers
#define WCS_PARAMETERS_GRIDSIZE			0
#define WCS_PARAMETERS_SENSITIVITY		1
#define WCS_PARAMETERS_GRIDSTYLE		2
#define WCS_PARAMETERS_MOVEMENT			3
#define WCS_PARAMETERS_GBDENS			4
#define WCS_PARAMETERS_AUTODRAW			5
#define WCS_PARAMETERS_ANIMSTART		6
#define WCS_PARAMETERS_ANIMEND			7
#define WCS_PARAMETERS_ANIMSTEP			8
#define WCS_PARAMETERS_COMPASSBDS		9
#define WCS_PARAMETERS_LANDBDS			10
#define WCS_PARAMETERS_BOXBDS			11
#define WCS_PARAMETERS_PROFBDS			12
#define WCS_PARAMETERS_GRIDBDS			13

#define WCS_PROJPREFS_HORDISPLAYUNITS		0
#define WCS_PROJPREFS_VERTDISPLAYUNITS		1
#define WCS_PROJPREFS_ANGLEDISPLAYUNITS		2
#define WCS_PROJPREFS_POSLONHEMISPHERE		3
#define WCS_PROJPREFS_LATLONSIGNDISPLAY		4
#define WCS_PROJPREFS_TIMEDISPLAYUNITS		5
#define WCS_PROJPREFS_ENABLEDFILTER			6
#define WCS_PROJPREFS_ANIMFILTER			7
#define WCS_PROJPREFS_TASKMODE				8
#define WCS_PROJPREFS_GUICONFIG				9
#define WCS_PROJPREFS_SAGEXPANDED			10
#define WCS_PROJPREFS_SHOWDBBYLAYER			11
#define WCS_PROJPREFS_RECORDMODE			12  // RecordMode is currently unused and may be retired eventually
#define WCS_PROJPREFS_INTERACTIVEMODE		13
#define WCS_PROJPREFS_KEYGROUPMODE			14
#define WCS_PROJPREFS_MAXSAGDBITEMS			15
#define WCS_PROJPREFS_MAXSORTEDSAGDBITEMS	16
#define WCS_PROJPREFS_SIGNIFICANTDIGITS		17
#define WCS_PROJPREFS_SAGBOTTOMHTPCT		18
#define WCS_PROJPREFS_INTERSTYLE			19
#define WCS_PROJPREFS_GEOPROJDISPLAY		20
#define WCS_PROJPREFS_VECPOLYLIMITMEGS		21
#define WCS_PROJPREFS_DEMLIMITMEGS			22
#define WCS_PROJPREFS_GLOBALADVANCED		23

#define WCS_ITEM_MODULE_DIGITIZEGUI		1

#endif // WCS_PROJECTDISPATCH_H
