// TipTable.h
// Repository for Tips.
// Ripped out of VersionGUI.cpp on March 22 2002 by CXH

//lint -save -e786
char *TipTable[] = {
"Holding down the SHIFT and CONTROL keys while getting diagnostic info from a rendered image will display the X and Y coordinates within the image instead of the RGB/HSV values. This tip does not work with diagnostic info from GL Views.",
"When digitizing, you can click in other GL Views, rendered Views, or even registered colormap images to place points.",
"If you click the Sample Color from Image checkbox the Color editor you can grab colors from any image in "APP_TLA", any GL View or any color well.",
"Double-click anywhere in a rendered image to automatically open the appropriate editor for the area or item you clicked on. This will only work if Render Diagnostic Data is checked in the Enabled2 section of your Render Options.",
"ALT-click any object in a GL View to make it the Active Object.",
"Control-click in a GL View to place the Active Object at the location you click (if the object supports this capability).",
"ALT-triple-click an object in a GL View to make it the Active Object and open the appropriate editor.",
"Hitting the ? key in a GL View will open the View Preferences for that View.",
"Adjust your GL display redraw speed by setting the Maximum Polygons in the General tab of the View Preferences.",
"Lightwave users: Hitting F9 in a GL View will render a Preview in that View.",
"Lightwave users: Hitting the return key in a GL View will open the Make Keyframe requester.",
"The small Play Animation button at the right edge of the time scrollbar is often overlooked.",
"Holding down the Spacebar in a View will switch you into Manipulate Camera mode until you release the spacebar.",
"Pressing the F1/Help key in any window will attempt to open the online reference manual to the page appropriate for that window.",
"Experiment with the Load Fast and Keep in Memory Long options in the Image Object Library. If you have the memory to spare, these can reduce and speed up image loading operations during rendering.",
"Most editor windows have an Undo all changes in this window button in the titlebar.",
"Click on the Status Log [ALT+G] button on the lower toolbar to see the most recent messages from the Status Line.",
"The Lock Active Item button on the lower toolbar will prevent the Active Item from changing inadvertently. If you can't get the Active Object to change, check to see if it is on.",
"Your Render Options can have a different Frame Rate than the rest of your project. This would allow you to use several Render Options to produce NTSC (30fps), PAL (25fps) and film (24fps) versions of the same animation.",
"For reducing network traffic when using a large number of Render Engines, set your Temp Path in your Render Options to a local drive.",
"You can now output the same rendered image to multiple image formats automatically. See the File Output section of the Render Options Editor.",
"You can now automatically add the preferred extension to your rendered images with the Add Extension checkbox in the File Output section of the Render Options.",
"If your camera is looking down onto the terrain and trees are disappearing into the ground or steep hillsides, try checking the Render From Overhead checkbox in the Misc section of the Render Options.",
"The Render Editor [ALT-R] can now schedule and consecutively render several Render Jobs in the same project. This is useful for 'multi-camera' action shots.",
"Setting the CPU Priority in the Render Editor to Low is good for letting "APP_TLA" render in the background while you continue to use your computer.",
"Leaving the Show Rendering checkbox on in the Render Editor significantly slows down rendering. Turn it off when you are not using it.",
"The Selected Job area of the Render Editor is good for checking that your render settings are correct before beginning a long render. You can use the Edit buttons next to the Camera and Options to further verify and correct settings.",
"You can view time in "APP_TLA" in either Frames or decimal seconds. Select your preferred type in the Units section of the Preferences window [CTRL =].",
"Displaying large numbers of database items in the Scene at a Glance can be very slow, so "APP_TLA" allows you to limit the number of items visible. This is controlled with the Max Database Items in S@G field in the General page of the Preferences window [CTRL-P].",
"If you wish, you can prevent "APP_TLA" from hiding inappropriate windows when switching task modes by turning off Matrix Task Modes in the Matrix Section [CTRL -] of the Preferences window.",
"You can change your Project's Animation Frame Rate in the Project section of the Preferences window without damaging any keyframes!",
"Experiment with the two different styles of GL View Interaction in the Interaction section of the Preferences window. Users familiar with other 3D or CAD software may find one or the other more comfortable.",
"If your project (or a project received from another "APP_TLA" user) cannot find and load its DEMs or other components, check the DEM Directories [CTRL D] and Paths [CTRL E] sections of the Preferences window.",
"If you move image files around, "APP_TLA" will automatically search the directories it knows about to try to find them. If it cannot find them, it will ask you to locate them, and will remember that location for future searches.",
"Customize "APP_TLA" to your preferred working methods by selecting your favorite Units and notations in the Units section [CTRL =] of the Preferences window.",
""APP_TLA"'s file menu will list the names of the last six projects you worked on for quick and easy access.",
"The import wizard is your friend. It will automatically attempt to recognize and help you load any types of data files it understands.",
"The import wizard cannot directly work with files that are .ZIPped, .GZipped, .TARred, BINHEXed or otherwise compressed or archived. You will need to extract or decompress these files before using them in "APP_TLA".",
"You can select multiple DEMs, Vectors and Control Points in the Database editor to perform the same operation to all of them.",
"You can conform multiple vector objects or control points to existing terrain with the Conform to: Terrain button in the Database editor.",
"If you have 2D vector objects or control points with no actual elevation, but have the elevation in the Name, Label or a Layer, use the Conform To: Name, Label and Layer buttons in the Database editor.",
"If you can't find data that you've imported, try checking where it ended up with the North, South, East and West extents fields in the Database editor to see if you made errors while importing.",
"You can do amazing things with images in the Image Object Library. Be sure to at least skim the reference documentation to appraise yourself of its capabilities.",
"Make sure you check often for Online Updates at the 3D Nature Web Site. Bug fixes, improvements, optimizations, tutorials, components and more!",
"If a window gets buried behind others, select it in the Window menu to bring it back into view.",
"You can set up and save common Gridding settings in a Terrain Gridder component.",
"If you suspect that your GL View is not showing the most up-to-date information, try pressing the V key to redraw all GL Views.",
"Create and save components from the projects you make so you can reuse them in future works, or swap them with other "APP_TLA" users. Take credit for your work! Fill in the Email field so users of your component know who the creator was.",
"It's a good idea to put usage and customization instructions into a Component's description when you Sign and Save it.",
"The Library Browser area in the Component Library window will allow you to select multiple components from another project file and import them into your current project. This only works with project files from the same version of "APP_TLA".",
"You can adjust the relative sizes of the upper and lower Scene at a Glance lists by grabbing and dragging the bar that separates them. The changes will be saved with your preferences.",
"You can drag and drop items between the two Scene at a Glance lists.",
"Clicking the Expand Scene at a Glance button at the top right of the upper list will widen the lists for better visibility and operation.",
"You can grab and drag the right edge of the Scene at a Glance to make it bigger. Toggle back to the original size with the Expand Scene at a Glance button at the top right of the upper list.",
"Try out the Show only enabled items and Show only animated items filter buttons at the top of the Scene at a Glance.",
"You can clone an existing item in the Scene at a Glance with the Add or clone selected item button at the top.",
"Some categories of items in the Scene at a Glance allow you to Enable or Disable the whole category.",
"Task Modes allow you to reduce user interface clutter by hiding windows that are not appropriate for the Task Mode you are currently in.","You can create new cameras from the View section of a GL View's popup menu.",
"You can have several GL Views using the same camera, but with different Realtime items enabled.",
"Typically all GL Views default to using a common Render Options but you can change this with Select Option Set in the View's popup menu.",
"You can save a rendered image or a GL view to a file with the Save Displayed Image popup menu item. Rendered images can be saved in several formats. GL Views can only be saved in Window's 'native' format, BMP.",
"When turning off Show Preview from a View's popup menu, answer 'Yes' to preserve diagnostic data. This will allow you to switch back to the Preview render by reselecting the Show Preview menu item.",
"If you want to quickly change the Active Object or parameter numerically without opening its editor, try the Numeric Entry [ALT .] window.",
"Keep your camera from running into the ground as you move it by turning on the Interactive Elevation Follow Terrain checkbox in the Camera Editor. There is a shortcut to this \'Make Camera Follow Terrain\' in the General tab of the View Preferences.",
"Orthographic cameras have no perspective. A mountain in the distance appears the same size as a mountain close up.",
"Planimetric cameras flatten the world out for making maps.",
"Overhead cameras always look straight down.",
"Panoramic cameras will create a 360-degree cylindrical panoramic image, automatically stitched together, for each frame in your animation.",
"The Horizontal View Arc controls how many radial segments "APP_TLA" will render for a Panoramic camera.",
"Selecting Realistic Lens Distortion on a camera will introduce curvature more like a real camera, but less like conventional 3D visualization software.",
"Multipass Antialising and Motion Blur can add significantly to your render time, and should be used carefully.",
"Depth-of-field can be a very convincing effect if used in small amounts. Large amounts can take a very long time to calculate.",
"Camera Velocity distribution keeps your camera going a constant speed throughout your animation, with an optional ease-in and ease-out to start and stop. This can result in your animation timing appearing very different.",
"Cameras can be instructed to target either the center or origin of a 3D Object.",
"Any targeted or Align to Path camera can still look away from its target or path by using the Heading, Pitch and Bank controls.",
"Make your camera automatically bank through your animation with the Create Bank Keys button in the Camera Editor. You can even tweak the banking manually.",
"If you use Field Rendering, make sure you understand and use the proper Field Dominance for your playback device or your animation may jitter badly.",
"You can quickly view images in any of "APP_TLA"'s supported formats with the View/View Image/From Disk... item in "APP_TLA"'s main menus.",
"You can quickly view the last image you rendered with the View/View Image/Last Rendered... item in "APP_TLA"'s main menus.",
"Key shortcuts can greatly increase your "APP_TLA" proficiency. Most menu items list their shortcuts, and most icons will display their shortcuts in their captions if you leave the mouse motionless over them. There is a list of key shortcuts available in the online help.",
"Priority and Evaluation Order are very important when you have multiple Terraffectors that overlap.",
"You can use a texture to control the amount of effect of Terraffectors, and the amount of Roughness, for some very powerful techniques.",
"You can rotate the whole planet and change its size in the Planet Options component. Default sizes for all our solar system's planets are provided, or you can set your own.",
"The cross-section profile of a linear (non-Area) Terraffector is mirrored symmetrically on both sides of the vector it is attached to.",
"Never use Variable Fractal Depth when making an animation. It will result in polygon sizes changing, and trees and foliage appearing and disappearing. Use Fractal Depth maps instead.",
"Constant Fractal Depth is rarely used in animation, but is very helpful for making maps where you want uniform detail and foliage density throughout the whole landscape.",
"Backface Culling can speed up rendering for stills, but in an animation it may result in trees disappearing as the terrain they stand upon disappears beyond a ridge.",
"Maximum Fractal Depth can be controlled by a texture or a raster image, allowing for very powerful and precise control over level-of-detail in your terrain.",
"Displacement mapping can be achieved on land or water by using a texture to modulate a Terraffector or by using a Roughness texture on the Waves in the Water Material of a Lake or Stream.",
"Terrain morphing can be simulated by using an animated texture to modulate a Terraffector on existing terrain or even on a perfectly flat DEM.",
"For subtle or dramatic effects, you can adjust the ambient light coming from the sky and from the ground separately in the Atmosphere component.",
"Small amounts of haze and fog can greatly increase realism of natural scenes.",
"You can use any image you like as a Celestial object and tint it to a new color if you wish.",
"A good sky gradient can greatly affect the feel of a scene. Experiment in the Sky Editor.",
"You can use textures to control clouds to make patterns or even shapes, images or logos appear in the clouds",
"You can use multiple Starfield components together with different densities and images to create a varied night sky.",
"Starfields can sprinkle any image around your sky -- not just stars.",
"You can make a Celestial object automatically follow a light.",
"Distant lights always point at the center of the planet and have no falloff.",
"You can recreate the lighting conditions of a real place and time with the Set Position By Time button in the Light component.",
"Using multiple shadows of different resolution in a scene is the key to good shadow results.",
"You can set a 3D Object to be invisible but still cast a shadow if you plan on rendering and compositing the object using another 3D rendering program.",
"Snowline feathering can make much more realistic snow regions and animated snowline changes.",
"You can set the Snow Cannot Cover this Ecosystem checkbox on an Ecosystem component to keep areas such as roads and parking lots snow-free.",
"Use textures and material gradients to vary the density and height of vegetation for extremely realistic results.",
"Use the Distance Dissolve (and Dissolve Color) controls in EcoTypes and Foliage Effects to lessen the amount of distant foliage "APP_TLA" must render with little noticeable difference.",
"Foliage Effects and Ecosystem EcoTypes can now use Images and 3D Objects.",
"When planting 3D Object vegetation, use the rotation variation (typically just the Y axis) for greater apparent variety.",
"When placing Image object vegetation, use the Random Flip X option for greater apparent variety.",
"Ecosystems with Constant Density (Stems per Unit Area) will give you accurate vegetation densities regardless of your fractal depth, but will take considerably longer to render.",
"Double-clicking most image thumbnails will open the image in a separate window.",
"Color Maps can be set to Drape Image on Terrain (good for draping photos, but unable to control vegetation) or Match Ecosystems to Image Colors (each polygon is a single color from the image, and can control vegetation growth).",
"Color Maps with Randomize Edges turned on have rougher, more natural borders.",
"Turning Luminous Colors on in a Color Map will allow you to pick unaltered color samples out of the rendered image to set up Ecosystem matching.",
"You can automatically snap a Color Map to a DEM or set of selected DEMs in the Image Object Library's Geo Reference tab.",
"The order of Ecosystems in an Environment or in a Color Map component is very important when more than one Ecosystem could conceivably be placed at a given location.",
"In the Color Map editor, you can easily grab an entire range of colors from an image to match to an Ecosystem.",
"SHIFT-clicking the More Tips button will open the online reference manual to show all of the tips.",
"You can digitize from any image that has geographic bounds (like a Color Map or bounded Texture Image) if you open the image for viewing from the Image Object Library or by double-clicking a thumbnail where it is displayed.",
"Increase the Environment's Distant Foliage Intensity if you don't want small distant foliage objects to disappear.",
"Use Image Object Distance Dissolve in the Ecosystem or Foliage Effect Editors to speed up rendering if you have a lot of foliage in the scene.",
"Use textures to create patterns of foliage.",
"Turn on Render from Overhead in Render Options when the camera is oriented downward. It offsets foliage Z values slightly so that 2D foliage doesn't get clipped by the terrain.",
"Celestial Objects can be linked to one or more Lights. An instance of the Object will appear at the position of each linked Light.",
"Use Planimetric GL Views and rendered previews for the most accurate digitizing.",
"To make a halo around a Celestial Object, attach it to a Light and in the Sky Editor set the second pin of the Toward and Away from Light Color Gradient to about 5% or less. Make the color of the first pin lighter than the color of the second pin.",
"Use Foliage Effects to make floating signs, billboards and labels. Set the Effect's Elevation to the height above the terrain you want the sign or label.",
"Hold down the SHIFT key to temporarily switch Interactive Style between Relative to Ground and Relative to Camera.",
"Hit the ENTER key while a View is activated to create a key frame.",
""APP_TLA" keeps track of key frame positions internally in units of seconds and fractions of a second. You can change the frame rate at any time without destroying the actual time positions of key frames.",
"Each set of Render Options has its own independent frame rate so you can have one Render Job to record for film and another for video. Both animations will be the same playback length in real time.",
"Use Connect mouse mode when you digitize to create rows of evenly spaced trees, fence posts or telephone poles. You can control the spacing between each point.",
"Using Foliage Effects to place multiple 3D Objects will save both memory and time when using shadows but their shadows will not be as detailed as when you use 3D Objects attached directly to a vector.",
"To export the whole planet as either a LightWave 3D or 3D Studio file, set the Reference Latitude to 90 degrees and the Reference Longitude to 0 degrees. That will prevent the planet from being rotated during export.",
"You can sample Color Map Ecosystem Match Colors directly from the Color Map image. You can even sample a range of colors by dragging the mouse over the area to match.",
"A good way to get realistic material colors is to sample them from a photograph. The Color Editor lets you sample single colors or color aggregates from any image you can view in "APP_TLA".",
"Colors can be sampled from displayed images, rendered images, image thumbnails and color wells within "APP_TLA".",
"When the Color Editor is open and set for sampling colors from images, clicking other color wells will sample the color well's color.",
"Better textures will usually result if the Project Reference Coordinates are somewhere near the center of the terrain.",
"You can set the style of interactive motion you prefer on the Interaction page of the Preferences window. LightWave users should find Relative to Ground to be most familiar. MAX users may prefer Relative to Camera.",
"Hit [CTRL G] to jump to any frame in your animation.",
"[ALT .] will open the Numeric Input requester for the Active Item.",
"Holding the SHIFT key while hitting the Select button in the Layers section of the Database window will add Database Objects that match the selected layer to the selected list of Objects. Holding the CONTROL key while clicking will subtract selected items.",
"Minimizing the "APP_TLA" application while it renders can result in noticeable speed increases.",
"When importing DTED files, try feeding the un-GZIPped .tar file straight to the Import Wizard without un-tarring it. You can even multi-select a number of TAR files all at once.",
"The Measure tool on the Toolbar can give you straight line and great-circle measurements in views and renderings.",
#ifdef WCS_BUILD_VNS
"Remember: Visual Nature Studio Training Seminars are held several times a year. Check the 3D Nature web site for details."
#else // !VNS
"Remember: World Construction Set Training Seminars are held several times a year. Check the 3D Nature web site for details."
#endif // !VNS
}; // TipTable
//lint -restore
