// VocabTable.h
//
// #defines for Markov search table.
// Machine generated code, do NOT hand-alter.
// Created from file "commandlist".


extern unsigned long MarkovTable[];

#define VE_ADD                    29 /* ADd */
#define VE_ALIAS                  34 /* ALIas */
#define VE_ALL                    35 /* ALL */
#define VE_ANTIALIAS              43 /* ANtialias */
#define VE_ARCVIEW                49 /* ARcview */
#define VE_AS                     50 /* AS */
#define VE_ASPECT                 55 /* ASPect */
#define VE_ASSIGN                 59 /* ASSign */
#define VE_BACKGROUND             72 /* BACkground */
#define VE_BANK                   74 /* BANk */
#define VE_BORDER                 80 /* BORder */
#define VE_BOTTOM                 84 /* BOTtom */
#define VE_BY                     85 /* BY */
#define VE_CAMERA                 96 /* CAMEra */
#define VE_CAMVIEW               100 /* CAMView */
#define VE_CLEAR                 105 /* CLEar */
#define VE_CLOSE                 109 /* CLOSe */
#define VE_CLOUD                 111 /* CLOUD */
#define VE_CLOUDS                112 /* CLOUDS */
#define VE_COLOR                 118 /* COLOR */
#define VE_COLORMAP              121 /* COLORMap */
#define VE_COMMENT               127 /* COMMent */
#define VE_COMPOSITE             133 /* COMPosite */
#define VE_CONFIRM               139 /* CONFirm */
#define VE_CONTENTS              144 /* CONTents */
#define VE_CREATE                149 /* CReate */
#define VE_CURRENT               155 /* CUrrent */
#define VE_DATABASE              169 /* DAtabase */
#define VE_DEBUG                 175 /* DEBug */
#define VE_DEFAULT               180 /* DEFault */
#define VE_DEPTH                 183 /* DEPth */
#define VE_DIRLIST               190 /* DIRlist */
#define VE_DISTRIBUTION          200 /* DIStribution */
#define VE_DLG                   202 /* DLg */
#define VE_DOMINANCE             210 /* DOminance */
#define VE_DRAW                  213 /* DRaw */
#define VE_DXF                   215 /* DXf */
#define VE_ECHO                  223 /* ECHo */
#define VE_ECOSYSTEM             230 /* ECOsystem */
#define VE_EFFECT                235 /* EFFECT */
#define VE_EFFECTS               236 /* EFFECTS */
#define VE_END                   239 /* END */
#define VE_ENVIRONMENT           248 /* ENVironment */
#define VE_EXAGGERATION          261 /* EXAggeration */
#define VE_EXIT                  263 /* EXIt */
#define VE_EXPORT                267 /* EXPort */
#define VE_FACTOR                280 /* FACtor */
#define VE_FADE                  282 /* FADe */
#define VE_FDMS                  285 /* FDms */
#define VE_FIELD                 291 /* FIEld */
#define VE_FILENAME              298 /* FILEname */
#define VE_FILTER                301 /* FILTer */
#define VE_FIX                   302 /* FIX */
#define VE_FIXED                 304 /* FIXEd */
#define VE_FLATTEN               310 /* FLatten */
#define VE_FORCE                 315 /* FORCe */
#define VE_FORMAT                318 /* FORMat */
#define VE_FRACTAL               325 /* FRACtal */
#define VE_FRAME                 327 /* FRAME */
#define VE_FRAMES                328 /* FRAMES */
#define VE_FULL                  331 /* FUll */
#define VE_GENERATE              341 /* GEnerate */
#define VE_GLOBAL                346 /* GLobal */
#define VE_GRADIENT              354 /* GRAdient */
#define VE_GRID                  356 /* GRId */
#define VE_HALF                  364 /* HALf */
#define VE_HAZE                  366 /* HAZe */
#define VE_HEIGHT                371 /* HEight */
#define VE_HIGH                  374 /* HIgh */
#define VE_HORIZON               380 /* HOrizon */
#define VE_IMAGE                 387 /* IMAGE */
#define VE_IMAGELIB              391 /* IMAGELib */
#define VE_IMAGES                392 /* IMAGES */
#define VE_IMPORT                396 /* IMPort */
#define VE_INTER                 400 /* INter */
#define VE_JUMP                  404 /* Jump */
#define VE_KEYFRAME              412 /* Keyframe */
#define VE_LAKE                  421 /* LAKe */
#define VE_LATITUDE              427 /* LATitude */
#define VE_LAYER                 430 /* LAYer */
#define VE_LEVEL                 434 /* LEvel */
#define VE_LIGHT                 439 /* LIGht */
#define VE_LINE                  441 /* LINe */
#define VE_LOAD                  447 /* LOAd */
#define VE_LONGITUDE             454 /* LONgitude */
#define VE_LOOKAHEAD             461 /* LOOkahead */
#define VE_LOW                   462 /* LOW */
#define VE_MAP                   469 /* MAP */
#define VE_MAPS                  471 /* MAPS */
#define VE_MAPVIEW               475 /* MAPView */
#define VE_MATCH                 478 /* MATch */
#define VE_MAXIMUM               483 /* MAXimum */
#define VE_MEDIUM                488 /* MEdium */
#define VE_MODE                  492 /* MODe */
#define VE_MOON                  494 /* MOOn */
#define VE_NAME                  500 /* NAme */
#define VE_NEW                   502 /* NEw */
#define VE_NORMAL                507 /* NOrmal */
#define VE_OFFSET                516 /* OFfset */
#define VE_OPEN                  519 /* OPen */
#define VE_ORIGIN                524 /* ORigin */
#define VE_OVERSCAN              531 /* OVerscan */
#define VE_PALETTE               543 /* PALette */
#define VE_PARAMETERS            551 /* PARameters */
#define VE_PATH                  553 /* PATh */
#define VE_PICTURE               559 /* PIcture */
#define VE_POSITION              566 /* POsition */
#define VE_PREVIEW               574 /* PREview */
#define VE_PRIORITY              580 /* PRIority */
#define VE_PROJECT               586 /* PROJect */
#define VE_PROPERTIES            593 /* PROPerties */
#define VE_QUALITY               602 /* QUALity */
#define VE_QUARTER               606 /* QUARter */
#define VE_QUIET                 610 /* QUIEt */
#define VE_QUIT                  611 /* QUIT */
#define VE_RANDOM                619 /* RAndom */
#define VE_REFERENCE             632 /* REFerence */
#define VE_RELIEF                636 /* RELief */
#define VE_REM                   637 /* REM */
#define VE_REMOVE                640 /* REMOve */
#define VE_RENAME                645 /* RENAme */
#define VE_RENDER                648 /* RENDer */
#define VE_REQUEST               653 /* REQuest */
#define VE_REVERSE               658 /* REVerse */
#define VE_RUN                   660 /* RUn */
#define VE_SAVE                  673 /* SAVE */
#define VE_SAVEAS                675 /* SAVEAs */
#define VE_SCREEN                681 /* SCREen */
#define VE_SCRIPT                684 /* SCRIpt */
#define VE_SEGMENTS              692 /* SEGments */
#define VE_SET                   693 /* SET */
#define VE_SETTINGS              698 /* SETTings */
#define VE_SHADE                 703 /* SHADE */
#define VE_SHADOWS               706 /* SHADOws */
#define VE_SIZE                  709 /* SIze */
#define VE_SKY                   711 /* SKy */
#define VE_SNOW                  714 /* SNow */
#define VE_SPECIAL               721 /* SPECial */
#define VE_SPEED                 723 /* SPEEd */
#define VE_START                 728 /* STArt */
#define VE_STEP                  730 /* STEp */
#define VE_SUN                   733 /* SUN */
#define VE_SURFACE               738 /* SURface */
#define VE_TARGET                748 /* TArget */
#define VE_TITLE                 752 /* TItle */
#define VE_TO                    753 /* TO */
#define VE_TOP                   754 /* TOP */
#define VE_TREES                 758 /* TRees */
#define VE_TURNS                 762 /* TUrns */
#define VE_VARIABLE              771 /* VAriable */
#define VE_VECTOR                777 /* VECtor */
#define VE_VELOCITY              783 /* VELocity */
#define VE_WCSCONTENT            796 /* WCSContent */
#define VE_WCSFRAMES             802 /* WCSFrames */
#define VE_WCSPROJECTS           810 /* WCSProjects */
#define VE_WIDTH                 815 /* WIDth */
#define VE_WINDOW                819 /* WINdow */
#define VE_Z                     820 /* Z */
#define VE_ZBUFFER               827 /* ZBuffer */
#define VE_ZENITH                832 /* ZEnith */


/* EOF */
