######################################################################
# Automatically generated by qmake (1.05a) Wed Jul 9 13:52:53 2003
######################################################################

#TEMPLATE = vcapp
CONFIG += qt warn_on release thread
TARGET = superconductor
# REQUIRES = thread

# Input
HEADERS += client.h \
           datatypes.h \
           mainwindow.h \
           message_dialog.h \
	   scthread.h \
           server.h \
           wcs-client.h

SOURCES += datatypes.cpp \
           main.cpp \
           mainwindow.cpp \
           message_dialog.cpp \
	   scthread.cpp \
           server.cpp \
           wcs-client.cpp
